<?php

$aid = 'sharon';
$title = 'What the Toilet Sees';
$cid = c3;
$issueid = i5;
$body = 
"
<p>We walk around with our noses in the air<br/>
Trying to be who we want to be<br/>
Showing people that we have glam and we have flair<br/>
But the toilets see what we don't want people to see<br/>
<br/>
As bottoms go, a toilet doesn't get to choose<br/>
Who gets to grace its noble seat<br/>
But in the bathroom you can't win, you can't lose<br/>
A toilet just sees what you excrete<br/>
<br/>
My point is, the toilet never sees who you are<br/>
As far as I know, the toilet doesn't care<br/>
You could be a nobody, you could be a star<br/>
But there's a truth of which only the toilet is aware<br/>
<br/>
Toilets don't need to see past our rears<br/>
Or beyond the bathroom stall<br/>
We're just people who poop, year after year<br/>
Nothing else matters at all<br/>
<br/>
So before you obsess over things like money or fame<br/>
Promotion and the status quo<br/>
Just remember, we are all the same<br/>
Just ask the toilet the next time you go.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>