<?php

$aid = 'sharon';
$title = 'My Balloon Friend';
$cid = c3;
$issueid = i5;
$body = 
"
<p>Today I made a balloon my friend<br/>
Glossy and plump and dark<br/>
I saved him from an untimely end<br/>
And tucked him safely under my arm<br/>
<br/>
I promised him he wouldn't die<br/>
Not if I was around<br/>
Yet I couldn't keep my dear friend alive<br/>
His physical body is nowhere to be found<br/>
<br/>
Innocent children like my balloon<br/>
They attract the attention of mischievous folk<br/>
I could not save him, not from his doom<br/>
From pen-wielding students, ready to poke<br/>
<br/>
But the betrayers, the students of my own class<br/>
Surrounded me, cornered me in on all sides<br/>
I could not stop them, determined to harass<br/>
My darling balloon, so charming and wide<br/>
<br/>
They lunged for me, I let out a cry<br/>
And dropped my balloon, my wonderful friend<br/>
And as I watched with eyes open wide<br/>
I pleaded for mercy, knowing what my attackers would intend<br/>
<br/>
But they ignored my pleas, they viciously set<br/>
Upon my balloon, quivering in fright<br/>
With expressions of glee, they carried out their threat<br/>
A bang, and my friend was nowhere in sight<br/>
<br/>
Please understand, companion departed<br/>
I did not mean to betray you so<br/>
I'm sorry your murderers could not be thwarted<br/>
But you're now safe in heaven, safe, I know.<br/>
<br/>
Rest in peace, my darling balloon.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>