<?php

$aid = 'sharon';
$title = 'If the Shoe Fits...';
$cid = c1;
$issueid = i5;
$body = 
"
<p>Something tells me this isn't right.</p>
<p>I look down at my foot. The shoe fits all right. It's a rather yucky looking shoe since around three hundred twenty-two girls have tried it on and gotten their sweat and bits of dirt all over the glass.</p>
<p>But the point is, it fits.</p>
<p>And I'm pretty sure it's the wrong girl.</p>
<p>I mean, my original idea wasn't to have everyone try it on. My idea was to go around and ask if anyone had the other shoe. But there's some obscure law prohibiting foot-related solicitation, and who am I to change the law just to find a stupid glass shoe? Besides, it was a size four and three-quarters, narrow. It would have to be custom made - in our kingdom we go by halves, not quarters. I figured I could go around and ask people to try it on and see if it fit. Apparently <i>that</i> wasn't against the law.</p>
<p>Well, it fits this girl. And I'm pretty sure she's the wrong one. She's got straight platinum blonde hair. The girl I danced with at the ball had medium blonde hair with curls at the ends. Though that may have been due to a heat curler. I mean, you never know.</p>
<p>But does it really matter? I mean, I didn't even know the girl at the ball. It probably isn't a good idea to marry someone whose name you don't even know, but it was either that or the princess of the neighboring kingdom... who's fat, ugly, and a really bad dancer.</p>
<p>A <i>really</i> bad dancer.</p>
<p>I don't think my feet have been the same since.</p>
<p>Speaking of feet.</p>
<p>This girl has size four-and-three-quarters feet, narrow. Go figure. Now I realize I should have just sent out a notice for girls with 4 3/4 size feet, narrow.</p>
<p>Hmm. This is a bit of a dilemma.</p>
<p>Do I tell this girl - who is, admittedly, quite excited now - that she's just one of the few people with tiny narrow feet? Or do I just go ahead and marry her?</p>
<p>Oh, the choices.</p>
<p>I was never good at turning down women. I almost married that fat old princess because I didn't want to tell her that I couldn't stand bad dancers. At the last minute I told her father I was taking a seventeen-day vow of celibacy and couldn't consider any marriage proposals at the moment.</p>
<p>Hmm.</p>
<p>Then again, what's the difference between one nameless-size-4-and-three-quarters-foot and another? Really, the hair color isn't that different. For all I know it could be the same person.</p>
<p>To me, there's really no difference between one stranger and another. Does it really matter?</p>
<p>Is this the girl I've been looking for? What if by fate we're meant to be together? Fate wouldn't throw the wrong girl in my path, now, would it?</p>
<p>Well if the shoe fits...</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>