<?php

$aid = 'raymond';
$title = 'Movie Review: Fargo';
$cid = c12;
$issueid = i5;
$body = 
"
<p>Damn, this film is very good.<br/>
I adore this film more than I should.<br/>
But why, oh why do I love it so?<br/>
Well, the answer to this question you shall know.<br/>
<br/>
The characters are developed well.<br/>
The plot, while typical, does excel. <br/>
The dialogue is also great.<br/>
Its originality and humor, no one can debate.<br/>
<br/>
Actor Bill Macy, who I hold I much regard,<br/>
Plays the man, Jerry Lundegaard.<br/>
Jerry is not very bright.<br/>
But when he talks to people he is very polite.<br/>
<br/>
The movie opens with this man<br/>
Who, in financial desperation, concocts a plan<br/>
To hire two men to kidnap his wife<br/>
So they can split the ransom and go on with life. <br/>
<br/>
Steve Buscemi plays one of the men, named Carl.<br/>
He curses, moans, whines, bitches, and snarls.<br/>
Peter Stormare plays his associate, Grimsrud.<br/>
He's a very big man and is built like wood. <br/>
<br/>
But the kidnapping goes pretty awry<br/>
For Grimsrud kills a cop and two passers by.<br/>
And so, without hesitation<br/>
The police begin an investigation.<br/>
<br/>
And so, we're introduced to Marge Gunderson,<br/>
A pregnant sheriff who's police work cannot be outdone. <br/>
She solves the crime, piece by piece<br/>
And no matter how tough it gets, she will not cease.<br/>
<br/>
Jerry is in a world of shit<br/>
And he does not like it. No, not one bit.<br/>
In several scenes, you see him pout<br/>
As he tries to worm his way out. <br/>
<br/>
But things for Jerry get worse and worse<br/>
And into the story we are immersed<br/>
Until the conclusion, violent and depraved,<br/>
Where we see the woodchipper scene, of which I have frequently raved. <br/>
<br/>
Some have complained about the frequent \"yah's\"<br/>
While others have complained about the violence, which is graphic and raw.<br/>
But I must say the violence was cool<br/>
And the \"yah's\" help make the film a jewel.<br/>
<br/>
The accents gave the film a more authentic feel<br/>
And they helped the characters seem more real.<br/>
The film is also very well scored<br/>
And Frances McDormand, who plays Marge, deserved that Academy Award. <br/>
<br/>
I think this is a great movie, as you can tell<br/>
And if you try to convince me otherwise, I'll see you in hell.<br/>
For a better review, go to the sites below  <br/>
And if you are still not convinced of its greatness, go back to watching you're crappy romance movies and tv shows.  <br/>
<br/>
<a href=\"http://rogerebert.suntimes.com/apps/pbcs.dll/article?AID=/19960308/REVIEWS/603080302/1023\">http://rogerebert.suntimes.com/apps/pbcs.dll/article?AID=/19960308/REVIEWS/603080302/1023</a><br/>
<a href=\"http://rogerebert.suntimes.com/apps/pbcs.dll/article?AID=/20010405/REVIEWS08/104050301/1023\">http://rogerebert.suntimes.com/apps/pbcs.dll/article?AID=/20010405/REVIEWS08/104050301/1023</a></p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>