<?php

$aid = 'editors';
$title = 'Editor\'s Note: Issue 5';
$cid = c19;
$issueid = i5;
$body = 
"
<p>Hello all!</p>

<p>Welcome to Issue 5 of Amalgam Magazine - written by the teens, for the teens. Well, a lot has happened in the past month, hasn't it? AP's, SAT's, SAT II's have all started and (mostly) finished... Sports CCS events came and went, and overall it's now \"chill\" time before the cram for finals comes up.</p>

<p>So, within a month, our seniors will be graduated and our juniors (class of '07) will be our new seniors. It's quite hard to believe so much time has passed! Even in Amalgam - this 5th issue marks our sixth month! And of course, our sixth month has to come with great improvements.</p>

<p>We have now added a forum onto Amalgam; in addition to the comments system (which will still be there, don't worry!), you can put your thoughts and opinions of the pieces on said Forum; give ideas and make suggestions!</p>


<p>Forum: <a href=\"http://s11.invisionfree.com/AmalgamMag/index.php\">http://s11.invisionfree.com/AmalgamMag/index.php</a></p>


<p>Along with this, I'd like to announce the opening of a Sports Column as well as a trial basis for a religion column. Submit your questions to our religion columnist, Aneesh Goel, at <a href=\"mailto:religion@amalgammag.com\">religion@amalgammag.com</a>.</p>

<p>\"I'll write a response to religious questions, no matter how obscure (I'll research it if I have to, but fair warning - if it's too obscure, I'll put up the question along with a 'I couldn't find the answer' type message); I'll also respond to religious claims you'd like to make.  By that, I mean that if you've got some great proof for your faith, or some particularly strong bit of appeal as to why your beliefs are special and important, I'll respond with a rebuttal and counterargument to your statement.  If anyone decides they want to rebut my rebuttal and send it to me, go ahead - I'll respond to that in the next issue too.\"</p>

<p>Keep in mind, you can also ask him questions via the forum; he will be available to respond there if it's a minor question in between issues.</p>

<p>Another thing I'd like to point out is that this month we have a special feature. At the Harker School, students in the sophomore class were given an option to write a personal nightmare essay; Amalgam collected a variety of these essays and have posted them for you to read!</p>

<p>My fun fact for this editorial; have you guys ever been to <a href=\"http://www.google.com/romance/index.html\">http://www.google.com/romance/index.html</a>? It was Google's April Fools Joke this year; if you read the process and FAQ, you're guaranteed to be amused. At every turn, they poke fun at the stupidity and obliviousness of humanity.</p>

<p>With that, I leave you all to enjoy Issue 5; once again, our writers produced an amazing turnout, and I especially recommend Jessica Hsueh's Personal Nightmare and Raymond Paseman's Fargo review. Enjoy!</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>