<?php

$aid = 'ruchi';
$title = 'Interviewing a Local Band: Why-Minus';
$cid = c13;
$issueid = i6;
$body = 
"
<p>If you attend the Harker School, you're most likely familiar with the \"indie emo jazz\" band Wh<i>y</i>-Minus. In fact, you're probably familiar with the two members of said band - Roger Kim and Anton Sepetov.</p>
<p>For those of you who aren't quite familiar with Why-Minus, I managed to interview Roger (sadly, Anton was unavailable.) about the band. Naturally, the first thing I asked him was the reason behind the band name - Why Wh<i>y</i>-Minus?</p>
<p>Roger had quite a deep answer for me - \"I don't like pretending I'm in a band,\" he said. \"I don't want to take us too seriously and we don't play shows that much. [...] It's mostly just a fun thing.\" However, he had another answer to go along with that.</p>
<img class=\"right\" src=\"inc/MSfiles/109/1.jpg\" alt=\"Roger Kim, playing the guitar\" />
<p>Harker was having a battle of the bands, and randomly, Roger decided he wanted to be in it. Anton jumped the band wagon (excuse the pun) and decided to enter with him; because they decided this in chemistry class, they picked out the name Wh<i>y</i>-Minus. After three practices, they performed, and thus were \"born.\"</p> 
<p>A breakdown of the band is quite simple; Roger is known as \"Lead Everything.\" There's not much of a surprise there. If you've been to a gig, Anton plays the keys while Roger sings and plays the guitar... and he also writes the songs. However, Roger's steadfast about his band mate, saying, \"It's not mainly me. Sure I do a lot of the work, but it wouldn't be anything without Anton. If I need anyone to play with, it's going to be with Anton, definitely.\" Other comments about Anton were vague to say the least. \"He's tall. He's really chill... I don't know,\" Roger said, confused when we asked him about the missing member.</p>
<img class=\"left\" src=\"inc/MSfiles/109/2.jpg\" alt=\"Anton Sepetov\" />
<p>Shockingly, there's one \"behind-the-scenes\" member of the band: Jeff Lee is considered part of Wh<i>y</i>-Minus's essence. \"I don't know about Jeff... he's our friend and ...whatever,\" Roger said, when I inquired about Jeff's main role.</p>
<p>If you haven't realized, Wh<i>y</i>-Minus is still a small band, inspired by anything original. \"If someone's doing something creative, watching anyone else be creative... that's inspiring,\" Roger said.</p>
<p>Lately, not too many people have heard much about the band. Like others, I made the mistake of thinking that because it was the end of junior and beginning of senior year, the band would be breaking up. Roger corrected me, reiterating that they were not trying to be a famous band and go on world tours. The band was for fun, for creativity - not for the sake of becoming famous.</p>
<p>Since the band has been around for about one and a half years, I couldn't help but ask Roger's favorite, craziest memory. The answer astonished me...</p>
<p>\"So once we got a show at this place called San Jose State over summer and then uh, [...] we emailed them, uh, and Anton told them fifty girls [were coming... they said], 'We'll put you first' [...] Five people show up and three more people we snuck onto the guest list [...] Only 5 people actually paid. You had to be there, funny, just being on stage, and I [messed] up one song because I couldn't remember the words. And me and Anton sang, and it was horrible. So like, it was more like hanging out because there was only eight people and most of them were our friends and the guy's like 'oh, can you please stop swearing into the mike?' and there was one person roller skating but really it's just a [crappy] venue...\"</p>
<p>This answer, of course, led me to ask about groupies. \"Zero? A million? Uh, what's a groupie?\" Roger answered, an awkward look gracing his face. He then reiterated that most of the audience was Harker itself - it had become the band's gimmick. They were the people that everyone knew; \"I know those kids, it's them,\" Roger tried to explain.</p>
<p>After that, the interview began to wind down; he mentioned that the band's favorite song started with \"Shut the Hell Up,\" a testament to the \"emo\" section in the band's genre.</p>
<p>To find our more or contact Why-Minus, take a look at their <a href=\"http://myspace.com/whyminus\">MySpace</a> or email <a href=\"mailto:Rk278488@msn.com\">Rk278488@msn.com</a>. To listen to some of their songs, check out their MySpace or <a href=\"http://www.purevolume.com/whyminus\">PureVolume</a> site.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>