<?php

$aid = 'raymond';
$title = 'Movie Review: Unforgiven';
$cid = c12;
$issueid = i6;
$body = 
"
<p>WATCH THIS MOVIE RIGHT NOW!</p>

<p>How many of you have heard of Clint Eastwood? Hopefully all of you. You see, he won all these awards in 2005 for this little movie he made called Million Dollar Baby. For some (retarded) moviegoers, this was the first time anybody had heard his name announced in an awards ceremony before. For many others, it was the second time, since they first heard his name announced a year earlier while watching the Best Director nominations for Mystic River. Most moviegoers, however, remember Clint Eastwood as the guy who made this brilliant movie all the way back in 1992 called Unforgiven, which was nominated for nine Oscars and won four, including Best Picture. An even smarter moviegoer would know him as Dirty Harry, or The Man with No Name. An even smarter one would know him as both. But the smartest one of all would know him for ALL of these.</p>

<p>I am appalled at how little this guy is known by my friends. Most of them didn't know what Dirty Harry was. HELLO? Harry Callahan is only one of the most popular American icons in history. I'm also appalled at how much flack the western genre gets from idiot moviegoers that I hang out with. They're under the impression that westerns are boring. I ask them what westerns they've seen, and here are their responses (I'm serious):</p>

<p>\"Westerns are boring. I saw this one where Clint Eastwood wears a bulletproof vest. I don't remember much about it, but it was pretty stupid.\"</p>

<p>\"Well, I saw The Good, the Bad, and the Ugly, and it was good, but westerns are still boring.\"</p>

<p>Regarding the first quote: Ok, first the guy didn't even know the title of the movie, A Fistful of Dollars. Second, he only watched ONE WESTERN and from that said that westerns are boring in general. Third, the movie is regarded as a classic by pretty much everybody, so saying that it's stupid without giving any justification whatsoever somewhat undermines his or her credibility. Fourth, YOU DON'T REMEMBER ANYTHING ABOUT THE MOVIE, SO HOW CAN YOU COMMENT ON ANY OF IT? I suppose an equivalent to that statement regarding the Sci-Fi genre is:</p>
<p>\"Sci-Fi movies are boring. I saw this one that George Lucas made with these guys with blue and red swords. I don't remember much about it, but it was pretty stupid.\"</p>
<p>By the way, I do think Star Wars is stupid as hell and doesn’t deserve any of the popularity it has gotten, but most of the public disagrees with me. And me offering no justification behind my opinion doesn't help me prove my cause.</p>

<p>Regarding the second quote: Alright, so here you've only seen one western, and you liked it, and you STILL THINK THE WESTERN GENRE IS BORING? WHAT THE HELL, MAN? EXPLAIN TO ME HOW THAT MAKES ANY SENSE.</p>

<p>My view of the western genre:</p>
<p>Well, it's like any other genre. There are good westerns (Unforgiven, TGTBTU), and there are bad westerns (Once Upon a Time in the West, Quigley Down Under); there are good action movies (Die Hard, Man on Fire), and there are bad action movies (XXX, Bad Boys 2); there are good dramas (12 Angry Men, Capote), and there are bad dramas (Crash, A History of Violence); there are good science fiction movies (Blade Runner, Terminator 2), and there are bad science fiction movies (Battlefield Earth, Rollerball [remake]).</p>

<p>Oh right, this review is supposed to talk about Unforgiven. Well, basically IF THERE IS ONE WESTERN TO SEE, THIS IS IT. For a review of the actual movie, I suggest that you look at the one written by <a href=\"http://ruthlessreviews.com/movies/u/unforgiven.html\">Ruthless Reviews</a>. Yes, I know I didn't actually comment on the movie. Yes, I know I wrote a rant against stupid people who think the western genre sucks, and yes, I don't really care. I said what needed to be said, so deal with it. Oh, and watch Unforgiven. If you like it, you're not an idiot, and if you don't like it, well, I'm afraid you are an idiot.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>