<?php

$aid = 'gwynnie';
$title = 'Erase';
$cid = c3;
$issueid = i6;
$body = 
"
<p>Perhaps if I could build a wall<br/>
I'd never change his perspective<br/>
Yet it's hard to keep my mouth shut<br/>
I guess I'm glad he's not perceptive<br/>
<br/>
They say it's noble,<br/>
To bury this secret for years<br/>
Yet is it really my choice to make?<br/>
To cause more agony, more tears?<br/>
<br/>
Is it my-<br/>

To rip apart this great illusion<br/>
Placed before the naive world<br/>
I can't stand to see him withdraw<br/>
Like a flower dying unfurled<br/>
<br/>
Words attacking, slashing down<br/>
The painting of respect and hope<br/>
Could I become that ultimate betrayer?<br/>
Could he take it; could he cope?<br/>
<br/>
Is it my place...<br/>
<br/>
A million questions flood my brain<br/>
Yet none of them are answered<br/>
He is still so young and free<br/>
I'd pierce his heart, the callous lancer<br/>
<br/>
So I'm left to never tell a story<br/>
From which nothing good would come<br/>
Is it so selfish to want him happy?<br/>
To live through him, because I'm too numb?<br/>
<br/>
Is it my place to erase?</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>