<?php

$aid = 'raymond';
$title = 'Movie Review: The Proposition';
$cid = c12;
$issueid = i6;
$body = 
"
<p>Well, I finally got my dad to take me to see this movie, and I loved every single minute of it. Since I've spent quite a bit of this year watching tons of crap like X-men: The Last Stand, The Da Vinci Code, Mission Impossible III, V for Vendetta, Crash, etc., a great movie like this was pretty refreshing.</p>

<p>The movie opens with Captain Stanley interrogating two brothers, Charlie and Mikey. These brothers are apparently part of the Burns gang, led by their older brother Arthur, who have recently raped and murdered a local family. Stanley offers Charlie a proposition: go out and kill Arthur, and Stanley will let him and Mikey free. However, he also warns Charlie that if he does not return by Christmas, Mikey will be hung. Apparently, Charlie and Mikey are really close, and Stanley knows that Charlie will do anything to save his little brother. So, Charlie embarks on his quest, which proves harder than he initially thought. Once he encounters Arthur, he doesn't even have the heart to tell him that Mikey is about to be hung in a couple days, let alone kill him. Of course, he must choose between loyalty or justice at some point, blah blah blah. Mikey is also a little crybaby when in prison. He is mercilessly taunted and beaten by guards and villagers.</p>

<p>But the real brilliant part about this movie is the development of Captain Stanley. At the beginning, he seems like the stereotypical corrupt sheriff who employs brutal methods upon inmates. I mean, the first thing he does is beat Mikey in the face with a pistol. But as the movie progresses, we learn more and more that he only wants to uphold justice. He understands that Mikey, being the crybaby he is, most likely didn't commit any crimes. He desires justice more than anything, and he knows that Arthur is the one who needs to be punished for the rapes and murders. In fact, Captain Stanley might be the most moral person in the entire movie. We're also given insight on Stanley's home life. He lives a normal life and has a wife who loves him. There's even a scene where he has Christmas dinner with her. Of course, something terrible happens afterward, but whatever.</p>

<p>I have heard many complaints about this movie. Some examples include:<br/>
<br/>
1. &nbsp; &nbsp; &nbsp; Too violent<br/>
2. &nbsp; &nbsp; &nbsp; Plot is hard to follow<br/>
3. &nbsp; &nbsp; &nbsp; Stanley's character development made me feel cheated<br/>
4. &nbsp; &nbsp; &nbsp; The ending sucked</p>

<p>Well, the movie is rated R for strong grisly violence and language. Of course, I didn't think the movie was violent at all, but that's just me. While the movie isn't any bloodier than the average action film, many comments I read on forums said that the gritty realism made the violence seem much more disturbing. As for the plot, it's easy enough to understand if you PAY ATTENTION. Be warned, however, that if you do not pay attention, you will most likely be lost. The ending requires lots of thought in order to understand the character's motives, but once that thought is put in, the ending makes a lot more sense.</p>

<p>What I don't understand is how anybody can possibly feel cheated about the development on Stanley. I mean, character development is supposed to be good, right? It adds dimension, and it makes the character seem more human. And here, it adds for some unexpected twists that fit really well into the movie.</p>

<p>It's a shame that great movies such as The Proposition get such a limited release while steaming piles of crap like X-men: The Last Stand go off and break box office records domestically. And sadly, this review will probably not be posted onto Amalgam until after its theatrical run. However, if you do manage to find a theater where this is playing, do yourselves a favor and go see it. This is what movies are supposed to be.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>