<?php

$aid = 'editors';
$title = 'Editor\'s Note: Issue 6';
$cid = c19;
$issueid = i6;
$body = 
"
<p>Hey everyone!</p>

<p>It's hard to believe that yet another month has passed - for most of us, the past few weeks have been filled with several memorable (although not necessarily lovable) things, like finals and graduation. All in all, though, it's now time for summer vacation.</p>

<p>For most of us, summer only started last week - and I hope you all intend to enjoy it fully. After all, what can be better than staying out late on a weekday, spending a full day hanging out with your close friends, or just sleeping till two in the afternoon eight or nine days in a row?</p>

<p>To back track a little bit, while I was supposed to be studying for finals, I ended up browsing the web (yet again) and I came across another amusing - yet slightly sadistic - website. I'm positive that you all have been here before... after all, this is somewhat famous. I had visited it a few times before, and was delighted to stumble upon the link again.</p>

<p>I hope you have fun browsing <a href=\"http://people.freenet.de/schnubelken/bunnys/\">Bunny Suicides</a>. I know that I myself enjoyed it - and if you have a sick sense of humor, you will as well.</p>

<p>With that, I hope you all enjoy Issue 6 of Amalgam Magazine! I personally enjoyed <i>The World Needs to be Invaded by Aliens (And I Mean the Little Green Kind)</i>. Also, check out the Why-Minus songs on their web sites, listed in the interview.</p>

<p>With that, once again, enjoy!</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>