<?php

$aid = 'rollingrabbit';
$title = 'When to Stop';
$cid = c15;
$issueid = i6;
$body = 
"
<p>So there I was. And, well, there <i>she</i> was. This time, no boyfriend. What luck! Sure, there were two other girls with her, but that was fine. I had my backup man behind me in case I needed him. Maybe I have a bit too much time on my hands. After all, when a high school student goes to the mall for women, and a freshman at that, it's really a bit sad. Of course, I wasn't serious. I was just entertaining myself.</p>

<p>Ok. So step one in my plan is to pick a target. Well, unfortunately, they don't come along very often. Usually the only people I see are 30-year-old women on their lunch break. Not really my type.</p>

<p>After step one, the steps really merge into spontaneous pick up lines and reactions. So, I stepped up to the plate. She was talking with her friends in front of Starbucks with a drink, presumably a very hot drink. I made a mental note to dodge flying liquids and walked directly up to her. The next part becomes a little bit shady in my mind for reasons that will soon become apparent. I will try to give the most accurate dialogue I can.</p>

<p>She was talking with her friends, her back toward me. I walked up behind her and stopped. One of her friends noticed me and alerted her of my presence. \"Hi. Um, I was wondering if I could have two seconds of your time.\" Most likely assuming it was something simple like directions; her friends continued their chat with each other while their friend handled me.</p>

<p>\"Oh, um, sure,\" she responded quite politely. \"What's up?\"</p>

<p>\"Thank you very much,\" I said happily. She waited for me to ask my question and silence filled the time. Finally, she asked a bit puzzled, \"Uh, yes?\"</p>

<p>That was my cue. \"Oh, that was it. I just needed those two seconds of your time. One to get a good look at you, and the other to fall in love with you.\"</p>

<p>She took about 2 and a half seconds to just stare at me. This was the part where the young lady will normally either walk away with her friends laughing, walk away with her friends staring at me with disgust, or telling me that she has a boyfriend who will come and eat me alive.</p>

<p>However, this particular lady was a bit different. She tapped on the shoulder of one of her friends, gave her coffee, and stared at me for another second. I could have sworn I saw her eye sparkle for a second.</p>

<p>Now at this point in time, I was optimistic. To me it seemed like she was about to go along with my little joke and fall madly in love with me for 10 seconds. To my dismay, I was quickly reminded of my bad luck with women.</p>

<p><i>*Smack!*</i> And not the kind of smack I hoped to get from a woman. Not the kiss kind of smack. It was the kind that hurts. It was the slap kind of smack. Now, in the past I was a huge fan of the joke where you turn your face toward the slap when you pretend to slap yourself. What I never really realized was how this habit carried into my <i>actual</i> life. I don't think you need to have taken physics to guess what happens when you run into something aiming for your face.</p>

<p>I held my ground with my face turned in the direction the slap came from, eyes squinting and mouth half open. I could have said ow and accepted defeat. There is a point where you need to stop and admit defeat. At this point in time, I hadn't realized this actually applied to me. The girl, who was now smiling with satisfaction, was still looking at my red cheek. I brought my face back to it's normal position and smiled back at her. \"Thank you again. This means so much to m-\"</p>

<p><i>*Smack!*</i> It came for the same red cheek as before. But this time, I wizened up. I didn't turn my face toward the slap. This time I left my head completely still. In hindsight, I suppose I should have turned my face away from the slap. But, I didn't, and the slap burnt my cheek again. This time I was pulled a bit to the right by her slap, so I stumbled a few steps. By the time I turned to look up again, she was walking away with her friends laughing. This really didn't make it any easier on me.</p>

<p>With a great sigh, I turned toward my laughing friend and socked him in the gut for the help. It was fun while it lasted. But I had realized my mistake. I was a smart guy. I walked away with knowledge that would serve me for the rest of my life...</p>

<p>Guys, turn your cheek away from the slap.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>