<?php

$aid = 'raymond';
$title = 'Fargo Sonnet';
$cid = c3;
$issueid = i6;
$body = 
"
<p>In goes the leg, and like chunks of beef<br/>
It gets ground up to burgers. Chip chip chip.<br/>
And out spurts rivers of blood. Drip drip drip.<br/>
The hungry Woodchipper causes much grief.<br/>
Oh, Carl could only think about his dough<br/>
And wouldn't give Grimsrud his car because<br/>
He wanted it for himself. So, what does<br/>
Grimsrud decide? \"Into the Shredder he goes.\"<br/>
Then in comes the great Marge Gunderson, who<br/>
Blows a brick red hole into Grimsrud's thigh.<br/>
All on this day, very nice and sunny,<br/>
So many have died out of greed. And to<br/>
Grimsrud, Margy says, her back nice and high:<br/>
\"There's more to life than a little money.\"</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>