<?php

$aid = 'rachelf';
$title = 'Club Review: Robotics';
$cid = c7;
$issueid = i6;
$body = 
"
<p>At the annual club fair, I was lounging behind the Robotics club table.  A group of freshmen passed by and I snatched the opportunity to recruit them.</p>

<p>\"Robotics? Don't you like, program and stuff?\" one of them laughed. \"That sounds too complicated. Maybe later.\" With that, they ran off towards another club.</p>

<p>To my disappointment, I received a similar reaction from many others at the club fair.  Of course, I'm not condemning freshmen, but it seems like people have some severe misconceptions about the Robotics Club.  Besides, we had a shiny 13-foot tall robot in the front of the gym with a giant \"2005 DAVIS REGIONAL WINNERS\" banner hanging on the top. How is that not eye-catching?</p>

<p>Those who declined to join mostly fell into two categories: they thought robotics was interesting but thought that they didn't have enough knowledge to join, or they simply weren't interested in the technical side of robotics.</p>

<p>Contrary to popular belief, no previous experience is necessary to join.  Before the actual build season, we have training sessions focused on the knowledge that members will need during build.  We collectively come up with a design and plan out how to efficiently build it and still have time for testing in a limited timeframe.  And robotics isn't only for the technically inclined: there is also the Public Relations subteam, which finds sponsorships and mentors and organizes outreach and communication between local teams.  PR is also in charge of media: maintaining the website, creating animations, and taking pictures and videos during build and competition.  Unfortunately, not many potential recruits know about PR! (There were only two people on PR this year, so it would be great if more decided to join...)</p>

<p>Another common misconception: Robotics is only for guys.  Due to this stereotype, there are only four girls currently involved.  However, all of them are (relatively) mentally stable, and they aren't looked down upon for being females on a robotics team. In fact, three of them are officers, and the fourth is a subteam lead.</p>

<p>What does all of this work go towards? After building the robot, we compete at regional competitions against other schools' teams.  The contest isn't a destructive BattleBots fight, but more like a sports game.  This year, it was a combination of basketball and hockey, and the year before that, tetrahedron-shaped game pieces had to be placed on top of goals to score.  In addition, teams are placed in randomly chosen alliances every match, so a lot of strategizing is necessary.  Between matches, we also get the chance to talk with other teams and learn about their robots.  The competitions are really unforgettable experiences that complete the whole build season.</p>

<p>If you're interested, check out the <a href=\"http://www.harker-robotics.org\">Harker Robotics</a> team site, or the <a href=\"http://www.usfirst.org/robotics\">official contest website</a>. If you are a Harker student, meetings are on Thursdays in Dr. Nelson's room (Rm. 29). If you are from another school, I strongly encourage you to check out your school's robotics team or talk with your administration in starting one.</p>

<p>/* end recruiting plug */</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>