<?php

$aid = 'brittany';
$title = 'Guardian Angel';
$cid = c3;
$issueid = i6;
$body = 
"
<p>I used to be good at this<br/>
I guess even guardian angels lose their knack sometimes<br/>
We sort of go in to hibernation<br/>
Want to fall off the face of the world<br/>
But we can't<br/>
So we end up doing the best we can<br/>
But it's not enough<br/>
We can't figure out the things that used to be so clear<br/>
So we scream in frustration<br/>
And watch as the people we try to help<br/>
Fall deeper and deeper in to darkness<br/>
And scream because we want to forget them<br/>
Because they don't want to be good<br/>
They don't want to be helped<br/>
But we can't<br/>
Not forever<br/>
Not even for a good period of time<br/>
We see the good in the good<br/>
Even if they can't see it in themselves<br/>
We catch our second wind<br/>
And start over again</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>