<?php

$aid = 'brittany';
$title = 'Belladonna';
$cid = c3;
$issueid = i6;
$body = 
"
<p>Poor Belladonna<br/>
How she must have felt...<br/>
Abandoned, betrayed, lost<br/>
Not from malice but a lack of thought<br/>
And when her tears were spent<br/>
The wounds scarred over and she moved on<br/>
Never to forget, always to try<br/>
She lost herself in people<br/>
Rejected, controlled, fought back<br/>
And now I know<br/>
Yet is took so long to realize<br/>
For perhaps a belladonna<br/>
Is more romantic that a human being</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>