<?php

$aid = 'brittany';
$title = 'Passing Through';
$cid = c1;
$issueid = i6;
$body = 
"
<p>Sam had been mowing the lawn in the backyard when he'd noticed the girl. She was about his age, maybe a bit younger, with long blond hair and piercing grey eyes. He didn't know how she'd gotten up there, but she stood on the fence, watching him, as if perhaps he was the only interesting thing in the world. A breeze came by, and the skirt of her white dress billowed against it, strands of her hair blowing across her eyes.</p>
<p>And she kept staring.</p>
<p>\"Hello?\" he ventured. The girl barely made any sign she had heard him, only tilting her head a bit to the left. There was a good minute or so of silence, and then...</p>
<p>\"Hello.\"</p>
<p>Her voice - it was normal, it sounded normal, and yet... there was something young about it. He found staring back at her was the easiest thing to do. It felt like it'd be more awkward to look away.</p>
<p>\"You're gonna fall from up there.\"</p>
<p>\"Do you really think so?\" It wasn't a sarcastic question, or even an actual question really. It was more a statement of wonderment, as if you'd told her faeries lived in the garden and she already knew but wanted to see what you thought.</p>
<p>\"Why are you here?\"
<p>That seemed to catch her attention.</p>
<p>\"Why are you?\" she returned.</p>
<p>\"I live here.\"</p>
<p>She nodded once, slowly. Another period of silence overtook them, longer than the first, and he noticed how cold the wind felt.</p>
<p>\"Do I know you?\"</p>
<p>The girl made no notice she'd heard him this time, keeping her steady gaze. A gust shook the yard, sending leaves down from the trees in a cascade against the overcast sky.</p>
<p>\"No...\" She said it so quietly, he wasn't sure if he'd heard or imagined it. For the first time since she'd appeared, the girl looked away, walking along the fence. \"I didn't want to bother anyone I knew, and you seemed so nice.\" She came to a section where cinderblocks had been stacked next to it, and she stepped down, moving from there on to the ground.</p>
<p>\"I've seen you somewhere before.\"</p>
<p>\"No, you really haven't.\" She looked back up at him. \"You just think you have.\"</p>
<p>Maybe it was because she was closer, but for the first time he could see emotion in her face, an indescribable expression. It wasn't longing, it wasn't knowing... it wasn't even sad, although he could tell she wasn't happy. Somehow it hinted at all of them, without truly being them at all. She came closer, and the nearer she came, the more he felt like he was in a photograph. The sky, the wind, the grass, her eyes, her hair... it was perfect, and yet it wasn't too perfect, because it existed. It simply was.</p>
<p>\"I know you...\" the words barely came out as a whisper.</p>
<p>\"Do you?\" she asked softly. She was so close, so unbelievably close. It seemed there had never been an intention to stop moving forward, because in a moment their lips met in a single, perfect kiss. There was no passion, no thought. Just a simple action that completed the world.</p>
<p>They parted, and their eyes met again. Somehow hers had changed from the cold, piercing grey of before. They had warmth, they had feeling. Her eyes mirrored something inside of him that would be there until the day he died and never, ever change.</p>
<p>\"I wanted to touch someone before I left.\" There was the faintest hint of a smile in her voice as she said it, and the words seemed to answer a question he had never known he wanted to ask.</p>
<p>\"<i><b>Sam!</b></i>\"</p>
<p>The boy's head turned sharply at his mother's voice as she walked out onto the porch, one hand still on the back door.</p>
<p>\"It's starting to rain. Get inside, you can finish the lawn in the morning.\" She left, and he looked back to a half-cut lawn, perfectly lit by the overcast sky.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>