<?php

$aid = 'sharon';
$title = 'Tell Me What I Want to Hear';
$cid = c3;
$issueid = i6;
$body = 
"
<p>Tell me lies, tell me lies<br/>
Hide the truth and tell me lies<br/>
Tell me what I want to hear<br/>
Your breath, your words, soft in my ear<br/>
<br/>
Tell me that I'm beautiful, tell me that I'm smart<br/>
Tell me that I'm talented, warm my painted heart<br/>
Twirl your finger in my dyed hair, and say it's fair<br/>
Touch my sticky lips, and say these words with pretend care<br/>
<br/>
I'll tell you, show you what to say<br/>
How to sugar my glossy day<br/>
I'll pretend to love you if you pretend to love me<br/>
I'll pretend to be happy, I guarantee<br/>
<br/>
Tell me lies, tell me lies<br/>
Hide the truth and tell me lies<br/>
Tell me what I want to hear<br/>
Your breath, your words, soft in my ear.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>