<?php

$aid = 'willy';
$title = 'Destiny in the Making';
$cid = c1;
$issueid = i7;
$body = 
"
<p>As I recall, I was at a local park enjoying the summer weather with a nice
walk and some fresh air when I saw her leave.  A woman of sixty-five or so 
years feeding the birds with bread crumbs was sitting alone on a bench. 
Her hair hadn't quite finished the transition from gray to white, but it was 
getting there. She wore a ragged blue sweater that looked like it had been 
knitted out of a hairball coughed up by a cat she might have owned.  And 
beside her was her purse.  The purse that sent me spiraling down the road 
of destiny.  For when the old lady was finished feeding the birds, she got 
up and left- forgetting her purse.  There it was, all by itself.  Wow.  And 
near as I could tell, no one else was yet aware of it.</p>

<p>Normally, being the (ahem) good person I am, I would have picked the purse up, 
hurried up to the old lady, and promptly returned it to her.  But today... 
Today was a different day.  I don't know why I felt such a strong change of 
heart from my normal self, but when I looked again at that purse, sitting 
there all by itself... a wave of pure greed overtook me.  I would have that 
purse!  The contents, whatever they may be, would be mine!</p>

<p>I quickly checked over my shoulder to see if anyone else that was in the 
area had yet noticed. No one seemed to have, but to my dismay I found 
that a mother watching her baby in his stroller would have no problem 
noticing me take the purse if she just so happened to look up.  Annoyed, I 
stood there, arms crossed and facing away from the purse so as to appear 
innocent, hoping against hope that that mother would just get up and roll 
her stroller somewhere else already, when I heard quiet, almost furtive 
steps behind me.  Slowly, to avoid suspicion, I turned and saw another kid 
about my age standing over the derelict purse, an air of mischievousness 
about him.  He wore a ripped, baggy, denim jacket, with a baggy black shirt on 
underneath that bore an obscene message I have selectively chosen to not 
repeat here, dirty, baggy, jeans, and a black ski cap.  Why he was wearing a 
ski cap in warm weather such as we were experiencing I can't say, but I 
surmise that he was just another typical adolescent trying to project 
himself through his clothing.</p>

<p>Apparently he didn't much mind the nearby mother with her stroller, for at 
that moment, he bent down, snatched up the purse, did a quick survey of its 
inventory, smiled maliciously, and dashed off.</p>

<p>Well you can imagine my predicament.  There I had been, within reach of the 
purse that I had so cruelly decided to steal- no, steal is such an 
unpleasant word.  Let us say, that I had so cruelly decided to keep for 
myself, when all of a sudden this delinquent comes along and grabs it right 
out from underneath my nose!  The irony of me judging him to be a delinquent 
when we both had the same purpose on our minds did not escape me, but I 
wasn't in the mood to philosophize.  I wanted that purse!</p>

<p>Without a further thought, I took off after the boy in the ski cap.  He 
didn't have a very large head start on me and was yet unaware that he 
had a pursuer.  I should confess that he was a decent runner and perhaps 
would have sped away from me if it weren't for the heavy clothing that he 
adorned himself in, but with clothes as baggy as his weighing him down, I 
made slight gains on him every few seconds, and when I was in reach I leapt 
out in a tackle that brought him crashing to the ground with a yelp of 
surprise.  He was quick-witted however, and before long had gathered himself enough to 
turn around and start fighting back.  I can only imagine what a 
sight the pair of us made; wrestling around in the dust for some feminine 
object that clearly didn't belong to either of us.  Not only that, but we 
were drawing a crowd and neither of us was likely to make it out of 
the park without being halted by some authoritarian.</p>

<p>I was getting ready to take a moment of my attention and energy away from 
the brigand that I was engaged with to spout some falsehood to the crowd 
about how it was my every intention to return the purse to its rightful 
owner as soon as I forced it from this other boy, this unruly thief.  I 
would have certainly succeeded and perhaps gained some benefit by it, but 
at that time my opponent landed a well aimed punch in my opening mouth, 
silencing me before I spoke.  In shock, I lay down in the dirt, gagging. 
The other boy could have at this time perhaps chosen to make his untimely 
departure and leave me to face the crowd, but I suppose I had angered him to 
some extent, for instead of making off with his ill-gotten gains, he chose 
to continue the struggle by kicking me square in the face.  I was trying to 
block his second kick when out of nowhere, two burly hands reached into the 
melee and yanked us both off each other, and our feet, by the collars of our 
shirts.</p>

<p>The owner of the hands appeared to be a police officer.  Holding us 
suspended in the air by our collars, how glowered at us from beneath bushy 
eyebrows.</p>

<p>\"Alright then, you two,\" he began,  \"what's this all about?\"  The other 
officer who must have been his partner appeared and retrieved the purse 
which had been left on the ground.  Taking a moment to scan its contents, he 
walked it backed over to their police car that had pulled up on the edge of 
the park, deposited it inside, locked the door, and returned to us.  I let 
my face droop in disappointment as the purse disappeared within the vehicle, 
and I could hear the other boy sighing over this as well.</p>

<p>\"Speak up!\"  hollered the burly cop.  And at once, the other boy and I 
began to blurt out a series of unconvincing, frenzied explanations.</p>

<p>\"I was trying to return the purse-\"</p>
<p>\"My mom forgot her purse and sent me-\"</p>
<p>\"I saw this punk trying to make off with it, so I-\"</p>
<p>\"As I was, uh, calmly walking it back to my mom, I was assaulted from 
behind-\"</p>
<p>\"So I started wrestling the purse away from him, to return it to its 
rightful owner mind you, and-\"</p>
<p>\"He was trying to steal my mom's purse, but I wouldn't let go-\"</p>
<p>\"Just as victory was within my grasp, you butted in-\"</p>
<p>\"I was about to beat off the thief when you grabbed us both-\"</p>
<p>\"You're not sending me to jail, are you?\"</p>
<p>\"You're not sending me to jail, are you?\"</p>
<p>The police officer could tell that we were both lying through our teeth.</p>
<p>He groaned, set us both down (at which point I noticed how much he towered 
over us), kneeled down, and spoke again in his deep, bass, voice.</p>
<p>\"Now look here, boys,\" he began.  \"Stealing is a major offense.  In fact, I 
could send you both packing to the slammer right now if I wanted.  But I 
won't.\"  He glared at us.  \"You see, I'm going to give you boys a chance to 
turn away from this newfound life of crime and become respectful, 
law-abiding citizens.\"  He narrowed his eyes.  \"Now I know that you won't 
make me regret my decision, will you boys?\"  It sounded more like an order 
than a question.  \"Boys?\"  He pressed when we had yet remained silent after 
a few seconds.</p>
<p>\"No, sir,\" we both mumbled.</p>
<p>\"Excellent!\"  The cop seemed satisfied.  He stood up and turned around to 
his partner.  \"Alright Frank.  Let's leave these two little angels to 
contemplate their futures and try to find out who this belongs to.\"</p>

<p>The cops drove off, and the crowd finally began to disperse.  We sullenly 
watched them walk away, watching them give us disapproving looks.  Before 
long, the boy in the black ski cap and I were the only ones left.  We sighed 
simultaneously, and began walking back through the park.  It was late and 
time to go home.</p>

<p>You'd think that the two of us would have parted ways at the first 
opportunity, but we remained together, a sense of camaraderie and 
understanding known only to two crooks among us.  As we walked, I turned to 
him.</p>

<p>\"Hey, sorry man,\" I apologized.  \"You totally stole the purse before I did. 
 I should've let you get away with it.\"</p>
<p>\"Nonsense,\" the boy replied, \"I admire someone who doesn't let their prey 
escape them.  I should've recognized that that's all you were doing and let 
you take it.\"</p>
<p>We both sighed again.  It seemed to me that the only question left to 
answer was whether we would become lawful citizens, like the cop told us to, 
or continue down the roads of vice we had begun on.</p>
<p>\"Hey, so what's your name anyway?\"  I queried.</p>
<p>\"Why, thank you for asking,\" the boy answered.  \"My name is Al Capone.
What's yours?\"</p>
<p>\"Jimmy Hoffa,\" I said.  \"Pleased to meet you.\"</p>

<p>--The End</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>