<?php

$aid = 'aarontang';
$title = 'Become a Leader in a National Youth Movement for Better Schools';
$cid = c7;
$issueid = i7;
$body = 
"
<p>What happens when over a million students stand up to demand that government address long-standing resource shortages, policy problems, and inequalities in public education?</p>

<p><a href=\"http://www.cnn.com/2006/WORLD/americas/06/13/chile.students.ap/\">In Chile</a>, the result was $200 million dollars to repair dilapidated schools, permanent youth representation in the form of twelve student seats on a national education reform panel, and other benefits like improved school lunch programs and free entrance exams to get into college.  Student leaders in Chile mobilized rapidly in response to growing concern about the lip-service being paid to youth issues, and the result—a million students walking out of their run-down schools for three weeks until the newly elected President agreed to take action as demanded by the students—was an unprecedented victory for young people & the future of Chile.</p>

<p>In the United States, the problems plaguing our education system are every bit as pressing: nearly 20,000 school buildings have facilities in \"inadequate\" condition; two-thirds of our students cannot read at grade level proficiency; more than a million students drop out of high school each year; and pernicious inequality persists along geographic, racial, and financial lines.  But until now, students have done precious little in response to these systemic failures and failures on the part of elected officials to improve things.</p>

<p>Thankfully, students in America - young people just like you - are beginning to take the future into their own hands.  Through <a href=\"http://www.oured.org\">Our Education</a>, a national student movement is starting to stand up to demand high quality public education be guaranteed as the right of every American child.  Because believe it or not, even though we live in one of the richest and most advanced countries in the world, children in this country do not actually possess an American right to an education... let alone the right to a high quality education.  The US Constitution doesn't mention the word \"education\" a single time, and the US Supreme Court ruled in 1973 that American children do not possess the fundamental right to an education.</p>

<p>Think this should change? You are not alone. Thousands of students have joined together to sign a petition demanding that all children be guaranteed the right to a high quality public education, a petition that is supported by a number of United States Congressmen.  You can learn more about the petition and sign it <a href=\"http://www.OurEd.org/pages/sign-the-petition\">here</a>.</p>

<p>But just like in Chile, if this student-led effort to improve our schools is to succeed and we are to win real improvements in our schools, students like YOU will have to become LEADERS and not just ordinary members of the movement.  We'll need students like you to spread the word about the petition and get it signed by your student body.  Then we'll need students like you to take the lead in debating and passing a first-ever \"Students Bill of Rights\" in 2007.  And we'll need students like you to continue to put pressure on our leaders to make our education a national priority.</p>

<p>Interested in being one of these student leaders?  E-mail <a href=\"mailto:info@oured.org\">info@oured.org</a> for more information on leading an Our Education petition drive at your school in the fall.  With just a few hours of your time, you can play a critical role in getting the word out about this campaign.  If you need service hours for graduation or anything else at your school, this would be a great way to get them!</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>