<?php

$aid = 'sharon';
$title = 'Raisins';
$cid = c3;
$issueid = i7;
$body = 
"
<p>I think that raisins<br/>
Are like old people grapes<br/>
Old people and raisins<br/>
Have shriveled-up shapes</p>

<p>Young grapes are like children<br/>
Plump, fresh and sweet<br/>
But then they dry up<br/>
FromÊ the sun's constant heat</p>

<p>Every raisin you see<br/>
And unthinkingly chew<br/>
Was once a grape<br/>
A child, just like you.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>