<?php

$aid = 'sharon';
$title = 'Nothing';
$cid = c3;
$issueid = i7;
$body = 
"
<p>I think I have nothing to say<br/>
My creativity has drained away<br/>
I recite a cheap rhyme<br/>
Just passing the time</p>

<p>Waiting for inspiration to come<br/>
Ho hum.</p>

<p>Twiddle my thumbs<br/>
Stare off into space<br/>
Notice that the last line<br/>
Didn't rhyme</p>

<p>What else can I write<br/>
Need to write something tonight<br/>
I wail and I groan...<br/>
Oh look, it's a poem.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>