<?php

$aid = 'shan';
$title = 'Relationship Advice for the Guys';
$cid = c4;
$issueid = i7;
$body = 
"
<p>We're all in high school now. Naturally, the only thing on most guys' minds is...no, not grades; girls. Whether guys work out or focus on buying good cars, the purpose eventually is to get girls. <b>Now of course</b>, all the girls are thinking, \"How sad...How come they can't think about anything else?\" Well, get used to it. This is how it's been for centuries, and it's not going to change for a while.</p>

<p>For you guys however, some advice on how to actually get the girl may be necessary. Some of you may think that you have it made for life: on your arm, a beautiful girl who's incredibly intelligent and very independent. Thanks to the Hollywood stereotype of women, that is exactly what every guy wants. I, however, am here to say: BULLSHIT!</p>

<p>Beautiful, smart, and independent? Are all of you crazy? Let me give you all a little insight into the requirements of a perfect women in the long term aspect: stupid, ugly, and incredibly rich. \"What!?\" you ask? But as crazy as it may sound, this will guarantee you happiness for the rest of your life.</p>

<p>Let me explain:</p>

<p>Since the dawn of time, guys have done certain things that, for some inexplicable reason, piss off girls. If you are with an intelligent girl, I guarantee that you will get away with absolutely <i>nothing</i>. Moreover, intelligent girls have a good memory, so you'll NEVER hear the end of it. With a stupid girl, however, you'll be able to get away with murder. She's more likely to believe whatever bogus and pathetic excuse that you come up with for doing the things you do.</p>

<p>All this leads me to point number two: ugliness. \"Why?\" you ask. \"Nobody wants to damage their eyes by staring at blatant imperfection for too long.\"  But if she's ugly, it's much more likely that the girl will be desperate and needy. This means that she'll probably do anything to make you happy. Yes, spending a day with someone with those looks may require a strong stomach (let's not mention night time...), but if you refer to the first point that I made, you'll remember that you can do anything to get rid of your unhappiness. <i>Anything</i>... (I'll let you use your imagination here) and you'll be able to get away with it.</p>

<p>Now these points are related, so it will not be complete until the third and final point is introduced: wealth. Now, what good does a stupid, ugly, needy wife or girlfriend, do? Why, buy your love! Most guys like luxury and expensive things. And the girl is desperate; after all, she knows she could lose you very easily. Therefore, she'll be willing to do (and spend) more to keep you with her. She loves you, you love money... everybody is happy!</p>

<p>These three qualities in a girl are the keys to a happy, luxurious life. You can all still have fun on your own time and at the same time be happy and content with your wife or girlfriend. There will always be some hypocritical moralist preaching and lecturing about how this way of life is wrong. Yet, as the constitution states, every man is free to pursue his own happiness, and this way of life yields happiness for both members of the \"relationship.\"  It may be a little hard for you to try at first, but once you get started, you'll feel happier than you have been in years...</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>