<?php

$aid = 'archana';
$title = 'Enchantress';
$cid = c3;
$issueid = i7;
$body = 
"
<p>The drums are beating,<br/>
senseless rhythms.<br/>
The snakes are swaying,<br/>
in time with my heart.<br/>
My feet are flying,<br/>
pounding the hard earth, beneath my feet.</p>

<p>Before me he stands, sword raised in hand<br/>
the look of an animal in his eyes.<br/>
Fierce. The fire rages within him.<br/>
Inconsumable. Burning.</p>

<p>The air stills for a moment,<br/>
then moves with every sway of my body,<br/>
moaning, yet crooning. Promising, yet dangerous.<br/>
Behind veils of deception and truth.</p>

<p>Slowly, I call to him.<br/>
With my eyes, I say his name.<br/>
The snakes are watching. The drums are beating.<br/>
He will be mine.</p>

<p>With the fire, I have become one.<br/>
Before his eyes.<br/>
Part god, part woman am I.<br/>
He looks into my eyes,<br/>
as the night calls to him, he falters.</p>

<p>He is mine. I have won my prize.</p>

<p>Fire surrounds him, licks at his feet.<br/>
No longer is he afraid.<br/>
For he is mine, and one in me.</p>

<p>Together we meld.<br/>
Together we are one.</p>

<p>The drums beat, faster. Harder.<br/>
The snakes won't rest tonight.<br/>
The air is dense, with the jasmine's scent.<br/>
Filling every crack, every crevice, every fissure.</p>

<p>Faster and faster beats my heart,<br/>
louder and louder my body sings.<br/>
Higher and higher the fire will rise.<br/>
For tonight is the night of the spirit.</p>

<p>I am who I am.<br/>
I am all-powerful.<br/>
Admirable is his will.<br/>
Unstoppable is my power<br/>
For I am who I am.<br/>
I am the enchantress.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>