<?php

$aid = 'anik';
$title = 'Iron Man';
$cid = c9;
$issueid = i7;
$body = 
"
<p><i>Gosh golly gee.</i> No alliteration truly expresses the joy summer can bring to a person. It seems that due to this euphoric joy in which I've been immersed, I have forgotten about this silly thing called <u>Amalgam</u>. However, recently this joy was cut short, when school was reinforced back into my life... in the form of Pre-AP Biology. Woe is me. But enough about me, let's talk about biology.</p>

<p>Ok, so, Biology is <i>kind of</i> interesting. There's the fun of drug discovery: \"This pill cures cancer! But the side effect is it makes your heart explode.\" And surgeries (and malpractice forms) are sort of cool. But there's a new field of biology that seems to be of increasing appeal. This field of biology is called bionics.</p>

<p>Now before you jump to <i>Robocop</i> or <i>Ahhnold</i>, understand that bionics is far more diverse a field than the designing of evil robots with strange accents that have actuating pistons in their hands rated to 600 psi, granting them the ability to crush a man's skull with one hand. Bionics is the application of biological systems to modern electronics and engineering.</p>

<p>Let's look at a historical example. Leonardo Da Vinci studied the flight of bats, and determined that since the anatomical structure of a bat's wings is similar to a human's arms, man should be able to fly. Therefore he designed a bionic machine: a crackpot contraption with giant bat wings that attach to your back and arms. He took his invention to a cliff to test his theory. But of course, being the genius he was, Da Vinci convinced one of his assistants to try it instead of testing it himself. His assistant agreed, and consequently died. Thanks to the stupidity of his assistance, Leonardo lived on to become the grandmaster of the Priory of Sion. (Dan Brown has the assistant to thank for the pretty profit he's recently made.)</p>

<p>Despite Da Vinci's failure, bionics did not go out of fashion. It has other uses besides flight, and it's mostly the other uses that excite scientists today. For those of you who remember the <a href=\" http://www.amalgammag.com/?id=34\">first article I wrote</a>, NASA is employing bionics in its project, BEES (NASA studied how bees navigate, and applied this to an AI for a spacecraft destined to explore Mars from the air).</p>

<p>Another example is the \"Black Widow,\" a tiny robotic insect developed by the CA based company, AeroVironment. The \"Black Widow\" can fly above an altitude of a hundred meters and take video surveillance of the ground. The U.S. Army has already purchased versions of this robot and has deployed them far behind enemy lines. NASA and AeroVironment's efforts are examples of using biology to inspire robotic design. There is another variation of bionics: studying the human body and then making a device that can help the disabled. This adaptation of bionics is more commonly known as prosthetics.</p>

<p>Prosthetics is a process of analyzing limbs and organs, making artificial ones, and then giving the fakes to people whose limbs and organs suck. When modern technology and electronics are implemented in prosthetics, the results can be amazing. A man named Jesse Sullivan accidentally grabbed a high voltage wire while repairing a power line. Oops, there went his arms. Now, in lieu of his arms, is a pair of six million dollar prosthetic arms that are controlled directly by signals from his brain. He can open and close a robotic hand, reposition his elbow, and even sense hot and cold.</p>

<p>Though more uncommon, there are cases where the entire arm isn't bunk, just the muscles that make it useful. What's the solution? Artificial muscles, made of composite plastics and fibers baked in chemical baths. When these plastics are applied to an electrical current, they expand or contract with an immense power to weight ratio. The advantage is it only takes electricity to flex a plastic bicep. Hmm... don't nerve cells supply an electrical impulse to muscles in the human body? Why yes, they do. This means we can give plastic muscles to a guy who had his arm caught in a meat grinder and he'll be <i>stronger</i> than he was before. This technology is still in development, so it has not been administered to a human yet. Regardless, the University of New Mexico has had a new visitor to the campus gym, a plastic skeleton named \"Myster Bony,\" who pedals an exercise cycle on his own.</p>

<p>There's a lot more going on besides cycling skeletons; so much more I don't have the patience to talk about everything, but for the sake of mentioning them, I'll spend a paragraph more (lucky you). Pacemakers! This thing has already been perfected - chances are one of them might be in your grandpappy's chest. But hey, if the whole heart is trash, we have to transplant it and have the patient take immunosuppressant drugs for the rest of his life. Well soon this may not be necessary, because artificial hearts have been made and tested. In the 1800's, a guy lived with a bronze heart inside him for a week or so. In 2001, the \"AbioCor\" artificial heart was given to a patient, who has not only survived, but whose life expectancy has doubled, and is due to return home.</p>

<p>There are also bionic solutions to less life threatening problems - can't see well? Surgically implant contact lenses, or someday even replace the lens your eye comes with. Can't hear well? Hearing aids a pain? Engineers are developing cochlear implants (some say the government is interested in hiding miniscule, radio transmitters in the cochlea of secret agents...).</p>

<p>In the end, there's a lot to be done, but bionics is indeed a promising study that will benefit the future of mankind (which is probably nuclear holocaust, where radiation will screw up babies, making them candidates for prosthetics when they grow older). Boy, we're in for a glorious future of cyborgs, exercising skeletons, and another topic for metal bands to rant about...</p>

<p><i>\"Heavy bolts of lead<br/>
Fills his victims full of dread<br/>
Running as fast as they can<br/>
Iron Man lives again!\"</i></p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>