<?php

$aid = 'raymond';
$title = 'Movie Review: Pirates of the Caribbean: Dead Man\'s Chest';
$cid = c12;
$issueid = i7;
$body = 
"
<p>Well, what do you want in this review? The movie grossed $132 million on its opening weekend, so chances are that you've seen it. But in case you haven't, here it goes.</p>

<p>The plot picks up right after the first movie. The story is pretty complicated, involving the quest for a key and a chest that has this creepy-looking guy's heart in it. But for a more detailed explanation of the plot, just watch the movie. I'm only going to sum up the stuff I liked and didn't like about it.</p>

<p><b>WARNING: SPOILERS</b></p>

<p><b>Liked:</b></p>
<p>1. The cannibal-island scene. I guess I've been influenced by Cannibal Holocaust a bit too much, but any normal person would think that scene is damn hilarious from the crewmates climbing the cliff inside their spherical stick cage to Jack Sparrow trying to blow out the flames beneath him as he is being cooked alive. Entertaining stuff (although the blowing-out-the-flames-while-being-cooked-alive was used in Return of the Jedi as well).</p>
<p>2. The special effects. Nothing short of amazing - Davy Jones looked great with all his tentacles, etc. His crew was pretty awesome too, as were the sea fights and sword fights.</p>
<p>3. Captain Sparrow. Hilarious, as expected.</p>

<p><b>Disliked:</b></p>
<p>1. Norrington. This might sound minor, but I hated how they made Norrington a bad guy. He was my favorite character in the first movie because of his honor and intense desire to do the right thing. In this one, however, they turned him into a greedy, whiny, and even sinister bad guy who spent most of his time complaining about how miserable his life is.</p>
<p>2. Bullet time. I swear to god they had a bullet time scene in here. I hate bullet time. I'd prefer to actually see someone/something get shot, not see the bullet fly slowly through the air. The only time when bullet time is acceptable is when the bullet actually hits someone in the process of flying through the air (<u>Bad Boys 2</u>). (And yes, I do hate <u>The Matrix</u> and its crappy sequels.)</p>
<p>3. Length. After about an hour an a half, the movie just seems to drag on and on and on and on. And on. And on and on and on. And on. The movie felt like it should've been about an hour shorter.</p>
<p>4. WARNING MAJOR SPOILERS<br/>
The Cliffhanger ending. It seemed way to much like The <u>Matrix Reloaded</u> (again, I must reiterate that the <u>Matrix</u> trilogy sucks). Usually, movies that drag are made tolerable by decent endings. However, with no such ending here, <u>Pirates</u> seemed a bit unfulfilling and disappointing.</p>

<p>SO DID YOU LIKE THIS MOVIE OR NOT?</p>
<p>Well, I must say that it was disappointing, to say the least. It started out with a bang (the cannibal island scene), but it sort of fell apart after that. Fans of the first one will probably like it to some degree, but this sequel is not nearly as well done as the first. However, it beats the hell out of most other summer \"blockbusters\" out there, like <u>Superman Returns</u>, <u>X-men 3</u> (*shudders*), <u>The Da Vinci Code</u>, etc.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>