<?php

$aid = 'raymond';
$title = 'Movie Review: Running Scared';
$cid = c12;
$issueid = i7;
$body = 
"
<p>HOLY CRAP!! A PAUL WALKER MOVIE THAT DOESN'T SUCK!!!!!</p>

<p>Ok, maybe I shouldn't be talking. In reality, I've only seen one Paul Walker movie, <u>Timeline</u> (which sucked by the way). Honestly, I've been avoiding this guy's movies for a long time due to the negative buzz surrounding his acting. However, I found out about this movie while surfing randomly on <i>imdb</i>, and I saw that it was rated R for pervasive strong brutal violence. So, naturally, I went out and saw it.</p>

<p>The movie starts out with Paul Walker's character, a lowlife gangster named Joey Gazelle, getting into a shootout with some corrupt cops during a drug deal. In order to cover up the killings, Joey's boss has him get rid of the gun involved in the murders to avoid implication. He returns to his house and hides the gun in his basement. Gazelle has a wife and a kid, and he seems to live happily at home. His kid's friend, named Oleg (played by Cameron Bright), however, leads a crap life. His dad is a John Wayne obsessed freak who frequently beats his wife and Oleg. Oleg then steals Gazelle's gun, shoots his dad, and then runs away. Gazelle, knowing that he's a dead man unless he finds that gun and gets rid of it, sets off on his quest to find it.</p>

<p>The movie, however, is more focused on Oleg's journey into the dark, grimy, ugly, brutal crime world than Gazelle's quest for the gun. This is NOT a mindless action movie. It's actually one of those rare, tightly scripted, character driven movies. It is pretty intense in spots, but that intensity comes more from the characters and the conflicts than the violence. The violence, while brutal, isn't really that pervasive. Sure, it's relatively frequent, but it's never gratuitous.</p>

<p>There are several things that distance <u>Running Scared</u> from other action movies. One is director Wayne Kramer's excessively pompous style. He uses a series of slow-mo shots, complex camera movements, and creative CGI sequences in many of the action scenes, and they just look cool. Another unforgettable aspect is a scene involving Oleg being taken to the home of a seemingly happy couple, only to later discover that they are pedophiles bent on raping and murdering him. That was a pretty intense scene. Third, Kramer puts more emphasis on the characters than the violence. He's a big fan of building up tension through dialogue and character development before something incredibly violent happens. It's similar to when the guy holding a gun shouts and threatens the victim for a couple of minutes before shooting them.</p>

<p>But the biggest difference between <u>Running Scared</u> and any other action movie is that it actually has a heart. Obviously though, an action movie that has a kid as the protagonist/major character is going to emphasize some kind of father/child relationship. But the movie manages to pull it off quite well, mostly due to Paul Walker's and Cameron Bright's acting. The other characters are also well acted, and the script actually takes time to develop most of the villains, making them more than one-dimensional.</p>

<p>Basically, if you are an action fan, violence fan, or movie fan in general, you will probably enjoy this movie. Squeamish people beware, however, because it is rather violent in parts.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>