<?php

$aid = 'raymond';
$title = 'Movie Review: A Scanner Darkly';
$cid = c12;
$issueid = i7;
$body = 
"
<p>This was an unusual movie. True, it's based off of a Philip K. Dick story, so of course it's going to be weird. But it's more than that - the movie itself was just...different. Imagine a junkie movie crossed with a cop drama crossed with a science fiction thriller...and then add some large doses of humor and you basically have this movie. It was also \"rotroscoped,\" which I haven't seen before (although it was used in director Richard Linklater's earlier film <u>Waking Life</u>).</p>

<p>Most of this was a junkie movie though, which I really wasn't expecting. I guess it makes sense; I think the movie was rotroscoped in order to disorient things as if you were on drugs. The plot is incoherent as well. It chronicles the life of several junkies in a futuristic world. Well, actually it's a bit more complicated than that.</p>

<p>Keanu Reeves is a cop working undercover as a drug dealer. Well, not quite undercover... cops of the future wear these suits that makes it impossible to tell who you are, so whenever Reeves is in the police station, he is unrecognizable, but when he is outside, he takes off his suit and assumes the life of a drug dealer. The film then chronicles how Reeves interacts with his fellow junkies, played by Robert Downey Jr. and Woody Harrelson. All they seem to do is talk crap, take drugs, make silencers out of tin foil, take drugs, and take some more drugs. Seriously. 80% of the movie is about this. The other 20% is a police investigation/sci-fi thriller plot twist. But the movie mostly focuses on how Reeves's live descends as he takes more and more drugs. And he only takes drugs with his junkie friends, so we get to see a whole lot of Robert Downey Jr. telling jokes and Woody Harrelson being stupid.</p>

<p>Why did I watch this movie? Well, I thought this was going to be another Philip K. Dick science fiction thriller like <u>Minority Report</u>, <u>Blade Runner</u>, <u>Paycheck</u>, <u>Imposter</u>, and <u>Total Recall</u>. Well, obviously it wasn't. Did I like it? I guess, but it certainly isn't a movie for everybody. My dad fell asleep in the theater next to me. It is a pretty slow movie and not a whole lot happens until the end, but despite this, I found the movie pretty interesting and, at times, hilarious. Robert Downey Jr. was awesome. He definitely deserves an Oscar nod. But overall, I wouldn't quite recommend this movie to very many people, except maybe Philip K. Dick buffs or people looking for something different.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>