<?php

$aid = 'ruchi';
$title = 'Seeing Red';
$cid = c4;
$issueid = i7;
$body = 
"
<p>I didn't think I was seeing red. I had never seen red before. Heck, I didn't understand why you were supposed to see <i>red</i>. Why not green or blue? Or better yet, black? Wasn't black the color of hatred? I mean, if you hate someone you send them a black rose, not a red one. Red is supposed to signify love, not hate.</p>
<p>But, either way, I didn't think I was seeing red. Sure, I was angry, furious, worked up, whatever you want to call it. My temperature had probably risen and I was ready to break, smash, ruin something. But I wasn't seeing red.</p>
<p>I remembered what the school counselor had told me: deep, calming breaths. In. Out. In. Out.</p>
<p>Oops. I think that was too much out - now I was seeing black.</p>
<p>I breathed back in before looking at the <i>thing</i> that made me so furious. Suddenly the black was gone and my vision cleared. I could see <i>it</i> and my anger returned, full force.</p>
<p>I glared at <i>it</i>. I still wasn't seeing red.</p>
<p>For a second, I closed my eyes, trying to block out the sight of <i>it</i>.  <i>It</i> that caused this rage to pour through my veins. <i>It</i> that had caused me to almost break down and cry. <i>It</i> which just ruined my life and future. I opened my eyes - looking at <i>it</i>, I still didn't see red. Instead, I saw the swirls of blue and black and white.</p>
<p>Funny. I thought white and blue were supposed to be calming colors. I didn't get how that worked either - I mean, blue is also supposed to be depressing. How is something that is depressing calming?</p>
<p>Suddenly, I wrapped my hands around <i>it</i>, bending and twisting it in a desire to get rid of it. <i>It</i> that had, in one fell swoop, ruined my life. I still didn't understand why I wasn't seeing red.</p>
<p>I was angry. I was furious. I was ready to murder. But I wasn't seeing red. Maybe I missed the memo: <i>You only see red on Tuesdays. On Wednesdays, you see black or blue.</i> Damn memos.</p>
<p><i>It</i> didn't rip. <i>It</i> didn't tear. <i>It</i> wasn't ruined at all, despite being subjected to my angry, and now achy, hands. Stupid <i>it</i>.</p>
<p>I slammed my fist onto the table-top in frustration. I then lifted my achy, and now sore and hurt, fist to my face.</p>
<p>Oh. I understood why people saw red - the blood streamed down my knuckles and fell onto <i>it.</i></p>
<p>That made more sense. You saw red - you saw blood. Wow, why hadn't anyone told me this? You don't see a red haze... you see red <i>blood</i>!</p>
<p>Now that this little matter was cleared up for me, I took another glance at <i>it</i> and allowed myself to smile in my own secret satisfaction. Now I felt the anger, the fury, and I saw red as was appropriate.</p>
<p>The smile slowly slid off my face as I kept staring at <i>it</i>. <i>It</i> had ruined my life. No college was going to accept me now. I was going to get rejected from everywhere I applied, mooch off my parents until they kicked me out, and become a hobo.</p>
<p>That damn A-.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>