<?php

$aid = 'editors';
$title = 'Editor\'s Note: Issue 7';
$cid = c19;
$issueid = i7;
$body = 
"
<p>And Issue 7 of Amalgam is <i>finally</i> released!</p>

<p>A few days ago I was surfing the internet in yet another attempt to put off studying mythology or biology. I <i>stumbled</i> (If you know what I mean, I'm proud of you! You're a dedicated Firefox user!) upon a Wikipedia site! Now, I know some people who are ardently dedicated to Wikipedia. They use it to look up answers in all their subjects, insist it's always right (much to my frustration), and I am willing to bet they pay homage to it. I am <i>not</i> one of those people... however, after reading <a href=\"http://en.wikipedia.org/wiki/List_of_unusual_deaths\">this</a>, I'm certainly a little more open to the idea of a Wikipedia cult - I never knew the site could be so amusing.</p>

<p>But that one page is among many other things I found interesting this month. While going through the articles, I learned the advantages and disadvantages of Windows Vista, the newest Microsoft OS that has been released in beta. As someone who can be technologically inept, I found this particularly useful... and the dry humor kept me entertained.</p>

<p>This month, the creative arts section of Amalgam - art, short stories, and poetry - is amazing. If you're in the mood to laugh, philosophize, or gaze in wonderment, you are going to be delighted with this issue. For example, A Destiny in the Making, a story about...well, you should read it for yourself, is one of the best short stories I have read in a long time...</p>

<p>Altogether, I think I'd just like to say, enjoy Issue 7!</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>