<?php

$aid = 'sharon';
$title = 'True Love';
$cid = c1;
$issueid = i8;
$body = 
'
<p>Do you believe in true love?</p>

<p>Do you sigh when you watch a romantic movie and wish that you could be struck with Cupid\'s dart? Or do you scoff at the idea of "true love," the phrase often uttered by people who want to get into each other\'s pants?</p>

<p>In my idle time (between sleeping, eating, and piano lessons) I wonder about things like this. I admit I\'m a bit of a skeptic. I sigh at the endings of movies and then mentally slap myself for being a softie. I wonder why the lady who writes in to Dear Abby claims to "love" the jerkface who slaps her around and cheats on her every other day. I wonder why a perfectly sensible sixteen-year-old boy would write "<3 you Amy, always and forever" in pink at the bottom of his AIM profile.</p>

<p>Perplexing, isn\'t it?</p>

<p>This summer, I\'ve watched several movies, old and new. The skeptical voice in my head has provided endless... er, entertainment, for lack of a more suitable word.</p>

<p>Pirates of the Caribbean: as I watch Elizabeth Swann and Will Turner declare their love for each other, I wonder if, a year later, they\'ll be able to stand the sight of each other. They\'re young, pretty, and hot-headed - what\'s to say they\'ll stay together?</p>

<p>Much Ado About Nothing: this movie based on Shakespeare\'s play proved rather confusing as well. Beatrice and Benedick, who start out hating each other, are tricked into believing that the other harbors unrequited love - and operating under this trickery, they proclaim their love and get married!</p>

<p>South Pacific, The Phantom of the Opera, Bend it Like Beckham: it\'s love, love, love. No movie gets by without a big dose of squishy lust. What is this love that everyone speaks of? Is love really that wonderful, for humans to wax eloquent for thousands of years about it? Or is it just an illusion, and is all this talk of love just wishful thinking?</p>

<p>I wondered what others thought. I turned to <a href="http://www.questionswap.com">QuestionSwap.com</a> - it\'s basically a site where you get to anonymously ask a question, answer another, and have the answer emailed to you. I asked one question again and again: "Do you believe in true love?"</p>

<p>Here are the answers I got. These answers are uncensored and unedited, given by people who I will probably never know.</p>

<p><b>Do you believe in true love?</b></p>

<p><i>Girls don\'t like nerds, so no.</i></p>

<p><b>Do you believe in true love?</b></p>

<p><i>Absolutely. Though i think it is alot rarer than songs and movies might have you think. I spent alot of my life watching relationships go down the tubes. I was 30 years old before I finally met someone who is perfect for me. He is my partner and equal in every way. It can happen, as long as you aren\'t foolish enough to settle for anything less than true love.</i></p>

<p><b>Do you believe in true love?</b></p>

<p><i>I havent experienced it yet but i\'ve seen so much of it around me i know it does exist.</i></p>

<p><b>Do you believe in true love?</b></p>

<p><i>I think I do, but it\'s very rare. I don\'t believe in love at first sight, though. Then again, everyone\'s going to get bored in a relationship at some point. I dunno.</i></p>

<p><b>Do you believe in true love?</b></p>

<p><i>I believe that we can love someone enough to do anything for them. I dont believe there is a specific "one" for all of us or "love at first sight". I believe that kind of love comes from trust, time and effort.</i></p>

<p><b>Do you believe in true love?</b></p>

<p><i>Yes I do, but not as some magical thing that keeps people together for ever and ever despite all odds. I believe that some people\'s personalities and attitudes fit well together, and that they are able to live together, mostly happily, for the rest of their lives. This however, takes a lot of work, just as munch as any non-true love. The difference being that a) the work pays of and the couple stay together and b) it\'s worth it.</i></p>

<p><b>Do you believe in true love?</b></p>

<p><i>I would have to say yes. To belive that you love someone that you would do absolutly anything I see as true. Everyone has to have someone there madly in love with. I mean just by numbers alone it seems very unlikly that there just isent someone for someone. I also belive that love/hate relationships are the best. Arguments keep relationships interesting and on your god damn toes! Do I belive in love at first sight? No. That said its also on how you belive your life. If you belive in spirituality then you may very wll think that you may feel a click just by looking at someone. I call it lust but eh.</i></p>

<p><b>Do you believe in true love?</b></p>

<p><i>I believe it is possible, but it doesn\'t come easy. Both parties have to work at it, otherwise you might as well spit in the ocean and see if it makes a difference.</i></p>

<p>So... do <i>you</i> believe in true love?</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>