<?php

$aid = 'rollingrabbit';
$title = 'Just For a Moment';
$cid = c3;
$issueid = i8;
$body = 
'
<p>Just for a moment<br/>

You need to lose focus<br/>

It\'s not about the concentration<br/>

It\'s all about losing your mind<br/>

When you\'re there it\'s a calming calamity<br/>

A surging stillness<br/>

And it\'s not about finding the right time to strike<br/>

Or nailing that spot glistening in the corner of your eye<br/>

It\'s about fighting a mental battle in your mind<br/>

In a few moments everything is blank<br/>

Only four things exist in your world now<br/>

Your body, your mind, and those of your opponent<br/>

The audience beside you is unapparent to your eye<br/>

Even while they sit a mere foot away<br/>

But the other man stands almost 3 feet from you<br/>

And the rush fills your body in an indescribable way<br/>

While your standing there thinking of what you have to do<br/>

A sharp pain fills your body and the adrenaline moves in you<br/>

So you lose hold of your entire life<br/>

Just for a moment<br/>

You\'re free from your life<br/>

Just for a moment you nail that kick<br/>

And his hands fly out to the side of you<br/>

Just for a moment, you feel no pride<br/>

Only the blankness of mind from after the fight<br/>

And after you\'ve finished your kick and the figure is down<br/>

You return to your mind and the moment is gone<br/>

And it\'s not until the end that the feelings come in<br/>

Or the satisfaction of winning<br/>

But the moment you jumped in to<br/>

Lost the grip on your mind<br/>

And there was no focus or doubt that kept holding you back<br/>

Just for a moment<br/>

You were alive</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>