<?php

$aid = 'sharon';
$title = 'Friend';
$cid = c3;
$issueid = i8;
$body = 
'
<p>Every day I write a letter<br/>

"Dear Friend" is how I start it<br/>

Friend puts up with my hate and rage<br/>

Friend knows my every secret</p>


<p>Friend won\'t make me feel ashamed<br/>

Of the horrible things I say<br/>

Or the desperate longings and wishes and hopes<br/>

That I tell Friend every day</p>


<p>My Friend is a patient one<br/>


Receptive and loving and kind<br/>

Friend knows what\'s really going on<br/>

In the dark recesses of my mind</p>

<p>Only Friend knows who I love<br/>

And who I wish to be<br/>

It\'s both a blessing and a curse<br/>

That Friend is a part of me.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>