<?php

$aid = 'raymond';
$title = 'Movie Review: Miami Vice';
$cid = c12;
$issueid = i8;
$body = 
'
<p>The marketing for this movie sucked, I must admit. The commercials would lead you to believe that this was some kind of remake of <i>Bad Boys 2</i>, or some kind of crossover between <i>Heat</i> and <i>Collateral</i>. It wasn\'t. This probably explains everybody\'s dislike of the movie; it sucks when you\'re expecting some mindless action-fest but get a thoughtful, realistic cop drama instead. This has happened before with the movie <i>Syriana</i>; the previews made it look like an action blockbuster when it was actually a talky political movie. However, bad marketing does not mean that Miami Vice is a bad movie.</p>

<p>Let\'s first take a look at what Miami Vice is NOT:</p>

<p>It is NOT an action movie. It has 2-3 action scenes (I\'m not even sure if you\'d consider the opening an action scene).</p>
<p>This is NOT a buddy cop movie. There is barely any emphasis on the relationship between Sonny Crockett (Colin Farrell) and Ricardo Tubbs (Jamie Foxx).</p>
<p>From what I\'ve heard, this is NOT an adaptation of the television series, although I cannot be certain because I have never watched it.</p>
<p>This does NOT have an easy-to-understand plot. The movie throws you into the lives of two undercover cops and you get the whole story from their point of view.</p>

<p>So, what IS Miami Vice?</p>
<p>Well, from what I understand, it is a well-shot, realistic depiction of undercover cop life.</p>

<p>This means a muddled plot, because police work is a very messy business. It also means lots of tedious talking because, unbelievably, that\'s what undercover cops do. There is also no happy ending because there is really no way for undercover police work to end happily. Not everybody is brought to justice because, in reality, punishing all drug dealers is an impossible feat. The characters stumble with words because, in real life, people are not perfect speakers. Many people complain about the two leads having no chemistry, which I guess is because most cop partners don\'t have chemistry. There are few action scenes because most cops are rarely engaged in shootouts, chases, fights, etc.</p>

<p>Michael Mann obviously attempted to make a realistic cop movie, and he did an incredibly good job. Unfortunately, many people failed to understand this, hence the negative reviews. Shame, because this easily the best movie I have seen this summer.</p>

<p>Even if you don\'t like the plot, you can still appreciate Michael Mann\'s cinematography. High Def looks pretty cool on the big screen. Nothing like 35mm, but it provides the right mood for this film. It\'ll look awesome on DVD.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>