<?php

$aid = 'aneesh';
$title = 'An Introduction to Diving';
$cid = c15;
$issueid = i8;
$body = 
'
<p>You\'re fifteen feet below the water\'s surface, and sinking fast.  You can see long distances in the crystal clear water - which means nothing up ahead, to the left, to the right, behind you... and just the surface, moving away quickly, up above, and the boat you entered the water from.  But none of that matters; you\'re only looking in one direction.  Straight down, looking at the wreck below you.  Above you, a few more divers enter the water, but the only other diver you\'re really focusing on is your buddy as you go down together - after making the descent, you\'ll stick together for safety, so its a good idea to keep track of each other. You reach the wreck quickly - it doesn\'t take long, although you are careful not to drop too fast, and make sure to equalize often.</p>

<p>As you reach the wreck, the top of it about sixty feet below the surface, the bottom still another twenty or so feet below you, you can see fish everywhere. It is an incredible experience; completely peaceful, all sounds muted, the entire world moving slowly. As you establish neutral bouyancy and just float effortlessly, you\'re completely calm - despite being under sixty feet of water. Your partner guestures to a fish swimming past, and you begin another exciting dive.</p>

<p>That dive, by the way, was the wreck of the The Major General Roberts, a small ship off of the US Virgin Islands - an actual dive I\'ve been on.  My buddy was my dad, and both of us came out of the water excited and thrilled that we had gotten to do a deep dive (defined for recreational divers as between 60 and 100 feet, sometimes extended to 130) and a wreck dive at the same time.</p>

<p>SCUBA (Self-Contained Underwater Breathing Apparatus) diving is one of the most incredible activities that someone can do. The feeling of weightlessness, the relaxed, slow, calm environment, and the beautiful world around you are all unmatched anywhere. That\'s not just me talking - after all, my life experience is decidedly lacking - that\'s the response of pretty much any divers I\'ve spoken to.  Even my dad - who once told me his favorite part of the dive was getting out at the end, because he\'s so utterly exhausted after long coldwater dives - will admit that it is a great experience, and while he can\'t cope with the cold water diving any more, he absolutely loves diving in the tropics.</p>

<p>Sure, you can always go snorkeling.  And not actually be able to see the fish hiding among the rocks, see through the kelp, witness anything up close, see anything clearly beyond a rather short range, or experience nearly the same Zen-like peace that you can get floating thirty feet below the surface. Not to mention, believe it or not, you\'ll actually be breathing <i>less</i> comfortably. Once I got used to them, I found my regs (that\'s the regulators, or \'mouthpeice\' for the rest of you) to be a vast improvement over my snorkel.</p>

<p><b>Isn\'t it dangerous, though? I mean, just look at all those scenes in the movies, and all the crazy stuff they do! There\'s even that movie that\'ll come out in a while about those NAVY Rescue Divers, that looks terrifying!</b></p>

<p>Well, sure, NAVY divers have an incredibly dangerous job.  For the rest of us recreational divers, though, the aspect of danger is quite low.  Statistically, the rate of injuries per person per dive in scuba diving is about equal to the rate of injuries per person per game of bowling.  Yeah, bowling. You\'re about as likely to screw up and get hurt diving as you are to drop the ball on your foot, or some equally inane method of harming yourself. And of those injuries, the vast majority of them come not from fauly equipment or natural dangers, but the diver doing something idiotic - <i>hey, look, I bet I can use my enriched air tanks and follow that turtle twenty feet below the contingency limits!</i> Follow the rules and safety guidelines and the risk is almost non-existant.</p>

<p>As a subset of that question, what if you run into a shark, a dangerous eel, or something else equally threatening? Well, if you\'re careful you won\'t get too close to them, and dive sites are usually safe - dangerous sea life is rarely a risk. Some sites specifically advertise sharks or stingrays or the like, and going to those sites, follow whatever precautions you\'re told to there and you\'ll be ok. Should you just happen to run into something dangerous, don\'t bother it and get safely away. Alert the other divers, leave the water, and follow the instructions that you\'ll learn in your courses (most of what you cover is about safety, so its way too much to explain here, but this was definitely anticipated by PADI in the courses they designed).</p>

<p><b>Isn\'t it scary? I mean, if something does go wrong, and you\'re so far below the surface...</b></p>

<p>Well, there is still a certain element of risk. In the event that there is an emergency, you\'re not in the best place to deal with it. Still, there are procedures for any risk that\'s worth noting, and most of the ones that aren\'t, and as long as you\'re diving with a buddy, things will work out fine. In general - especially in warm water, but in pretty much all dives - it gets so peaceful that it isn\'t hard to stay completely calm, especially as soon as you get the hang of controlling your bouyancy - you can just float in place, completely relaxed, and take the sights in.</p>

<p>I admit, I did have a panic attack once - twenty feet below, during my open-water certification, I was doing mask removal and retrieval and I accidentally used my nose to breathe in - which meant water coming up in my nose. I freaked out, and spit out my regulator (the mouthpeice, remember?), but my instructor quickly got it back into my mouth, then grabbed my mask and helped me put it on.  A little while of staying still, breathing and calming down, and I was fine for the rest of the dive and another dive later that day.</p>

<p>I\'ve done four cold water and six warm water dives since, plus a pool dive to try out my new drysuit, four of those shore dives and six of them boat dives - and haven\'t had a single problem since then. I\'m too distracted by the world around me to have time to be afraid - I\'m either looking around and enjoying myself or I\'m checking my pressure guage to see how much air I have left and my dive computer to see how deep I am and how much longer I have.</p>

<p><b>What do you do underwater?</b></p>

<p>Well, you swim around, look at the fish, coral, and whatever other features are present underwater and relax. Depending on what sort of dives you prefer and what specialties you train in along the way, you might speed around underwater with a DPV (Diver Propulsion Vehicle), explore underwater caves and tunnels, navigate through wrecks, or just see sights that not many people ever will - and there\'s a lot more that I haven\'t talked about. With a waterproofed camera, you can take pictures, too. Plus, there\'s the bragging rights - not many people can say they\'ve been eighty-feet below the surface, have seen a wolf eel up close in the water or have watched their instructer poke a (non-dangerous, of course) shark to make it swim away.</p>

<p><b>How do you get into the water?</b></p>

<p>Shore diving is the most basic method - get on your gear (except for the fins, which you\'re carrying) and get into the water. Inflate your BCD (the vest you wear that you control your bouyancy with) so you float, put on your fins, swim/snorkel out to wherever you\'re diving, then switch to your regulators and go down. That\'s a bit oversimplified, but that\'s the gist of it.</p>

<p>Then there\'s boat diving - go out in a boat with all your gear, put it on at the dive site, jump in, dive.  That one is <i>really</i> oversimplified - there\'s an entire speciality devoted to boat diving, but that sums it up decently enough, especially if you\'re going to dive on vacation, where the staff of whoever is running the dives and boats will handle pretty much everything.</p>

<p>All in all, scuba diving is an incredible experience that I would suggest that everyone give a shot. A local dive shop - <a href="http://www.diverdans.com/">Diver Dan\'s</a> - offers a <a href="http://www.diverdans.com/classes/discoverscuba.aspx">free introductory course</a> every Friday evening, and if you like it, you can go ahead and sign up for your open water certification course. If you get lucky and get Ron Angell as your instructor, tell him I said "Hi" - I\'m getting my Advanced Certification with him, and he\'s a top rate instructor and a great guy.  And no, I\'m not getting any referral discounts or free stuff off of this - my recommendations are my honest opinion. If you guys have any more specific questions, ask away in the comments and I\'ll try to answer as best as I can.</p>

<p>Links of interest:</p>

<p><a href="http://www.diverdans.com/">Diver Dan\'s</a></p>
<p><a href="http://www.diverdans.com/myths.aspx">Common misconceptions about diving</a></p>
<p><a href="http://www.diverdans.com/classes/faq.aspx">Frequently Asked Questions</a></p>
<p><a href="http://www.diverdans.com/classes/discoverscuba.aspx">The free introductory course</a>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>