<?php

$aid = 'sharon';
$title = 'Mister Silverstein';
$cid = c3;
$issueid = i8;
$body = 
'
<p>Mister Silverstein, you\'re a hero of mine<br/>

I\'ve grown up with your rhymes<br/>

I\'ve read and recited and been wholly delighted<br/>

With your words so many countless times<br/>

Thanks to you I\'ve fallen up<br/>

And encountered Runny Babbit<br/>

Because of you I\'ve decided to keep<br/>

A light on in the attic<br/>

Mister Silverstein, I think you\'d find<br/>

That we would have been best of friends<br/>

So just you wait, we\'ll meet someday<br/>

Where the sidewalk ends.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>