<?php

$aid = 'sharon';
$title = 'Funny Links and Quotes';
$cid = c4;
$issueid = i2;
$body = 
'
<a href="http://www.netjeff.com/humor/item.cgi?file=resrchph.rse">http://www.netjeff.com/humor/item.cgi?file=resrchph.rse</a><br/>
--kinda funny<br/><br/>
<a href="http://www.netjeff.com/humor/item.cgi?file=8thGradeHistory">http://www.netjeff.com/humor/item.cgi?file=8thGradeHistory</a><br/>
--it\'s been passed around, but it still leaves me rofl<br/><br/>
<a href="http://www.netjeff.com/humor/item.cgi?file=telemarketers.txt">http://www.netjeff.com/humor/item.cgi?file=telemarketers.txt</a><br/><br/>
<a href="http://www.topfive.com/arcs/t5032603.shtml">http://www.topfive.com/arcs/t5032603.shtml</a><br/><br/>
<a href="http://www.freemaninstitute.com/woman.htm">http://www.freemaninstitute.com/woman.htm</a><br/><br/>
<a href="http://www.justsurfing.com/a/100reasons/">http://www.justsurfing.com/a/100reasons/</a><br/><br/>
<a href="http://www.topfive.com/arcs/t5050302.shtml">http://www.topfive.com/arcs/t5050302.shtml</a><br/><br/>
and here are some quotes:<br/><br/>
There two kinds of people in the world. Those who divide people into two
groups and those who don\'t.<br/><br/>
60% of statistics are made up.<br/><br/>
10 out of 9 people have trouble with fractions.<br/><br/>

"I always wanted to be somebody, but I should have been more
specific."<br/>
-- Lily Tomlin<br/><br/>

If God has intended man to smoke, he would have set him on fire.
"Forgive your enemies, but never forget their names."<br/>
-- John F. Kennedy<br/><br/>

"If Lincoln were alive today, he\'d roll over in his grave."<br/>
-- President Gerald Ford<br/><br/>
Follow your dream! Unless it\'s the one where you\'re at work in your
underwear during a fire drill.<br/><br/>

"Any fool can learn from experience--it takes a wise person to learn from others."<br/>
-- unknown<br/><br/>

After eating an entire bull, a mountain lion felt so good he started
roaring. He kept it up until a hunter came along and shot him. The moral:
When you\'re full of bull, keep your mouth shut.<br/>
-- Texas Bix Bender
'
;

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>