<?php

$aid = 'editors';
$title = 'Editor\'s Note: Issue 8';
$cid = c19;
$issueid = i8;
$body = 
'
<p>ATTENTION! ATTENTION! Read all about it! Issue 8 of Amalgam released!</p>
<p>So many of you have observed that this issue is kinda sorta late. Yes, I\'ve noticed too. In my defense, the end of summer is a hectic time and we slipped. BUT, another part of the problem is the extremely low submission count! In fact, I delayed the submission due date by 2 weeks in order to get more in and am still lacking.</p>
<p>So, in an attempt to provide some motivation for the next issue, here is a pleasant note from Sharon:</p>
<blockquote>
<p>Hi guys!</p>
<p>This is Sharon and I have a warning for all of you. I took a look at the submissions we have lined up for this issue, and boy, are we LOW. I thought Ruchi might have been exaggerating when she said we had practically nothing, but I looked, and she\'s RIGHT. :O</p>
<p>Since I\'m not going to write a dozen more poems or essays just to fill up the space, I\'m going to ask you guys to submit stuff. NOW. Mail in your drabbles, your stories, your funny little articles, because we really need them. Don\'t whine that you don\'t have enough time because you\'ve been given a lot of time, okay?</p>
<p>Otherwise I\'m going to track down as many of you as possible and see if it really is possible to cleanly murder a person with a Post-it Note and a spool of thread. However, I would rather not spend my illustrious high school career in juvenile hall--in fact, I\'d prefer to edit the wonderful submissions that you must be scrambling to submit right now!</p>
<p>Much love,<br/>
Sharon</p>
</blockquote>
<p>With that in mind, let\'s move on to more pleasant thoughts.</p>
<p>This issue, I\'d definitely recommend reading Sharon Su\'s "Mister Silverstein". In the past few issues, I\'ve noted that all the reviews tend to liken her to him, so I\'m sure all of you will enjoy the poem. Also, Tiffany Liou\'s artwork is quite stunning - check it out!</p>
<p>Speaking of artwork - once again, I was stumbling across the internet one morning and I came across <a href="http://www.art-e-zine.co.uk/karyn.html"> this </a>.  At first, I didn\'t get it, but after a few seconds of letting my eyes adjust, I found it quite amazing. In case you are wondering, they are all <i>separate</i> images, not one large one.</p>
<p>Creative, eh?</p>
<p>Well, on that note, move on to the issue! I hope you all enjoy!</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>