<?php

$aid = 'perceseptive';
$title = 'Summer\'s End';
$cid = c15;
$issueid = i8;
$body = 
'
<p>Well, the end of the summer has not only approached the majority of us, it\'s passed us by. Suddenly, I\'m starting to see a lot of away messages that read: <i>\'HW. I hate my teachers. Help,\'</i> or <i>\'working,\'</i> or <i>\'procrastinating.\'</i> Last year\'s seniors went to college, this year\'s got their senior photos, and <i>bam!</i>, we\'re heaving our heavy backpacks and heading towards that dreaded torture chamber.</p>
<p>However, this isn\'t meant to depress you. While I\'m sure no one wants to go and sit through hours of classes (if you do, please feel free to contradict me), some, if not all, of you are more than excited to be seeing your friends again.</p>
<p>Why?</p>
<p><i>I didn\'t see them over summer. I want to see how people changed. It\'s a new year, a fresh new start.</i></p>
<p>Not to be rude or anything, but why didn\'t you see them over summer? I mean, isn\'t summer supposed to be the time when you actually <i>do</i> hang out with your friends? Were you avoiding them? If that\'s the case, they probably aren\'t your friends.</p>
<p>And how people changed? Excuse me if I\'m wrong, but you haven\'t seen them in three months. Except the usual loss or gain of weight or a haircut, a person probably doesn\'t change that much. And if the person\'s a friend, even if they aren\'t, you\'ve probably seen pictures of them.</p>
<p>A fresh start? As far as I knew, first impressions carry a long, <i>long</i> time. If you\'re looking for a fresh start, I suggest you transfer to a new school. Believe me, it\'s not going to be that new of a start if you come back to the <i>same school</i> with the <i>same people</i>.</p>
<p>I\'m sure some of you did miss your friends. Your summers were jam-packed with a job, athletics, \'family time,\' summer reading, and homework (evil, evil teachers). You didn\'t get time to get out of the house much, or you were out to the point that even on your days off you were so fried that you were dead to the earth.</p>
<p>I still <i>don\'t</i> understand why the vast majority of you are excited about school though. And I\'m starting to suspect that it may be something I never will.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>