<?php

$aid = 'ruchi';
$title = 'A Spoonful of Sugar';
$cid = c15;
$issueid = i8;
$body = 
'
<p>A little bit of kindness goes a really, <i>really</i> long way.</p>
<p>I know it seems weird to say something so idiotically obvious. Give me a break, when we were little kids, Mary Poppins said, \'A spoonful of sugar helps the medicine go down.\' And even in the real world, a bit of kindness here and there can stop and nullify a lot of bitterness.</p>
<p> As usual, there\'s a little story prompting exactly what brought this thought to mind.</p>
<p> I don\'t know why this always manages to touch me and stick with me so much, but maybe it\'s just a sentimental thing. In eighth grade, I had just had a relatively miserable summer vacation. My older brother was leaving for college and to me, that felt like the world was coming to an end. Also, I think I was in an emo-dramatic stage of my life. Either way, I didn\'t want to come back to school at all. I didn\'t want to walk the halls and know that my brother wasn\'t going to be somewhere there.</p>
<p> Slightly sulky, I stepped on the campus beginning ninth grade. I was prepared to be a moody child throughout the whole of my high school career when suddenly, one of my friends came running at me out of no where.</p>
<p>\'Oh my gosh! I didn\'t get to see you all summer! How was vacation? <i>I missed you so much! I\'m really happy to see you.\'</i></p>
<p>Those few, simple words immediately made me feel better; honestly, I think that\'s what made me view the school year with a positive attitude rather than a negative one. I don\'t know why they had such a profound effect; I definitely wasn\'t and am not an attention  and love-starved child. But that was my spoonful of sugar at the end of a \'bitter\' summer.</p>
<p>Suddenly, my brother\'s absence at the house didn\'t seem so bad. Whatever had caused me to be so dramatic and sulky over summer disappeared and life didn\'t seem quite as gloomy as it had seconds earlier.</p>
<p>What I love about that moment, most of all, is that she was completely genuine. She simply spoke her mind, and a year later, when I mentioned it to her, she didn\'t remember having said it at all. It was just something she had felt and expressed.</p>
<p>So, what\'s <i>your</i> spoonful of sugar?</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>