<?php

$aid = 'raymond';
$title = 'Movie Review: The Black Dahlia';
$cid = c12;
$issueid = i9;
$body = 
'
<p><i>Whoa, you actually watched this?</i><br/>
Yeah, unfortunately.</p>

<p><i>What\'s it about?</i><br/>
I have no idea. It\'s extremely convoluted. I spent most of the time waiting for it to end/for something violent to happen.</p>

<p><i>Well...can you give us a basic summary?</i><br/>
Well, apparently it\'s supposed to be about the investigation of this woman\'s murder, but I\'m not too sure. She doesn\'t even get killed until about halfway through, so don\'t know what the prime focus is. Let me think....eh, it\'s a <b>mess</b>.</p>

<p><i>Was the acting good?</i><br/>
Oh, HELL NO. Josh Hartnett gives an awful performance as some cop (I think his name is Bucky) who investigates this murder with his partner. Actually, he investigates the murder during the last 15 minutes; the rest of the time he sits around as his partner investigates the murder. Wait, actually during the first half hour, he boxes his partner. Wait, I DON\'T KNOW. The other people sucked too. Scarlett Johanssen (HOTTIE) sucked. Hilary Swank sucked, Aaron Eckhart sucked. Yea, they all sucked.</p>

<p><i>So, how does this compare with other movies this year?</i><br/>
Well, it\'s better than X3.</p>

<p><i>And?</i><br/>
Uh...it\'s worse than The Da Vinci Code.</p>

<p><i>HOLY SHIT!</i><br/>
Yeah.</p>

<p><i>So, what do you recommend?</i><br/>
Skip it.</p>

<p><i>What if you\'re a Josh Hartnett fan?</i><br/>
Well, he does get naked for the teenage girls...but no, skip it.</p>

<p><i>Anything violent happen?</i><br/>
Ooooo. This one guy is falling off this balcony and lands on his head. On a spike. Yeah, his head lands on a spike, and it EXPLODES. Sweet scene. Other than that, the movie was pretty boring. This one woman shoots herself in the mouth though...</p>

<p><i>How many people died?</i><br/>
I didn\'t count.</p>

<p><i>Why not?</i><br/>
Because I was too bored.</p>

<p><i>So all in all?</i><br/>
Well, it\'s rare to see a movie of such ineptitude. Brian De Palma is supposed to be this super-good director and stuff, but I don\'t really like the few movies of his that I\'ve seen. <i>Scarface</i> was ok and <i>Mission Impossible</i> wasn\'t very good. He obviously is trying to make the movie a throwback to film noirs of the 40s and 50s, but he fails miserably. So yea, it sucks.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>