<?php

$aid = 'andreak';
$title = 'The Halloween Party';
$cid = c22;
$issueid = i9;
$body = 
'
<p>Bowls of chips? Check. Music ready? Check. Halloween costume? Check. October 31, 7:30 p.m., the perfect night for a Halloween party thought Emily as her eyes swept the room. The perfect night for some good old-fashioned fun. All that was left was to wait for the un-expecting guests who were in for quite the surprise.</p>
<p>As the clock chimed 8, the guests began to arrive one by one. "BRIIIIIIIING" went the doorbell and in walked a gorilla, a Cinderella, and a chef among others. Soon the party was in full swing as everyone began to loosen up. Emily surveyed the scene. The gorilla, she noticed, was dancing merrily with his friends. "I hope he\'s enjoying himself because he won\'t be around for much longer" Emily thought to herself. Jack and his competitive nature had beaten Emily far too many times. No matter he participated in, whether it be a race or a game of Monopoly, his constant yearn to win would always take advantage of him, constantly leaving Emily in his dust. She had grown tired of the humiliation and decided to take matters into her own hands. </p>
<p>"May I please have everyone\'s attention?" shouted Emily as she clinked her champagne glass. "I have a very important announcement! As you all know, this is a Halloween party and we are all in costume, so it is only befitting to have a costume contest! All contestants must line up at the front of the room to be judged. The winner will receive a BIG surprise. May the best costume win!"</p>
<p>As soon as the words left her mouth, Jack rushed to claim the prime spot in front of the judges, just as Emily had expected. Slowly, the rest of the contestants began to line up. "Jack has some competition" perused Emily as she scanned the front of the room, her eyes passing over a doctor and a cheerleader among others, "but I\'m sure he\'ll find a way to win as always." The setup of the competition was explained to the contestants. First, each would walk around the room to show off their costumes and then they would each do an impersonation of the persona they had chosen to dress up as. Emily\'s thoughts were confirmed as she witnessed Jack tripping the doctor during his walk and making rude remarks during the cheerleader\'s performance, causing her to fumble with her words as her nerves got the best of her. Now that he had ensured low marks for his top competition, Jack was within reach of 1st prize.</p>
<p>"May I have everyone\'s attention please?" announced Emily for the second time that evening. "The Judges have come to a decision! The winner of the competition by a landslide is Jack dressed as a gorilla! Would Jack please come see me to receive his prize!"</p>
<p>"Here I am!" exclaimed Jack. "Now where\'s my prize?"</p>
<p>"It is waiting for you upstairs Jack. But you can get it at the end of the party. Go enjoy the party for now"</p>
<p>After this encounter, Emily began to mingle with the other guests, consoling the angered doctor and cheerleader who had unrightfully lost the competition.  She realized that they harbored the same hatred for Jack and his competitive nature that she had for all these years and could identify with them.</p>
<p>"We need to stand up to Jack!" exclaimed the cheerleader through her tears.
"Why does he take everything so seriously? It was only a costume competition! Is it so hard to let others win once in a while?"</p>
<p>"Don\'t worry," said Emily in a soothing voice, "we\'ll think of something."</p>
<p>As the party began to wind down and guests slowly began to leave, Jack approached Emily."</p>
<p>"Is it time for my prize yet?" he asked Emily.</p>
<p>"Not quite. We have to wait for ALL the other guests to go home so that they do not get jealous when they see the fabulous prize you have won."</p>
<p>"Whatever you say!" said Jack with a broad smile forming on his face as he began to imagine what such a great prize could possibly be.</p>
<p>When the final person left, Emily found Jack and told him to follow her upstairs where the prize was. Jack\'s anticipation grew with each step they took up the darkened stairs lit only by a dim hallway light in the distance. They finally came to a stop in front of a closed door. Emily turned to Jack and said,</p>
<p>"Jack, I am so happy that you won this prize. I feel that you are the only one of all the contestants to truly deserve it. Are you ready?"</p>
<p>"Yes!" shouted the over-eager Jack. "Open the door! Open the door!"</p>
<p>Emily slowly turned the knob and pushed open the door, revealing a pitch black room.</p>
<p>"Why don\'t you turn on the lights Jack?"</p>
<p>Jack immediately ran into the room to look for the light switch. As soon as he flicked the switch, Jack realized he was surrounded by people in their Halloween costumes.</p>
<p>"Surprise!" shouted the cheerleader as the rest of the costumed people began to beat Jack with their bare hands until blood soaked through his fur.</p>
<p>"Happy Halloween Jack" said Emily to the limp gorilla body on the floor.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>