<?php

$aid = 'shan';
$title = 'Nervousness';
$cid = c15;
$issueid = i9;
$body = 
'
<p>"Hey, you weren\'t at the dance on Saturday. Where were you?" A thousand different thoughts ran through my mind as I heard these words. What does she mean? Did she <i>want</i> me at the dance? Was she disappointed? Or is she just making a casual observation? Why the <i>hell</i> can\'t I think of anything mildly intelligent to say?</p>
<p>As most of my friends are grudgingly aware, I pride myself in having a quick retort or reply for most statements that come my way. However, lately I\'ve found myself tongue-tied more often than not, and, infuriating as it is, I am at a loss for what to do. Nervousness remains one of the biggest obstacles in many peoples\' lives.</p>
<p>I noticed that this phenomenon does not occur in a selective age group, gender, race, or anything of that sort. Rather, it occurs randomly in a person\'s life, often at the worst possible time, when even the slightest mistake or awkward hesitation can ruin your chances. Absolute confidence is a rare characteristic sought after by many. Practicing a speech for hours can help you with the material, but confidence is key to bringing across your point. There are different things that different people are confident doing: talking, playing music, dancing, dancing <i>with</i> someone, etc. However, the \'right stimulus\' can cause you to forget any and all knowledge you have of that particular subject.</p>
<p>So you probably think I\'m writing this article because I\'ve miraculously discovered a way to overcome nervous feelings and triumph in whatever nerve-wracking issue that\'s worrying me at the time, but I have not. Why then am I writing about this? Simply because I have finished my homework for the day, and have nothing else to do.</p>
<p>Actually, in my experience, the best solution for overcoming your fears is to just go ahead anyways. Freezing up, most often provokes worse results than blurting out the first thing that comes to mind.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>