<?php

$aid = 'ravi';
$title = 'Parents';
$cid = c3;
$issueid = i9;
$body = 
'
<p>As if <i>we</i> didn\'t know what we had to do<br/>
As if <i>we</i> tried to fail that test<br/>
They think that they understand <i>us</i><br/>
They think that they\'ve gone through <i>our</i> problems</p>

<p>Would you care to cut us some <i>slack</i>?<br/>
You know, give us the <i>relaxation</i> period we need<br/>
The one you always need away from <i>us</i> when we start making sense<br/>
Because we\'re only <i>human</i> too</p>

<p>Who are <i>you</i> to say that you know what we\'re going through<br/>
What do <i>you</i> know about how the pressure feels<br/>
How are <i>you</i> expected to understand what\'s going on in our heads<br/>
WHY DO <i>YOU</i> INSIST ON PRESSURING ME WHEN I\'M ALREADY BEING PRESSURED</p>

<p>And then the slap goes off<br/>
And I apologize for speaking back</p>

<p>Do you?</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>