<?php

$aid = 'paulal';
$title = 'Isidora';
$cid = c22;
$issueid = i9;
$body = 
'
<p>It was a night so dark and dreary,<br/>
My mind would not let me sleep, though my body was weak and weary.<br/>
Restless, I arose and crossed the room,<br/>
The reverberation of my footsteps echoed throughout the silent loom.<br/>
&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;I spoke to her but she would not move.</p>
<p>She stood behind a glass wall in the rigid posture I had seen so often,<br/>
I pleaded with her to hearken but her features would not soften.<br/>
"Isidora, Isidora," I prayed, "I apologize on my knees,<br/>
It was <i>mea culpa</i>, please accept my apology." <br/>
&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;I prayed to her but she would not move.</p>
<p>She remained behind the glass piece, so that I could not touch or hold her,<br/>
With my knuckles I tapped then rapped the barrier,<br/>
I grew more desperate and beat the glass only to make her stir,<br/>
The shatters flew and were carried by the howling wind, but she would not answer.<br/>
&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;I threatened her but she would not move.</p>
<p>Some nights ago, in her chamber, we had had a violent feud, <br/>
I screamed and shouted and responded with actions so insolent and lewd,<br/>
Then she had thrown an ornately carved wooden chair at the point where I had stood,<br/>
So I slammed the door shut, leaving the damned shut behind the piece of wood, <br/>
&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;I had left her but she would not move.</p>
<p>It took the bitterly cold night air to cause me to come to my sense,<br/>
I had heard His voice, a cold shiver that snapped my bones to become rigid and tense,<br/>
"You fool! You fool! You\'ve betrayed Isidora, left her exposed on her own,<br/>
Now I must chasten you for robbing her from <i>my own</i> home."<br/>
&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;He had threatened me but I could not move.</p>
<p>The wind had whined and shrieked around me as it picked up velocity,<br/>
Trying to force me back to the home, back to Isidora, with its ferocity,<br/>
But I could only sit in my cold sweat and speculate what he would do to her.<br/>
My memories were swept and whirled by the wind until it all became a blur.<br/>
&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;The wind had warned me but I could not move.</p>
<p>Now I stood in front of the scratched wall of glass,<br/>
Knowing Isidora would never forgive my cruel actions, so brass,<br/>
Yet my lips curled to the familiar "<i>Es mea culpa</i>," as if it were an obligation,<br/>
But her familiar lack of response set me in my station.<br/>
&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;I pleaded with her but she did not move.</p>
<p>Her pallid face was so gaunt and strict,<br/>
I stared directly into her eyes, but she remained emotionless.<br/>
After my begging to the wall, to her, I swear I did see her stir,<br/>
Though to my raging, violent thoughts and feelings, did my sanity defer.<br/>
&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;I spoke to her but she would not move.</p>
<p>"Ehm, Signor, I am so sorry to interrupt you in your state of gloom,<br/>
But I have finished cleaning the corridors and now I should clean this room."<br/>
So I stepped away, as I had always done, leaving the bleak yet striking dame,<br/>
As I heard my servant mutter, "Old Benito has ruined the glass again, I must replace this frame."<br/>
&nbsp;	&nbsp; &nbsp; &nbsp; &nbsp;He removed her portrait from the wall but I did not move.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>