<?php

$aid = 'sharon';
$title = 'Swapper Report';
$cid = c8;
$issueid = i9;
$body = 
'
<p><i>Swapper Report is a monthly feature in which a question is anonymously asked through QuestionSwap.com. The unedited answers are compiled into each article.</i></p>
<p>This month, there are actually two questions featured in Swapper Report. Let me explain.</p>
<p>So I thought for a while (meaning two seconds) before deciding on the next question. I decided to ask "What is the meaning of life?" and (possibly) get some really good answers. At least, that was what I thought would happen.</p>
<p>First, I kept getting the answer "Forty-two." I had failed to foresee the fact that there are many, many <u>Hitchhiker\'s Guide</u> fans out there in the world.</p>
<p>So those are, of course, not going to be featured here.</p>
<p>Second, I got one answer directing me to the QuestionSwap rules page, which requested that "What is the meaning of life" NOT be asked, as too many people would reply "Forty-two."</p>
<p>Go figure.</p>
<p>So here are the few decent answers I got for "What is the meaning of life?" Then I\'ll move on to the next featured question.</p>
<p><b>What is the meaning of life?</b></p>
<p><i>Of all the questions... well, according to the Hitchhiker\'s Guide, it\'s 42. I can\'t remember why, but I\'d suggest either reading the book or watching the film (even though it\'s a poor adaptation). To me, it depends on the individual. For me, the meaning of life is to endulge as much as you can in as little time possible . A bit predictable I know, but that\'s because I\'m a shallow, self-absorbed little shit. For someone esle, maybe it\'s some crap like trying to better your situation in the face of adversity, or writing a sonnet, or climbing Mount Everest. Why do all that when you can watch someone else do it on your telebox from the comfort of your own living room. Whilst eating a steak dinner. And drinking tequila. In your underpants. I tell thee!</i></p>
<p><b>What is the meaning of life?</b></p>
<p><i>As a whole grain oat based breakfast cereal, <a href="http://www.lifecereal.com" title="Life cereal">Life</a> was designed by the Quaker Oat Company to provide kids with a nutritious start to the day.</i></p>
<p><i>One could therefore argue that the meaning of Life, it\'s very reason for being, is simply to fill the stomachs of thousands of American children.</i></p>
<p><b>What is the meaning of life?</b></p>
<p><i>To gain love from your friends and respect from your enemies.</i></p>
<p><b>What is the meaning of life?</b></p>
<p><i>I already told you! To gain love from your friends and respect from your enemies!</i></p>
<p><i>Now go home!</i></p>
<p>(Oops. Them again, what are the odds?)</p>
<p>After that slightly disastrous attempt, I decided to ask a different question. Since a few friends were around, I shouted "ASK ME A PROFOUND QUESTION!" and the two I remembered were "What is the meaning of life?" and "What do you define as success?"</p>
<p>Well, I\'m sure you understand the rest.</p>
<p><b>What do you define as success?</b></p>
<p><i>Anything that I feel proud of, which includes physical stuff such as completing a marathon or having sex with a beautifull girl, intelectual ones such as passing an exam or stupid one such as giving a good answer to a question (though I am not sure this one is).</i></p>
<p><b>What do you define as success?</b></p>
<p><i>a personal success for me would be to own my own Pirate vessel and to sail the North sea, stealing from norwegian fishing vessels for food, and to have a wife on every harbour, YARRRRRGH!!!</i></p>
<p><b>What do you define as success?</b></p>
<p><i>Success is accomplishing the goals you have set forth for yourself.</i></p>
<p><b>What do you define as success?</b></p>
<p><i>Well friend the answer is simple. Success is when you are fully content with the product in front of you. In this very case and in actually every case, life. When you are fully satisfied with your situation and you see no points that need improvement or altering, ergo you have succeded.</i></p>
<p><b>What do you define as success?</b></p>
<p><i>To be proud of yourself.</i></p>
<p><i>What do you define as success?</i></p>
<p><i>I\'ve answered this one once, I said I wish to be the most infamous pirate on the north sea, in swashbuckling style, ye lillielivered landlubber!!!</i></p>
<p>If you have a question you think should be featured on Swapper Report, <a href="mailto:sharon@amalgammag.com" title="Email Sharon!">e-mail me</a>.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>