<?php

$aid = 'alexf';
$title = 'The Stain Removed';
$cid = c22;
$issueid = i9;
$body = 
'
<p>It was a pleasantly windy day as I enjoyed the last moments of the class I had been attending at the university. For an hour at least, the professor had questioned and probed his audience in a manner so similar to Socrates one would not have been surprised at the number of false ideas being assumed. I, for one, chose not to pay much attention to these lectures, relying instead on the class textbook. Indeed, the confusion of the class increased further as it was announced that our tests would be returned.</p>
<p>The suffering I had taken from Libroto thus far must now be mentioned. His incessant good fortune in these tests does not come from his hard work, but rather from a blatant disregard of probability. The professor writes ambigious multiple choice test questions, which invariably lead one to failure, yet still, the pompous Libroto manages to pass them all! He does nothing extra compared to me; I read the book, and I practice online questions.</p>
<p>The professor has told the class that the grades will be curved until the top person reaches an A+. Nevertheless, Libroto manages to get higher, and the rest of the class continues to fail. The ill feeling towards him was further compounded by the teacher\'s high opinion of him as well as his smiling insistence that he was doing nothing wrong. How I hated him! He was nothing but a lazy bum. It must be stated, however, that I never did purpose to have any revenge on him. But that night, the events conspired against me. I merely waited and watched, but when the opportunity came for revenge, how could I pass it by? After all, I was rendering a service to society; it was my duty to rid the world of him.</p>
<p>That evening, the dark and gloomy street lights glowed dimly through the rainy streets. As I walked through the empty roads, the wet, frozen air surrounded me, sending shivers down my spine. On this Hallow\'s Eve, I desired to go door to door, collecting sweets from the silent neighbors. My bag had reached quite a size when I finally had arrived at Libroto\'s house. It was covered in cobwebs and spiders, and an eerie yellow glow was emitted from the inside. Knocking, I waited for Libroto to come to the door.</p>
<p>"Trick or treat!" I shouted happily.</p>
<p>"Hello, there, Vidioto. That is a very nice costume," he responded with equal cheer.</p>
<p>"Thanks. Hey, Libroto." There was a pause. "Do you have any candy for me?"</p>
<p>"Sadly, I do not Vidioto. I\'m afraid I will have to choose \'trick\'!" With that, he slammed the door in my stunned face. The wetness, (or was it the loneliness of the street?), caused me to shiver. I was silent for a while, but then I knocked again.</p>
<p>"Libroto!"</p>
<p>"Yes?" He was smiling with immature glee at the little fun he had created at my expense.</p>
<p>"That was a dirty trick. Come on now, for that, at least let me in where it is warm."</p>
<p>"Okay!" With that, he opened the door and allowed me in.</p>
<p>I settled in the living room by the roaring fire. Shifting around in the soft sofa, I finally settled into a comfortable position, letting myself take full advantage of the fire\'s drying powers. Libroto followed me in and set himself down beside me. From the fire light, I could see that Libroto wore the guise of a corpse. His hair was covered in dust and his clothes were faded and torn. The brown coloring of his long pants did not reach his ankles, which were painted bony and emaciated.</p>
<p>I sighed. "Libroto, what did you manage to get on that exam?"</p>
<p>"Well, I clearly didn\'t get the highest grade-"</p>
<p>"Come on," I urged. "What was it?"</p>
<p>"I did incorrectly answer a question everybody else answered correctly-"</p>
<p>"Well?"</p>
<p>"96."</p>
<p>Libroto was not one of tactics, for he clearly looked too pleased to be modest. Additionally, the fact that the grade was higher than that of anyone\'s in the class seemed to jump out at me at once. Annoyed, I turned to take out some of my spoils from this year\'s Halloween.</p>
<p>"Ooh, chocolate! I love chocolate," he said bouncing up and down on his sofa in excitement. The vibrations from the bounces caused me to accidentally drop the chocolate I was holding onto my suit. "Oh dear!" he shouted with equal excitement. "How unlucky, Vidioto. We must clean you up at once!"</p>
<p>"That is not such a good idea. I should really not exploit your hospitality so long, Libroto."</p>
<p>"It is quite alright, my friend. Let us descend then to the washing room."</p>
<p>The innocent voice was like the scratching of a hand\'s nails on a chalkboard. The screeching sound grated into my ears, and I felt I had the rightful urge to destroy it. But for then, I followed Libroto down into the damp staircase into the basement. There, he took a hearty tug at a rope. A single, bright light illuminated the room. Libroto stumbled into the room and beckoned me to follow down the creaking steps. I proceeded down a few steps and tripped, as Libroto had on the last step. Catching the rope, I managed to break my fall and succeeded in extinguishing the lights, dropping my candy bag on the way. The moonlight flowed in through from a small, solitary window.</p>
<p>"Are you alright, Vidioto?" he asked concernedly.</p>
<p>"At least I am fine, Libroto," I responded. With that, I picked up and swung my bag of candy where I knew his head to be. A loud thud told me that he would be unconscious. Adjusting my eyes to the darkness, I dragged Libroto\'s body across the floor towards what appeared to be the washing machine. Opening the lid, I managed to lift Libroto into the machine without his waking. But as I started the water, he began to mutter, and his eyes opened.</p>
<p>"Vidioto?" he asked, disoriented.</p>
<p>"Libroto," I responded. I measured a cup of detergent.</p>
<p>With realization, Libroto\'s eyes widened in terror. He started to scream, and I began to laugh. Dumping the detergent into his mouth, I watched as he choked on the bubbles formed by the hot water flowing into the basin. Around, around, around, he went. His fearful eyes spinning wildly around the agitator were the last image of him I saw as I closed the lid. A crack of lightning brightened the room, casting a long shadow on the floor of the basement. The figure stood with a black hooded cloak and held a long curved blade attached to a pole in one hand and a bag of candy in the other.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>