<?php

$aid = 'aneesh';
$title = 'Sleipnir';
$cid = c22;
$issueid = i9;
$body = 
'
<p> "Men - double file outwards on me, move through the locks slowly - the station doesn\'t have the annie plants working, so the gravy-plant and atmo-sys are down.  Helmets on dark/sense, weapons on single-fire - we don\'t know hull integrity, so low power - right, MOVE OUT!"</p>
<p>Sergeant Prets gestured with his gun as he unsealed the airlock.  As he had expected, the atmospheric regulation within the derelict station wasn\'t functional, and without the main power plants online to spin the station, the gravity generators, or \'gravy-plants\', were all offline.  This provided no obstacle to the trained soldiers, however; their combat suits provided both armor and an electromagnetic system on the boots to simulate gravity.</p>
<p>"PFC Krell!  Corporal Ment!  Take point!  Lances Firt and Dern, rearguard!  Everybody else, standard double-file on me!" the sergeant adjusted his orders as he took in the environment they\'d be working in.  The station had been destroyed nearly fifty years earlier, in the first Xeno War.  Sleipnir station had once housed the Gungir, the mighty plasma lance that had been instrumental in the victory over the Jotnar.  However, the mysterious alien aggressors had managed to cripple the once-mighty station, and it was abandoned as system after system went critical under a continuous onslaught.  By the time the Sol fleet had arrived, it had been too late.</p>
<p>Now, it was a useless derelict, but Prets had been ordered to lead a squad as a boarding party to obtain some unknown item - the naval specialist his men were escorting would know what to get, but Prets himself was not informed.  The sergeant didn\'t spend long trying to determine what it was; he was fully aware that asking too many questions was a dangerous, often suicidal act when working with ONI, which he was certain the specialist was from.</p>
<p>"Sir?"  Krell\'s questioning tone interrupted Prets\'s thoughts.  "Which way?"</p>
<p>Prets merely looked to the specialist from ONI, who pointed left.  "Hubward," Prets echoed.</p>
<p>The ten soldiers and single technical officer rounded the corner, moving closer towards the bridge, situated in the center of the station.  Prets gestured for his men to fall back and took point himself as he broke down the door that led into the second of the four concentric rings that made up the station, with the disc-like bridge at the very center along with the Gungir mount.  He moved through quickly, although the HUD on his helmet still displayed no unusual sources of warmth and no movement beyond that of his own troops.  Still, something felt very wrong about the entire situation.</p>
<p>A twitch out of the corner of his eye drew the sergeant\'s attention.  The station was abandoned, and his men should have been the only ones in so much as an AU radius of the place, yet he was certain that something had moved in the shadows.  No, that wasn\'t quite right either - it was the shadows that had seemed to shift.  It must have been a trick of the eye, he told himself, caused by the lights mounted on the armor suits that cut through the darkness of the station, but he was still not completely convinced.</p>
<p>There - again - a shadow moved - other side - no, left again - and right - the sergeant started looking back and forth.</p>
<p>"Sarge?" Ment asked.  "Something the matter, sir?"</p>
<p>"Did any of you see some motion?"</p>
<p>The assembled marines shook their heads, Krell adding a puzzled "No" as the ONI spook stood passively.</p>
<p>"Never mind, then, I\'m sure it was nothing.  Keep moving, men."  Prets continued forward, into the next hallway, where another door led hubward.  This one was unlocked, and the men passed through quickly.  One more ring to go, then the bridge, and then they could return to the small boarding craft and the <i>SNS Skidbladnir</i> waiting not far away.</p>
<p>Some odd filmy substance covered the door into the innermost ring, and Prets took a moment to consider how best to break it down without risking contact with an unknown material, when he saw another shadow shift.  This time, he could clearly see it moving, and when he looked directly at it, there was a face in the darkness, grinning maliciously.  In a single smooth motion, he raised his rifle and fired a bright blue beam into the shadow.  He turned, seeing another of the shadows with faces, and again opened fire.  He realized that none of his men were aiming for the shadows, and barked out, "The shadows!  Shoot the shadows!"  He whirled and fired again, dropping another shadow - and realized that his troops were not aiming for shadows, but for him.</p>
<p>Sergeant Prets was dead before he hit the ground, three of his men also lying lifeless where he shot them.</p>
<p>"The sergeant was delusional and shot three of his own men, he had to be killed for the safety of the squad.  I\'m aborting this mission, let\'s return to the <i>Skidbladnir</i>," announced the science officer.  The dark visor of his containment suit concealed his wide grin - and that he had no shadow.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>