<?php

$aid = 'aneesh';
$title = 'The Knight of the Fractured Realms';
$cid = c1;
$issueid = i9;
$body = 
'
<p>"Who are the five most powerful people in the Fractured Realms?"</p>

<p>"Pardon?  Five most powerful people... yourself at the top of the list, definitely, then King Saerus of Selis, Lord Hermech of Delphi..." The aide stopped, thinking.  "Uh... Queen Sekhmet of Helios, perhaps?  And then... uh... Prince Vladmir of Draeg?"</p>


<p>The general laughed.  "All powerful, but you left out the two most powerful people from the list, and put me at the top for flattery only - I\'m not even the strongest of the five you listed yet."</p>

<p>"Then who are the two I missed?"  The normally stoic aide looked slightly irritated that he would be accused of making such an error - perhaps he could not list the top five, but for his position he was sure that he could name the top three.</p>

<p>The general laughed again.  "Don\'t feel so bad - very few know about them, perhaps only the more powerful rulers know who they really are..."</p>
<hr><br/>
<p>"Ugh... how much longer?" asked the Knight, looking horribly uneasy in his saddle and almost ready to fall off.</p>

<p>"Would you calm down?  The town is just another minute away," replied the young woman next to him.</p>

<p>"Couldn\'t we have teleported?"</p>

<p>"We could have, but you need to deal with this fear of horses.  I mean, what kind of Knight is terrified of riding?"</p>

<p>"Oh, shut up, Alyssia."</p>

<p>"Come on, Rhyss, you know you love me anyway," Alyssia replied with a smile and a wink.  She was enjoying a rare chance to tease the Knight next to her.  "Just relax, we\'re almost there."</p>

<p>"Nobody of our rank rides anywhere, teleports are inexpensive and we can afford them easily, even if you couldn\'t cast the spell yourself."</p>

<p>"Our rank?  So says the self-described knight-errant who refuses all titles.  You could have had quite a few, you know.  And besides, we did teleport most of the way, I just had us ride to the final town from the nearest one."</p>

<p>"Of course I know, you never stop reminding me.  What about you?  You do have a fairly impressive title, but you don\'t make any use of it.  Lots of extra work for you, and you won\'t even claim the benefits."</p>
<p>Alyssia shrugged.  It was an old argument, one the pair had gone through many times, and one that they would no doubt have again, and again.  Still, for all the occasional bickering about their different philosophies towards the Realms, the two were good friends, and had been for some time.  Perhaps they made an odd pair at first glance, but in truth the two were not so dissimilar, and had a great deal in common.</p>
<hr><br/>

<p>Alexia was relaxing in the inn.  She was waiting for the other members of her party to arrive, and in the meantime, she decided to take a break in the common room.  The bard who was performing was actually fairly good, and she listened happily.  Kariudo, Sam, and Sean were likely to arrive soon, but she didn\'t mind the wait in the meantime.</p>

<p>Two figures rode past the window she was sitting at, catching her eye.  The first looked like a Knight or a Paladin, based on his armor.  As Alexia looked more closely, though, she was sure he was a Knight; she couldn\'t see any holy symbols, and his field plate was dull and dented, not the perfectly maintained gleaming armor of a holy warrior.  The warhammer at his side bore no crest, holy symbol, or distinction of any kind, as odd as the armor for a Paladin.  Even for a Knight, it was odd; he was clearly a fairly skilled and high-level warrior, yet his equipment was in poor condition and didn\'t bear any normal indications of high quality.  The oddest thing about the Knight, however, was that he looked awkward on his horse - in fact, he looked even afraid.  What kind of knight was afraid of riding a horse?  She giggled a little, imaging Kariudo or Sean unable to ride because of fear of the mount.</p>

<p>The woman at first seemed much more nondescript, yet more careful inspection made it evident that she was far from it. The tall, slim woman wore loose, light robes that would draw little attention - except that they were grey and bore the seal of the Grey Order, the largest guild of Sorcerers and Sorceresses in the Realms, on the front.  That along with the staff at her side - not particularly ornate, but bearing a telltale gemstone focus at one end - indicated that she was a Sorceress.</p>

<p>As the two stopped and turned to face the inn, she got a better look at them.  The woman had bright red, straight hair that flowed into the hooded cloak, making it difficult to see how long it was.  Her companion - a hired guard?  A fellow traveler?  A friend?  A bound blade? - removed his helm, the only unbuttered portion of his armor, revealing brown hair that fell just above his eyes in front, was fairly neatly arranged, and was cut shorter in the back.</p>

<p>Alexia smiled and turned as her companions entered the room.  Kariudo, the only one she had told she would be waiting in the inn instead of outside as usual, was leading, in his usual ornate half-plate armor over the finely cut clothing that indicated his status as a noble - Lord of Alonia, in fact - and his rapier at his side.  Sean, Kariudo\'s general and another friend, followed in studded leather armor, a large scythe on his back.  Sam hung off of Sean\'s arm, wearing no armor and loose clothing that let her move freely without getting in her way; a skilled martial artist, she didn\'t need to carry any weaponry with her.</p>

<p>"Sorry I\'m late, love," Kariudo said with a sheepish grin.  "Some things came up on the other side, but that\'s not relevant here.  Let\'s get on the quest."</p>
<hr><br/>

<p>Rhyss dismounted clumsily, wincing at the awkwardness with which he got off the horse.  Still, he had survived the ride, which was good enough for him; he hated horses, no matter how odd it was for a Knight.  "This is the inn?"</p>

<p>Alyssia swung off her horse with grace, letting the groom from the stable take it back into a stall.  "Yeah, this is the one."</p>

<p>"We could have taken a quest or something and teleported tomorrow, you know," he said reproachfully.</p>

<p>Alyssia looked hurt.  "But I wanted to spend some time with you just hanging out, not questing, and I thought a long ride together would be fun."</p>

<p>"I hate horses!"</p>

<p>"Then you need to learn better, don\'t you?"  The feigned hurt expression vanished, replaced with a sly smile.</p>

<p>"You just enjoy tormenting me."</p>

<p>"Maybe..."</p>

<p>"You get some sick pleasure out of making me go through that."</p>

<p>"I might..."</p>

<p>"This is stupid."</p>

<p>"I just have two words to say in my defense... \'snake\' and \'quest\'.  Get my drift?"</p>

<p>Alyssia\'s level glare accompanying her words caused Rhyss to raise his eyes and look up in mock defeat.  "I give, I give... but the quest wasn\'t that bad..."</p>

<p>Alyssia lightly whacked her traveling companion on the head.  "Yes it was!"</p>

<p>The snake quest had been a surprise - Ryss had left out the details of what their mission would be when he brought Alyssia along, making it seem like simple item recovery.  The fact that instead of normal traps, there were snakes everywhere and even several naga guards was among the details he had omitted; it was that day that he learned that Alyssia had a mortal fear of snakes.</p>
<hr><br/>
<p>"Just a few more days and I should have enough resources to attack Erlen with almost no losses.  Then I just need to push through Amel, Kretz, and Pixia, and we\'re up to the mountains.  Erlen is the only one with enough military power to matter much.  Once we have it, we can get the southern portion of the range through Amel.  Kretz and Pixia are too weak to provide much resistance - if we offer a position within our military, or allow their leaders to retain some degree of power as governors within our empire, they will almost certainly allow themselves to be annexed without bloodshed."  The general smiled as he gestured and pointed on the map.</p>

<p>"Excellent work, general... our empire will grow to greatness, it is only a matter of time now.  If we hold the entirety of the Elmenstar mountain range and maintain holdings all the way to Haven, we should be able to stage attacks through the mountains into other regions as well.  You have my full permission to engage in this assault."</p>

<p>"Thank you, Emperor. May the Ever Victorious Armies sweet the Realms with their might, and may we stand together at its head as all the nations within the Realms bow to us."</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>