<?php

$aid = 'editors';
$title = 'Editor\'s Note: Issue 9';
$cid = c19;
$issueid = i9;
$body = 
'
<p>Hey guys! It\'s been forever since an issue has been released, hasn\'t it? I\'d like to extend my apologies - it seems like school never lets up with its constant homework overloads, quizzes, and tests. But enough about that -</p>
<p>It\'s second semester! Only 5 more months left till the end of the school year! And for you seniors, graduation!</p>
<p>I don\'t really know what to recommend in this issue - there are articles spanning all the way from Halloween, but nothing really in the holiday spirit. Still, most of the articles are amusing, fun reads and not too heavy on the mind.</p>
<p>I hope everyone had a great holiday season! Enjoy the issue!</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>