<?php

$aid = 'sharon';
$title = 'Disappointment';
$cid = c3;
$issueid = i9;
$body = 
'
<p>Disappointment<br/>
Is a funny thing<br/>
You never know what anticipation might bring</p>

<p>Disappointment<br/>
Can sure mess everything around<br/>
You\'re first in the sky and then kersplat on the ground</p>

<p>Disappointment<br/>
Is something you can\'t really avoid<br/>
You build up a hope and then it\'s destroyed</p>

<p>Disappointment<br/>
Crashes down on your soul<br/>
You don\'t know what to do and you lose control</p>

<p>Disappointment<br/>
Struck me down today<br/>
I\'m upset as hell but might be okay.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>