<?php

$aid = 'sharon';
$title = 'Help!';
$cid = c3;
$issueid = i9;
$body = 
'
<p>If you\'ve been to a bookstore<br/>
You\'re surely aware<br/>
Of the wave of self-help books<br/>
That pile the shelves there</p>

<p>How to get through your divorce<br/>
Or avoid it altogether<br/>
How to raise the perfect kid<br/>
How to divine the weather</p>

<p>How to do calculus<br/>
If you know two plus two<br/>
How to make an atomic bomb<br/>
How to creatively tie your shoe</p>

<p>How to bake cookies<br/>
How to get that slim frame<br/>
How to make money from nothing<br/>
How to get fortune and fame</p>

<p>Anyone can help anyone<br/>
That\'s freedom of speech<br/>
But should we trust this anyone<br/>
And believe what the how-to books teach?</p>

<p>I have a suspicion<br/>
That these authors know squat<br/>
They only write help books<br/>
Cause they can\'t write \'round a plot</p>

<p>You can write a book for the best<br/>
That can help with the worst<br/>
I think what you need<br/>
Is to help yourself first.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>