<?php

$aid = 'sharon';
$title = 'When...';
$cid = c3;
$issueid = i9;
$body = 
'
<p>When...</p>

<p>Someone called me a name<br/>
I walked away<br/>
And cried in a corner<br/>
Where no one would see</p>

<p>When I was done<br/>
I told everyone<br/>
I knew they\'d have<br/>
Good things to say \'bout me</p>

<p>I showed them my pain<br/>
They reacted the same<br/>
When I told them<br/>
What happened to me</p>

<p>"You poor thing!" they cried<br/>
"That awful person lied<br/>
You\'re a great person,<br/>
It\'s easy to see"</p>

<p>And though it was nice<br/>
These people with their advice<br/>
It wasn\'t<br/>
What I need</p>

<p>Because what I need<br/>
Is an apology<br/>
From the person who was<br/>
So mean to me.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>