<?php

$aid = 'stephanie';
$title = 'Community: Taking a Closer Look at Autism';
$cid = c7;
$issueid = i2;
$body = 
'
<p>	Living in an area known for its emphasis on acceleration in every area, especially education, I was surprised when I met a group of individuals who redefine the meaning of learning and growth in a way most of us don\'t initially understand. This group of children were autistic, a diagnosis that isn\'t fully understood yet. </p>
<p>Autism is a developmental disorder, unrelated to the intellectual functions like stereotypes make us believe.  Rather, the neurological disorder affects the normal development of the brain in the social and communicative areas; thus, the diagnosis is normally during later childhood after certain milestones, including subtle ones, are missed. Characteristics include lack of reciprocal social interaction, communication deficiency, and signs of stereotypical interests and activities, such as rocking, spinning objects, or other self-soothing behavior.</p>
	<p>I never realized that there were so many individuals or families affected by autism in the Bay Area, and yet, when I volunteered for the first time on a Saturday at the Organization for Special Needs Families (OSF), there were approximately 25 children per volunteer session.</p>
<p>For two hours at OSF, I watched over a little five year old girl as she played, worked on arts and crafts, interacted with a computer game, listened to music, and ran around during a P.E. class. Obviously, I was fairly tired by the end of it - who wouldn\'t be, after watching an extremely active and curious little child? Had I not known that she was autistic, I would not have been able to tell the difference, since many of the behaviors that were signs of autism were similar to the habits of any child between 3 and 6-speaking occasional words of a private "language" that I couldn\'t understand, needing constant reminders to stay focused, or even flashes of contrariness and uncooperativeness. Clearly, she was a bright child, with a keen perception of her surroundings and noticeable memory for classical music-the only visible sign of autism was that she communicated her needs through physical means such as facial expression, rather than conventional verbal communication.</p>
	<p>Aside from the rewarding effect of volunteering in general, working with autistic children brought a degree of perspective about the sensitivity that we need when classifying those around us who have special needs. Not only does it bring awareness and solidarity to the community, but such an education provides a better perspective for one\'s own learning and skills.</p>
<br />
To learn more about volunteering opportunities with OSF, contact them at:<br/>
(Address) 20920 McClellan Road, Cupertino, CA 95014<br/>
(Email) <a href="mailto:assistosf@yahoo.com">assistosf@yahoo.com</a><br/>

';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>