<?php

$aid = 'kriti';
$title = 'Abortion';
$cid = c8;
$issueid = i2;
$body = 
'
<p>That word may mean nothing to you, but it means the world to countless women across the globe. California\'s recently failed Proposition 73 urged for parental notification laws when involving an abortion by a woman under the age of 18. Although this resolution has already failed, I wanted to ask you what you think. To provide a little background, here are the general arguments proposed by both sides. </p>

<p>Proponents of this proposition emphasized that this proposition was solely requiring parental notification, not parental consent. It is ultimately up to the person in question to make her choice. Given that the majority of minors notify their parents of their choices to take abortions anyway, this law would have merely called for more mass reform. Moreover, a woman\'s health should be taken into consideration. Suppose there are medical complications, who helps the minor? Is the doctor responsible? </p>

<p>When looking at this issue, however, one must consider the issue of privacy. </p>
<p>Is it up to the minor to decide whether or not she feels comfortable to tell the truth? How does she cope if she lives within an abusive family? Some argue that government involvement is not the key to promoting communication amongst children and their parents. The family issue should remain in the family. By enforcing communication it may ultimately lead to more illegal, or "back-alley" abortions.  Furthermore, by instituting this law, one merely delays any taken action. For instance, if a parent objects to the decisions of a minor, the family must appear before court and obtain a waiver. </p>

<p>Before we can answer this question we must consider the key issues of privacy, as well as the rights of a parent. Here are some opinions of fellow students. </p>

<p>Neil Shah opposed this proposition as he stated that "forcing the child to [inform her parents] may make her resort to back-alley abortions." </p>

<p>Jasmyn Johal, a proponent of this proposition, believes that "if your parents took care of you since you were born [ . . .], then they\'d care about you enough to want to know if you\'re getting an abortion."</p>

<p>Stephanie Benedict argued that this proposition "would have made more girls afraid to come forward and have the procedure done, potentially risking their health and well-being."</p>

<p><strong>Now, I ask you. What do you think?</strong></p> 

';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>