<?php

$aid = 'ruchi';
$title = 'Just Chill';
$cid = c15;
$issueid = i2;
$body = 
'


<p>So I was talking to one of my good friends the other day. No, her name isn\'t really Sally, but I figured she\'d prefer some privacy rather than having her name splashed onto the internet. Be warned: our conversation isn\'t exactly "clean."</p>
<br/>
<strong>Sally:</strong> i dont know what the hell i\'m doing with my life<br/>
<strong>Me:</strong> ?<br/>
<b>Me:</b> welcome to teh rest of the world Sally<br/>
<b>Sally:</b> no like really<br/>
<b>Sally:</b> i\'m just not doing anything<br/>
<b>Sally:</b> i\'m throwing it away<br/>
<b>Me:</b> ...ehhh what do u mean?<br/>
<b>Sally:</b> stupid choices<br/>
<b>Sally:</b> and i have a habit of fucking myself over<br/>
<b>Sally:</b> so now ive procastinated too much, ive made stupid choices, and i still am making stupid choices<br/>
<b>Me:</b> if u realize what u\'ve done<br/>
<b>Me:</b> u can fix it<br/>
<b>Me:</b> you know that right?<br/>
<b>Me:</b> i mean life isn\'t set in stone<br/>
<b>Sally:</b> i cant go back and retake the tests<br/>
<b>Sally:</b> or actually do the homework<br/>
<b>Me:</b> no u cant<br/>
<b>Sally:</b> or actually learn the 18 chapters of physics<br/>
<b>Sally:</b> or undo the shit i\'ve done<br/>
<b>Sally:</b> rawreja;owjotgaijwr;gjarijyhitjhab;<br/>
<b>Me:</b> hahah<br/>
<b>Me:</b> that\'s not actually true<br/>
<b>Me:</b> you can\'t retake the tests or do the hw<br/>
<b>Me:</b> i admit that<br/>
<b>Me:</b> but you CAN learn the physics<br/>
<b>Me:</b> and as for the "shit" hahah there\'s AWLAYS ways to at least salvage PART of the past<br/>
<br/>
<p>	Yep. But it made me think. In a way, "Sally" is right. There are choices we make in the past which just screw us over. We can\'t do much about it. After all, we are young, somewhat stupid, and often just don\'t care enough to put in the effort. But if we make the choices, maybe we should start dealing with them and trying to fix them.</p>
<p>	We\'re at the age where we still have that opportunity. We can screw up, get screwed up, but still pull through. Maybe we should take some advantage of that. I mean, I\'m still young. It\'s my sophomore year. Even so, the decisions I make now affect what\'s going to happen with  me in the next few years. </p>
<p>	I\'m not saying "pull your act together and make the right choices." I\'m all for making stupid ones. If we don\'t make mistakes, what\'s the fun of life? Messing up is definitely one of the highlights of being human. But I am saying that no matter what we\'ve done, we can still get off our butts and fix our problems. Some, yes, are unfixable. A flunked test, a forgotten homework... but those aren\'t the things that really matter anyway. I mean, you can fail a test, but if you learn the material it\'s going to show through.</p>
<p>	My chemistry teacher told my class that a test is just what we know at that specific point in time. What\'s to say we don\'t learn before and after? We keep what we find important and discard what isn\'t as special. And that\'s just how life is.</p>
<p>	So, for all those Sally\'s, sure you made some stupid choices. Sure you don\'t know where your life is headed. A lot of us don\'t. And some of us make considerably dumber choices than you. But don\'t worry. We\'re all still kids and we have time left. We can fix our mistakes, or some of them, and we can make better decisions in the future.</p>
<p>	In the famous words of most of the teenagers in the state of Cali, "Just chill." </p>

';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>