<?php

$aid = 'emily';
$title = 'Review of Kolina Teng\'s Artwork';
$cid = c5;
$issueid = i2;
$body = 
'
<p><a href="http://www.geocities.com/koliflower/hic.jpg"><img width=151 height=184
src="http://www.geocities.com/koliflower/hic.jpg"></a>
<a href="http://www.geocities.com/koliflower/doncat2.jpg"><img width=251 height=184
src="http://www.geocities.com/koliflower/doncat2.jpg"></a>
<a href="http://www.geocities.com/koliflower/halloween05.jpg"><img width=231 height=184
src="http://www.geocities.com/koliflower/halloween05.jpg"></a></p>

<br/>
<p>UC Davis student Kolina Teng\'s artwork is simple, cute, and
comical. The boring college classes inspired her to doodle. If these are
doodles, I don\'t know what to call my artwork! Visit her website for full
versions of the displayed artwork and more: <a href="http://www.geocities.com/koliflower">http://www.geocities.com/koliflower</a></p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>