<?php

$aid = 'natalie';
$title = 'Focus on a Designer: Stella McCartney';
$cid = c11;
$issueid = i2;
$body = 
'
<p>Stella
McCartney is an amazing designer who crafts elegant sophisticated womenwear
while still bringing a similar flair to trendy stores like H&amp;M and sporty
brands like Adidas. From the time she was born, her name has carried fame and
fortune. After all, she is the daughter of ex-Beatle Paul McCartney. However,
her namesake is not what has made her a world-renown designer. In fact, she has
made a name for herself in the high-end fashion industry of today. Born in 1972
in London, her artistic talent and savvy style was soon recognized after
graduating from Central St. Martin\'s College of Art &amp; Design. With a
stunning resume, of which included working with Christian Lacroix at the age of
fifteen, she soon found work as the creative director at Chloe. Though critics
were skeptical at first, her abilities soon became apparent in just her first
collection.<o:p></o:p></span></p>

<p>In 2001,
she launched her own line with Gucci, and since then she has set up three
stores worldwide. She designed for Madonna\'s 2004 "Reinvention tour", Annie
Lennox, and the movie "Sky Captain and the World of Tomorrow," and she even has
a line of fragrances. More recently, she has collaborated with H&amp;M, with
her label Stella McCartney for H&amp;M. She is also launching a collection of
sportswear with Adidas.<o:p></o:p></span></p>


<p><!--[if gte vml 1]><v:shapetype
 id="_x0000_t75" coordsize="21600,21600" o:spt="75" o:preferrelative="t"
 path="m@4@5l@4@11@9@11@9@5xe" filled="f" stroked="f">
 <v:stroke joinstyle="miter"/>
 <v:formulas>
  <v:f eqn="if lineDrawn pixelLineWidth 0"/>
  <v:f eqn="sum @0 1 0"/>
  <v:f eqn="sum 0 0 @1"/>
  <v:f eqn="prod @2 1 2"/>
  <v:f eqn="prod @3 21600 pixelWidth"/>
  <v:f eqn="prod @3 21600 pixelHeight"/>
  <v:f eqn="sum @0 0 1"/>
  <v:f eqn="prod @6 1 2"/>
  <v:f eqn="prod @7 21600 pixelWidth"/>
  <v:f eqn="sum @8 21600 0"/>
  <v:f eqn="prod @7 21600 pixelHeight"/>
  <v:f eqn="sum @10 21600 0"/>
 </v:formulas>
 <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
 <o:lock v:ext="edit" aspectratio="t"/>
</v:shapetype><v:shape id="_x0000_i1025" type="#_x0000_t75" alt="" style=\'width:180pt;
 height:271pt\'>
 <v:imagedata src="inc/MSfiles/23/image001.jpg" o:href="http://www.style.com/style/view/87/13/100051387.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=271
src="inc/MSfiles/23/image002.jpg" v:shapes="_x0000_i1025"><![endif]><span
style="mso-spacerun: yes">&nbsp;</span><!--[if gte vml 1]><v:shape id="_x0000_i1026"
 type="#_x0000_t75" alt="" style=\'width:180pt;height:270pt\'>
 <v:imagedata src="inc/MSfiles/23/image003.jpg" o:href="http://www.style.com/style/view/56/13/100051356.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=270
src="inc/MSfiles/23/image004.jpg" v:shapes="_x0000_i1026"><![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>Spring 2002
Ready-To-Wear Collection<br>
This collection embodies a somewhat flashy but still understated elegance
displayed through the use of crème yellows and dark blues, off-the-shoulder
above-the-knee dresses and<span style="mso-spacerun: yes">&nbsp;
</span>clean-cut feminine suits.<o:p></o:p></span></p>


<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><!--[if gte vml 1]><v:shape
 id="_x0000_i1027" type="#_x0000_t75" alt="" style=\'width:180pt;height:270pt\'>
 <v:imagedata src="inc/MSfiles/23/image005.jpg" o:href="http://www.style.com/style/view/95/78/100067895.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=270
src="inc/MSfiles/23/image006.jpg" v:shapes="_x0000_i1027"><![endif]><span
style="mso-spacerun: yes">&nbsp;</span><!--[if gte vml 1]><v:shape id="_x0000_i1028"
 type="#_x0000_t75" alt="" style=\'width:180pt;height:270pt\'>
 <v:imagedata src="inc/MSfiles/23/image007.jpg" o:href="http://www.style.com/style/view/88/78/100067888.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=270
src="inc/MSfiles/23/image008.jpg" v:shapes="_x0000_i1028"><![endif]><br>
<!--[if gte vml 1]><v:shape id="_x0000_i1029" type="#_x0000_t75" alt=""
 style=\'width:180pt;height:270pt\'>
 <v:imagedata src="inc/MSfiles/23/image009.jpg" o:href="http://www.style.com/style/view/64/78/100067864.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=270
src="inc/MSfiles/23/image010.jpg" v:shapes="_x0000_i1029"><![endif]><span
style="mso-spacerun: yes">&nbsp;</span><!--[if gte vml 1]><v:shape id="_x0000_i1030"
 type="#_x0000_t75" alt="" style=\'width:180pt;height:270pt\'>
 <v:imagedata src="inc/MSfiles/23/image011.jpg" o:href="http://www.style.com/style/view/67/78/100067867.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=270
src="inc/MSfiles/23/image012.jpg" v:shapes="_x0000_i1030"><![endif]><br>
Fall 2002 Ready-To-Wear Collection<o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>Stella
McCartney uses bright colors to modernize a Grecian Goddess look.<span
style="mso-spacerun: yes">&nbsp; </span>However, she also reaches in the other
direction, making a gothy black look elegant. In addition, the grunge look of
the early 1990\'s is brought back in the large oversize jackets and sweaters.<o:p></o:p></span></p>


<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><!--[if gte vml 1]><v:shape
 id="_x0000_i1031" type="#_x0000_t75" alt="" style=\'width:180pt;height:270pt\'>
 <v:imagedata src="inc/MSfiles/23/image013.jpg" o:href="http://www.style.com/style/view/09/18/100101809.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=270
src="inc/MSfiles/23/image014.jpg" v:shapes="_x0000_i1031"><![endif]><span
style="mso-spacerun: yes">&nbsp;</span><!--[if gte vml 1]><v:shape id="_x0000_i1032"
 type="#_x0000_t75" alt="" style=\'width:180pt;height:270pt\'>
 <v:imagedata src="inc/MSfiles/23/image015.jpg" o:href="http://www.style.com/style/view/02/18/100101802.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=270
src="inc/MSfiles/23/image016.jpg" v:shapes="_x0000_i1032"><![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>Fall 2003
Ready-To-Wear Collection<br>
This collection is reminiscent of Victorian styles with its dark earthy colors
and the satin/charmeuse-like material. <o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><!--[if gte vml 1]><v:shape
 id="_x0000_i1033" type="#_x0000_t75" alt="" style=\'width:180pt;height:270pt\'>
 <v:imagedata src="inc/MSfiles/23/image017.jpg" o:href="http://www.style.com/style/view/17/94/100119417.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=270
src="inc/MSfiles/23/image018.jpg" v:shapes="_x0000_i1033"><![endif]><span
style="mso-spacerun: yes">&nbsp;</span><!--[if gte vml 1]><v:shape id="_x0000_i1034"
 type="#_x0000_t75" alt="" style=\'width:180pt;height:270pt\'>
 <v:imagedata src="inc/MSfiles/23/image019.jpg" o:href="http://www.style.com/style/view/23/94/100119423.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=180 height=270
src="inc/MSfiles/23/image020.jpg" v:shapes="_x0000_i1034"><![endif]><br>
Spring 2004 Ready-To-Wear Collection<o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>Stella
McCartney\'s classic delicate feminine pieces are epitomized here in these
delicate, airy chiffon dresses, dyed to reveal a range of cool colors. <o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><!--[if gte vml 1]><v:shape
 id="_x0000_i1035" type="#_x0000_t75" alt="" style=\'width:178pt;height:266pt\'>
 <v:imagedata src="inc/MSfiles/23/image021.jpg" o:href="http://www.style.com/slideshows/fashionshows/S2006RTW/SMCCARTN/RUNWAY/00070m.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=178 height=266
src="inc/MSfiles/23/image022.jpg" v:shapes="_x0000_i1035"><![endif]><span
style="mso-spacerun: yes">&nbsp;</span><!--[if gte vml 1]><v:shape id="_x0000_i1036"
 type="#_x0000_t75" alt="" style=\'width:178pt;height:268pt\'>
 <v:imagedata src="inc/MSfiles/23/image023.jpg" o:href="http://www.style.com/slideshows/fashionshows/S2006RTW/SMCCARTN/RUNWAY/00010m.jpg"/>
</v:shape><![endif]--><![if !vml]><img width=178 height=268
src="inc/MSfiles/23/image024.jpg" v:shapes="_x0000_i1036"><![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>Spring 2006
Ready-To-Wear Collection<o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>While
Stella McCartney\'s design has always been feminine, we can see that in this
collection she has added a few menswear pieces such as the trouser shorts and
the long button-up white overshirt that subtly yet successfully accentuate a
woman\'s femininity. <o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>CREDITS:<o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>ALL PHOTOS
ABOVE WERE TAKEN FROM <a href="http://www.style.com/"><span style=\'color:windowtext\'>WWW.STYLE.COM</span></a>
<o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial;color:#666666\'><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>Off the
runway, her designing is still impeccable, with her one-time production line
with popular chain store H&amp;M.<o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><!--[if gte vml 1]><v:shape
 id="_x0000_i1037" type="#_x0000_t75" alt="stella mccartney 240x370" style=\'width:180pt;
 height:278pt\'>
 <v:imagedata src="inc/MSfiles/23/image025.jpg" o:href="http://www.handbag.com/graphics/library4/6105_XM45_0301370.jpg"/>
</v:shape><![endif]--><![if !vml]><img border=0 width=180 height=278
src="inc/MSfiles/23/image026.jpg" alt="stella mccartney 240x370" v:shapes="_x0000_i1037"><![endif]><span
style="mso-spacerun: yes">&nbsp;</span><!--[if gte vml 1]><v:shape id="_x0000_i1038"
 type="#_x0000_t75" alt="stella mccartney 240x370" style=\'width:180pt;height:278pt\'>
 <v:imagedata src="inc/MSfiles/23/image027.jpg" o:href="http://www.handbag.com/graphics/library4/6105_XM45_0311370.jpg"/>
</v:shape><![endif]--><![if !vml]><img border=0 width=180 height=278
src="inc/MSfiles/23/image028.jpg" alt="stella mccartney 240x370" v:shapes="_x0000_i1038"><![endif]><br>
<!--[if gte vml 1]><v:shape id="_x0000_i1039" type="#_x0000_t75" alt="stella mccartney 240x370"
 style=\'width:180pt;height:278pt\'>
 <v:imagedata src="inc/MSfiles/23/image029.jpg" o:href="http://www.handbag.com/graphics/library4/6105_XM45_0305370.jpg"/>
</v:shape><![endif]--><![if !vml]><img border=0 width=180 height=278
src="inc/MSfiles/23/image030.jpg" alt="stella mccartney 240x370" v:shapes="_x0000_i1039"><![endif]><span
style="mso-spacerun: yes">&nbsp;</span><!--[if gte vml 1]><v:shape id="_x0000_i1040"
 type="#_x0000_t75" alt="stella mccartney 240x370" style=\'width:180pt;height:278pt\'>
 <v:imagedata src="inc/MSfiles/23/image031.jpg" o:href="http://www.handbag.com/graphics/library4/6105_XM45_0306370.jpg"/>
</v:shape><![endif]--><![if !vml]><img border=0 width=180 height=278
src="inc/MSfiles/23/image032.jpg" alt="stella mccartney 240x370" v:shapes="_x0000_i1040"><![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>(Photos
taken from: <a
href="http://www.handbag.com/galleries/gallery/Style_trends/Fashion_Buys/fashion_stella/MemberID=12/">http://www.handbag.com/galleries/gallery/Style_trends/Fashion_Buys/fashion_stella/MemberID=12/</a>)<o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>Though
there are similarities between this collection and her runway ready-to-wear
collection, these garments are geared more towards a trendy, street style.<o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><b><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></b></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><b>Adidas
by Stella McCartney<o:p></o:p></b></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial;color:#666666\'><b><!--[if gte vml 1]><v:shape
 id="_x0000_i1041" type="#_x0000_t75" alt="stella mccartney for adidas"
 style=\'width:446pt;height:257pt\'>
 <v:imagedata src="inc/MSfiles/23/image033.jpg" o:href="http://www.stylemaven.com/images/stylefile/stylefile_banner_stellaadid.jpg"/>
</v:shape><![endif]--><![if !vml]><img border=0 width=446 height=257
src="inc/MSfiles/23/image034.jpg" alt="stella mccartney for adidas" v:shapes="_x0000_i1041"><![endif]></b></span><span
style=\'font-size:10.0pt;font-family:Arial\'><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>Taken from:
<a href="http://www.stylemaven.com/stylefile_stella4adidas_feb2005.htm">http://www.stylemaven.com/stylefile_stella4adidas_feb2005.htm</a>
<o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'><![if !supportEmptyParas]>&nbsp;<![endif]><o:p></o:p></span></p>

<p class=MsoNormal><span style=\'font-size:10.0pt;font-family:Arial\'>Stella
McCartney\'s multifaceted talent is shown in her ability to design different
styles of garments- proving herself as a true fashion designer; However, she
characterizes each piece and collection she innovates with an own trait of her
own- on the runway, in stores, and in sportswear. In many ways, she is an
"elite" designer, but she has also brought her designs to the general public. Stella
McCartney has officially made her own name in the fashion business, and she
will be continuing to do so for a long time.<o:p></o:p></span></p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>