<?php

$aid = 'sharon';
$title = 'Autism';
$cid = c3;
$issueid = i2;
$body = 
'
The world is too big for me.<br/>
Lost here in a babble of incoherence<br/>
People grimace, contort their faces<br/>
Until they are not human anymore<br/>
I don\'t understand what they do<br/>
I cannot read what cannot be read<br/>
I don\'t understand these towers<br/>
With someone at the top<br/>
Am I the one below?<br/>
This whirling behemoth of wild colors<br/>
Or changing faces<br/>
Of those who are my kind<br/>
But I don\'t see<br/>
Who they are<br/>
They are different<br/>
Different from me, and different from themselves<br/>
I don\'t understand<br/>
Please help me, I am lost<br/>
Can you understand?<br/>
Surely you who are not like me<br/>
See something I do not<br/>
Surely you know the rules to this game<br/>
I am lost<br/>
But in my world I am king<br/>
So I hide in my cove, with my crown on my brow,<br/>
Where I reside alone with companions I make<br/>
And the friends I choose<br/>
The colors I choose to see and<br/>
The music I choose to hear<br/>
It makes more sense<br/>
Than endless cycles<br/>
Of what I do not understand.<br/>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>