<?php

$aid = 'ruchi';
$title = 'The Best Sunday Afternoon';
$cid = c1;
$issueid = i2;
$body = 
'
<p>I have to admit, sitting on a Sunday morning drinking coffee is the best. Just staring at the window, snickering at the overweight kid, who\'s attempting to run a few miles to lose weight, sink his teeth into a doughnut right outside my window.</p>
<p>The coffee is so relaxing - I swear, if I had to go a day without caffeine, I might go insane. After all, I need the energy boost.</p>
<p>I watch the overweight kid put down the doughnut (actually, trash the doughnut... or what\'s left of it) and resume running, feet pounding on the cement. I have to wince. The noise, and tremors, are enough to bring down my apartment building.</p>
<p>Sighing, I drain the rest of my coffee and proceed with my waking up ritual. Eat breakfast, take a shower, start the laundry, and get ready to hit work. If there\'s one thing I hate about my work, it\'s that I have to work on Sunday\'s. But, hey, I get Friday and Saturday off, and Sunday is off early.</p>
<p>Slipping into my little black Bug, I turn on the radio, blasting some rock into my ears. I roll down the windows and sing my heart out to Kelly Clarkson. Much too soon, I pull up to my work.</p>
<p>Ah. The agony of switching off that radio and stepping out of my car is too  much to describe. But, still, I plaster on a fake smile and walk into the yoga center.</p>
<p>The yoga center - it\'s a relaxing place. There\'s always some soft music playing, courtesy of Charlene, the other yoga teacher. She can\'t live without some amount of noise in the background.</p>
<p>I snort quietly as I see the overweight kid from earlier walk into Charlene\'s class. What a small world. I make a mental note to tell her I saw the kid trying to eat doughnuts and run at the same time. We\'ll have a good laugh over that later, after our classes are over at noon.</p>
<p>Slowly, my class starts to trickle in. Ah, the famous and wealthy. It\'s always amusing to see some new "student" come in wearing Christian Dior perfume and Armani boots. Or, better yet, wearing sweats that cost more than my car.</p>
<p>"Okay class," I say ten minutes later. "Let\'s stretch quickly before we start." I put on some relaxing instrumental music, the kind that reminds a person of water dribbling over rocks or a small stream.</p>
<p>The class slowly progresses, and I feel like it\'s taking forever. What is so hard about the Cat position? Or the transitions? I snicker quietly as I imagine the overweight kid trying to manage even a simple yoga move. Probably will hurt something while thinking about a doughnut, I reflect with a smile.</p>
<p>Hours later, two and a half to be precise, class is over and I stretch myself out as I watch my wealthy clients leave. I hear them discussing the class:</p>
<p>"Oh, Mary Anne! I just couldn\'t get that headstand position! Do you think that\'s a sign of stress?"</p>
<p>"No, don\'t worry about it Doreen," Mary Anne reassures her, "it just takes practice. You\'re only stressed if you can\'t..."</p>
<p>I chuckle to myself yet again and roll up the yoga mats, taking the time to speak to a few of my clients before I pack up to meet Charlene.</p>
<p>"So, how was class?" she asks once we enter Starbucks.</p>
<p>"Good," I reply. "The normal. A bunch of rich idiots who think that just because they can\'t do yoga yet, they are stressed."</p>
<p>"Amazing," she said, shaking her head.</p>
<p>"I know," I grinned. "God, I love my job."</p>
<p>"Same here," she added. We looked out the window, only to see the overweight kid at it again.</p>
<p>"Wow," I said. "Dedicated kid there."</p>
<p>"Still has reason to hope," shrugged Charlene.</p>
<p>I snorted yet again into my coffee. Sitting on a Sunday afternoon drinking coffee may not be the best, but it\'s pretty damn close.</p>


';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>