<?php

$aid = 'gwynnie';
$title = 'Annoyance Toward Depression Tests, a Memory';
$cid = c15;
$issueid = i3;
$body = 
'
<p>Sometime in early 2005, my counselor suggested that I take a depression test, as I was not as bubbly and talkative as normal - a clear sign that I was upset about something.</p>
<p>This idea, to be honest, completely terrified me. What if I was depressed? If I was, I knew that knowing would just send me straight out of atarxia and into one of my gloomy, self-absorbed moods. Reluctantly, I agreed, running my eyes over the list of questions. \'What on earth?\' I thought, looking with a mixture of surprise and annoyance at the piece of paper.</p>
<p>"Do I read books? Never, sometimes, often? What kind of question is that?" I asked. "Of course I don\'t read books anymore. Well, except for the ones at school, but I don\'t have any time to read for fun!"</p>
<p>"They just want to gauge how you spend your time," my counselor replied calmly. Muttering, I turned back to the form.</p>
<p>Obviously, some of the questions made sense - can you sleep well, have you thought about suicide, etc. But others, like the book one, were based on facts that I thought entirely unrelated. If I had no time to go outside or read a novel because of sheer lack of time, not because I wanted to, would I be diagnosed depressive?</p>
<p>I ended up right on the edge between mild depression and no depression. In my mind, as there were not many questions on the test in the first place, I was not depressed. Maybe it was my stubborn pride, but I was sure that those bogus questions had something to do with it.</p>
<p>The questions do have to be general ones that can apply to the majority, not overworked and stressed out private school kids, but why don\'t the people who write these tests just take out questions that have a time element to them? Who knew how many kids had had busy schedules and couldn\'t read for fun or gone outside, which tipped the scales of depression in their favor? Whatever the case, more relevant questions should be on tests such as these. Being told that one is depressed is a huge blow - why cause unnecessary stress through outdated assessments?</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>