<?php

$aid = 'gwynnie';
$title = 'Upper School Cooking Club';
$cid = c7;
$issueid = i4;
$body = 
'
<p>Ever wanted to learn how to cook or just some of the basic techniques around the kitchen? Perhaps you\'d just like to learn how to make some tasty treats. The newly formed Harker US Cooking Club meets every other Thursday in the kitchen next to the gym, unless otherwise stated by advisor Mr. Silk. Check the daily bulletin to find out when and what we\'ll be cooking up next, but make sure to contact Mr. Silk at <a href="mailto:AnthonyS@harker.org">AnthonyS@harker.org</a> to get your permission slip first!</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>