<?php

$aid = 'gwynnie';
$title = 'Movie Review: Good Night, and Good Luck';
$cid = c12;
$issueid = i4;
$body = 
'
<p>This Oscar nominee is a real work of genius. The screenplay is direct and biting, the actors don\'t overplay their roles and add unnecessary drama, and the usage of black and white, much sharper than I\'ve seen before, make this a wonderful film stylistically. Of course, many see it only as a vehicle for political commentary on the McCarthy era, but the issues of censorship in the media and using the right of free speech against the government come into play. With some light-hearted moments while the group celebrates their successes, this film shows both the factual and emotional impacts of McCarthy\'s regime. For anyone with a sense of justice or if you\'d just like to watch a very well-rounded and interesting film, "Good Night, and Good Luck" will be a sure hit.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>