<?php

$aid = 'stephanie';
$title = 'So Psyched';
$cid = c7;
$issueid = i3;
$body = 
'
<p>What is it about online quizzes that keep us distracted from homework for hours? They\'re merely the newest addition to a universal quest for humans to learn about themselves. From exploring learning patterns to inkblot tests, the Harker School\'s Psychology Club provides a firsthand experience for students at the high school level.</p>
<p>According to Annelise Han, the president and founder of the club, Psychology Club was "created as an opportunity for students, especially those who are not taking or have not taken any course in psychology, to explore this topic. People are interested in it because it\'s such a prevalent topic in related applications, such as stress, personality, creativity, emotion, dreams, intelligence, eating disorders, food and color preferences, memory, and relationships."</p>
<p>Ultimately, the goal of the club is to help students better understand and appreciate themselves and those around them, while having fun at the same time. And the members of Psychology seem to be doing just that.</p>
<br/>
<p align="center"><img src="inc/MSfiles/30.jpg" /></p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>