<?php

$aid = 'stephanie';
$title = 'A Case for Switch-side Debate';
$cid = c8;
$issueid = i3;
$body = 
'
<p>Think about the last time anyone, in an argument, spur of the moment debate, or a "discussion" (we all know what that means), admitted to being wrong or attempted to see it from the other side\'s view. A look at today\'s politicians, opinionated citizens who utilize their right to speech, and of course, teenagers, demonstrates a trend where people have predetermined what they believe and will argue for it until the cows come home. Not that the expression has ever really made sense to some of us, being city-slicks.</p>
<p> <img src="inc/MSfiles/31.jpg" class="left" /> Ever thought about the other person or platform\'s point of view? Play the devil\'s advocate, and upon doing so, you will learn about the structure of the arguments the other person is making. If you wholeheartedly attempt to see the world from someone else\'s view just as they would, you will gain understanding of what their arguments are. How are you going to argue with a foreign economist, hardcore environmentalist, or a Desperate Housewives enthusiast if you don\'t know what their platform is? Only by understanding their reason for taking that position can you engage them in those points and possibly defeat them. Sometimes along the way, however, you might find -oh horror! Of all things! - that you even agree.</p>
<p>"Because I said so." "I\'m always right." "Just because!" Heard these phrases before? In other words, they preclude someone who has no idea why they believe what they claim and having no other recourse, become childishly defensive. One way to avoid becoming that person is to switch-side debate against yourself; imagine the sort of arguments someone else might bring up, look for logical flaws that may not have occurred to you before, and in the process, think of answers you might use to respond and whether those responses hold up under scrutiny.</p>
<p>Gilbert Chesterton, an English writer (1874-1936), once said that "people generally quarrel because they cannot argue." Learning to compare opinions from both sides just as adeptly is enriching not only intellectually, but socially. Ambidebater, shall we call it? Actually, it\'s just the natural process of learning to argue - I mean, "discuss" - well.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>