<?php

$aid = 'kriti';
$title = 'Sadie\'s: Relief or Stress?';
$cid = c8;
$issueid = i3;
$body = 
'
<p>In honor of the recent, so-called <i><b>day of love</b></i> (February 14th) I thought that this popular debate could focus on the trials and tribulations of young puppy love. (Aw... how sweet)</p>

<p>With the upcoming Harker Sadie\'s dance on March 18th, I think it is essential to find out what you think about it.</p>

<p>For those of you unaware of what a Sadie\'s is, it is a chance for a "role reversal" (if you will) where the girl tormented by forsaken love... (or who just needs a date to "fit in") can ask out a wonderful or not-so-wonderful gentlemen to be her date to a dance.</p>

<p>There are many popular unanswered questions: Is it normal for a girl to initiate? Is it more/less stressful to have this opportunity? Is this a pure, inaffective gimmick, or is this a privilege? How do guys feel about this, is it relief or torture?</p>

<p>It is in my experience that most "couples" are generally supportive of this opportunity, because it is a chance for the girl to court or "woo" (I love that word...) the guy and impress him. But what do I know, I\'m just a kid...</p>

<p>As for the single women, there are always mixed answers. There are those who see this as a message from God (or other, non-secular beings) and they feel that this is their time to shine. There are also the not-so-optimistic beings who find this unconventional and useless.</p>

<p>What do you think? Do you think this is a modern age where the girls should initiate as well? Or, do you feel that we should stick to the conventional methods?</p>

<p>Sneha Jain saw this more in the perspective of the guys themselves as she said "we need to give the guys a break for once - [because] I know it\'s definitely not easy asking someone to a dance - it\'s definitely okay for the girls to initiate sadies or not."</p>

<p>An anonymous boy thinks that "it makes it easier for guys... takes a load off my back."</p>

<p>Eugenia Sorotokin says "It\'s okay for girls to ask guys to a dance, Although personally I wouldn\'t do it in any romantic sort of way \'cause it\'s just awkward? As friends though it\'s ok. Nobody really dances with their date [...] unless they\'re going out."</p>

<p>Rohan Mehra says "[Sadie\'s] is a good idea because girls get to experience what guys go through for every other dance."</p>

<p>So, from these opinions it seems that the majority of girls and boys alike see this as a conventional and practical idea. It seems that most people see it more as a relief for the guys rather than a relief for the girls. Then again, the whole notion of seeing as it was put "what guys go through" could suggest that some girls would feel otherwise. Who knows?</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>