<?php

$aid = 'stephanie';
$title = 'Your Local Oasis: Economic Lessons from a Bookworm';
$cid = c7;
$issueid = i3;
$body = 
'
<p>I\'ve discovered the perfect weekend excursion for large families, stressed out adults, and teenagers with no spending money. For no entrance fee, people can spend an entire day using the internet, listening to music, reading comic books and novels, and enjoying the air conditioning.</p>

<p>And of course, this blissful place is none other than your local library. Simply register and a library card means that after enjoying the facilities, you can walk home with books, music selections, videos, DVD\'s, and even software. Even if you\'re not a bookworm (who, by now, should have already discovered the home great literature and the latest works), you can still take advantage of this vast resource. For example, you could opt to get your weekend music and movies from the library rather than renting them. Ask if any programs are offered; often, there are arts and crafts, book readings by authors, free musical and dramatic performances, and other interesting ways to invest your time during school breaks, especially summer.</p>

<p>Even though this article has been written in part out of a wistful longing for the lazy days spent at the library in the summer, there is a sense of tranquility in entering those library doors on a weekend and taking a moment to stop, no matter what season. Last weekend, I visited my local library after having been absent nearly since the commencement of school. I found the books that had been listed on my "to read list" since forever and enjoyed a few cathartic hours reading novels on the squishy couches by the large glass windows. Of course, I then went home to finish piles of homework, but knowledge of my literary treasures awaiting me helped motivate me through my work.</p>

<p>So now, I urge you to take a field trip to your local library. Expand your horizons. And if nothing else, make full use of the resources provided for by your own money. Utilize your tax dollars! That would be the smart thing to do.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>