<?php

$aid = 'emily';
$title = 'A Self-Layout of Oil Pastels and Sketches';
$cid = c5;
$issueid = i3;
$body = 
'
<p>Back by demand, I have decided to submit some more of my own
work. I started as a tiny tyke with my little box of oil pastels and markers
and proceeded into the medium of oil painting. After a hiatus due to an
overload of extracurricular activities, I went back to my art teacher in 2004,
continuing with oil painting and sketch. I recently started with watercolour
and am experimenting with all three mediums. I have loved art all my life and
it has become one of my biggest passions. There\'s just something about art &#8211;
the idea that it can be seen everywhere in different forms and can communicate
and convey so many different messages within just one sketch.</p>
<a href="inc/MSfiles/35/image003.jpg"><img src="inc/MSfiles/35/image004.jpg" /></a><br/>
Copy of Pino\'s <i>Desire</i>: Pencil & Pastel on Paper<br/><br/>
<a href="inc/MSfiles/35/image001.jpg"><img src="inc/MSfiles/35/image002.jpg" /></a><br/>
Still Life - Poinsettas: Watercolour on Paper<br/><br/>
<a href="inc/MSfiles/35/image005.jpg"><img src="inc/MSfiles/35/image006.gif" /></a><br/>
Inspired by Chinese Makeup Ad<br/><br/>
<p>**The thumbnails are linked to larger images.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>