<?php

$aid = 'ruchi';
$title = 'The Secret of the First Charm - Prologue, Chapter 1';
$cid = c1;
$issueid = i3;
$body = 
'
<p> &nbsp; </p>
<h12>Prologue</h12>

<p>When I first got my letter of acceptance to Astra Academy, I wasn\'t all that surprised. After all, Mother had told me about power and had showed me how to use some of it. Admittedly, I wasn\'t very good at it. The few times I had tried to find things, well, let\'s just not go there.</p>

<p>I suppose you are wondering who I am, what I\'m talking about, and why I\'m talking about it. Unfortunately, that\'s a rather difficult question for me to answer. In the history of the world as most people see it, I suppose I\'m a nobody. I\'m not in the textbooks, I\'m not on the web, and, unless you are smart enough to search under \'Christopher Race\' or \'Daniel Raven,\' in the <u>History of Power</u> text they will use at Astra in about ten years, I\'m sure you\'ll never find anything attached to my name.</p>

<p>So then why is the question so difficult, you ask? Hold on, I\'m getting there. See, in the eyes of the two greatest Enchanters of all times, I\'m one of the most important people to walk this earth. Funny, isn\'t it? The greats consider me important while the common people don\'t know I exist.</p>

<p>You understand why the question is so complicated? But I\'m not here to answer questions about myself. After all, I\'m a fifteen year old Enchanter who is attending the aforementioned academy. I\'m not that important in the grand scheme of the world. However, Heather wanted me to write down our adventures and story as Ryan and Carol wrote down theirs. Who\'s Heather, Ryan, or Carol? Maybe I should just tell you the whole story, as I lived it, from the beginning...</p>

<p>In 1985, I, Nicole Athena Raven, was born to Marianne and Daniel Raven, as their first and only child. Ten years later, my father was killed and my mother and I decided to leave the country. There were too many painful memories associated with America, all concerning my dad. My father wasn\'t a normal man, I admit it freely. Through the first five years of my life he was a warm, loving father who would have given the moon to my mother if she had asked. However, a little after I turned five, he turned into a man who didn\'t know he had a daughter or wife. Secretly, my mother and I were both glad of this man\'s death, while we had mourned the loss of my daddy years before.</p>

<p>That\'s when my mother told me about power, and that\'s where this story begins.</p>

<p align="center">----</p>

<h12>Chapter 1: Of Pink Hair and Whizzing Wells</h12>

<p>"Mother, we\'ve got to leave... now!" I yelled up the staircase. A minute later my mom came running down the steps and grabbed the car keys. "Finally," I muttered as we got into the car. Mother rolled her eyes at me as we drove down to the subway station.</p>

<p>"Look, Nicole, there\'s something I need to give you before you leave," she said fifteen minutes later, as we pulled up to the subway station. She sat back in her car and looked at me for a few seconds, tears gathering in her eyes. Reaching into one of her numerous coat pockets, she pulled out a small jewelry box and handed it to me.</p>

<p>"It\'s beautiful," I said after a minute, gaping at the snowflake charm bracelet. It was the most delicate thing I had ever seen in my life, and, as I put it on, I felt tears gather in my eyes as well. "I won\'t ever take it off," I promised before giving my mom, my only living relation, a hug. I still couldn\'t believe I was going to be leaving her.</p>

<p>"Honey, if you don\'t want to go, you can still," she started hesitantly it. Through my tears I choked back a laugh.</p>

<p>"Mother, I\'m going. I need to learn about your world, my world..." I paused for a split second, "and Dad\'s world."

<p>"I know you do," she admitted, sitting back in her seat. Suddenly she shook her head and wiped her tears. "Well, come on then, you don\'t want to miss that subway. The next one heading to Astra leaves in six hours." With a weak grin, she got out of the car and started hauling my suitcases out of the trunk.</p>

<p>It seemed that everyone around us seemed to be going to Astra, as there were only parents and a bunch of kids with suitcases around. To me it was a little odd that no normal people seemed to be coming into the station, but I shrugged it off. As my ticket was being checked, I looked around myself and saw parents hugging their children goodbye and kids, my age and older, loading themselves into subway cars. Mother and I dragged my luggage through the security and finally put it in the subway baggage car. Within thirty minutes, I had left for my new school.</p>

<p>Now, normally I pride myself on being a relatively outgoing person. I\'ve never been one to be afraid of making a fool of myself and as a result I generally was surrounded by lots of people. But, as you can tell, this wasn\'t a normal situation. For about five minutes, I searched for a relatively empty compartment in the car I was in, but found none. The last door I opened revealed six kids though, my age, sitting and laughing with one another. As I was about to close the door in embarrassment, they all looked up.</p>

<p>"Oh, um, sorry," I started before one of the boys, with dark brown hair with eyes to match spoke.</p>

<p>"The name\'s Ray," he said easily. "Are you new to Astra? I haven\'t seen you around before."</p>

<p>"Yeah, I am," I answered, trying to disguise how uncomfortable I was with the door half closing on me. "And my name\'s Nicole."</p>

<p>"I\'m Heather," greeted another girl, Chinese with long black hair. "Why don\'t you come in? The door looks like it\'s squashing you." Gratefully, I left my uncomfortable position, and as the door slammed shut, I sat down.</p>

<p>"This is Melanie, Chris, Dean, and Brianna," Heather said as she pointed to a blond, a boy with black hair and green eyes, another boy with grey eyes, and a brunette with short hair. I figured I wasn\'t going to remember everyone\'s names for more then two or three minutes, but smiled at everyone and shook hands anyway.</p>

<p>"So, you\'re new to Astra," said Dean, leaning back in his seat. "Do you know \'bout power yet?"</p>

<p>"Yeah," I replied, surprised at the question. "Don\'t you have to, to go to the school?"</p>

<p>"Not really," Melanie said. "Two years ago a ton of kids came for middle school and had no clue what power was. It wasn\'t pretty."</p>

<p>"So I\'m guessing you\'re all old to this school," I said, feeling a little left out. These guys would know tons more about power then me.</p>

<p>"Well, I think all of us joined fourth grade except Bri here, who started in seventh," Ray said. "And we\'ve had the same classes for years."</p>

<p>"Not this year," interrupted Melanie. "I\'m taking mostly different classes than you guys, a lot of extra ones. My schedule is different than the rest of the grade."</p>

<p>"Wait, does everyone in our grade have the same classes?" I inquired. After all, I knew there were around a hundred kids per grade. It didn\'t seem natural that you had tons in one class and almost none in another.</p>

<p>"Nah," Ray said easily. "They split us up into twenty groups, and, uh, it\'s complicated. Anyone else want to explain."</p>

<p>"It\'s not really that hard," Dean said after a minute. "The five people per group always have classes together and stuff, they take all the same classes. Then maybe three or four groups of five meet for a class. Sometimes you have the same groups of five in your classes, sometimes not."</p>

<p>"I think I understand," I said. "How do I know what group of five I\'m in though."</p>

<p>Chris snorted disdainfully at me, his eyes glinting, and instantly I felt a dislike towards this boy.</p>

<p>But before I had a chance to talk to ask him what was so funny, the subway train jerked to a stop, throwing the compartment door open and the two of us out of it.</p>
	
<p>I knocked into a body in the hall, and as I picked myself up off the floor, I apologized.</p>

<p>"Watch where you\'re going," Chris snapped in response. "God, what a klutz." I didn\'t hear the teasing note in his voice.</p>

<p>"Excuse me?" I asked, insulted. I didn\'t notice Dean opening the compartment door to see why we hadn\'t come back in, but he was watching, open-mouthed.</p>

<p>"You heard me. Watch where you\'re going. Is that too hard to comprehend?" His eyes were twinkling with mischief, but I was just plain annoyed. Before you jump down on me as a brat, remember I didn\'t know this guy very well, and I thought he was serious.</p>

<p>I think now would be the time to tell you I used to have a pretty short temper. Actually, I still do. It\'s something my mother tried, unsuccessfully, to fix. Generally, though, nothing actually provokes me to lose it. However, whenever I was nervous or unsure of myself, which was pretty rare, I had a hard time controlling it. A really hard time. So, to put it simply, I snapped.</p>

<p>I was aware of my power on the whole, but not completely sure how to use it. I still managed to exact some amount of revenge, however, as suddenly his hair turned pink. Dean quickly muffled a snort of laughter, as the boy was obviously unaware of what happened, and the two us went back into the compartment when he called my name.</p>

<p>"Priceless," he said, still laughing when he sat down. As the others saw Chris, who they were referring to as Race, they started laughing as well.</p>

<p>Suddenly, the humor of the whole situation, especially the pink hair, hit me as well, and the six of us were laughing pretty boisterously until a boy who looked amazingly like Dean opened the door.</p>

<p>"Dean," he said, and then suddenly stopped and shook his head. After a second, Race\'s pink hair turned back to jet black. Race, obviously confused as to what had made as laugh, finally realized what happened and sent me a death glare. "Please don\'t tell me you and Race have started a prank war already."</p>

<p>"James, couldn\'t you have left it for a few hours?" Ray whined. "I mean, I wanted the school to get to see it!"</p>

<p>James, as I correctly guessed his name was, cracked a smile. "I can\'t believe you guys. School hasn\'t even started and you are already trying to outdo each other and I didn\'t even know you knew how to use your power yet."</p>

<p>"We don\'t," said Heather bluntly, looking at his left ear. "Nicole does though."</p>

<p>"Nicole?" James questioned, gazing at Heather as she slowly turned red. It was easy enough to see she liked him, but that wasn\'t my main concern at the moment. James looked directly at me after a second. "You\'re new, right?" At my nod, he looked sarcastically at Heather. "She\'s new and yet you think I\'m going to believe that she knew how to use power?"</p>

<p>"I did," I replied, slightly offended that he didn\'t think I was capable. "Race here was rude, so I turned his hair pink."</p>

<p>"What?" asked Race, annoyed. However, I ignored him. I didn\'t realize it, but I had just made myself a pretty formidable adversary.</p>

<p>James\'s glare zipped back to me before he started laughing. After he had calmed down, he said, almost seriously, "Look, Nicole, you can\'t go around jinxing kids in your class, especially before you even know how to use your power properly."</p>

<p>"Well it worked didn\'t it?" I said cheekily. James was the type of person who made me want to break the rules. He wouldn\'t tell on me, I could see that from his face, and as long as I didn\'t do anything dangerous, he\'d just be exasperated with me.</p>

<p>"It\'s just not a good idea," he insisted. "I mean, what if you had turned his skin pink or something? That would have been a lot harder to fix."</p>

<p>"Actually," I muttered, "that\'s what I was aiming for." I endured James\'s, and Race\'s, glare for less then ten seconds before I gave up. "Fine, I won\'t use power until I learn how to properly," I told him. My fingers were crossed behind my back.</p>

<p>"Good," he said, smiling again. He turned to leave, calling over his shoulder, "By the way, you guys have about two minutes left to get your stuff off the subway, \'cause we\'re here!"</p>

<p>Cursing, the seven of us went running to the luggage car, grabbed our stuff, and jumped off the subway before it went hurtling back to Carlisle. "Welcome to London," said Dean under his breath as we followed the other students up a hill to a well.</p>

<p>I watched in amazement as, in groups of ten, students stepped onto a platform on top of the well. Suddenly, the platform, and the students, were gone and another clear platform took it\'s place. Looking around, I guessed there were about two hundred students there at the moment, and waited quietly in the back of the line with the others for our turn "down" the well. Or wherever the disappearing platform was taking all the students.</p>

<p>As the seven of us, James, and two older students we didn\'t know finally stepped on to the platform, it whizzed downwards in a circle, giving me the horrible sensation that I was going to be sick. After about a minute, we stopped whirring. In front of us, written on an oak wood door, was written the names Heather Lee and Nicole Raven.</p>

<p>"Go on then," said James as the two of us stood dumbfounded and staring at the door. His voice snapped us out of our shock and we picked our suitcases up and walked through the door.</p>

<p>I can\'t tell you what I was expecting, but it definitely wasn\'t what I got. By the looks of it, this room was to be our dorm room for the next four years. There were three beds in the room, each with a different colored comforter and bed sheets. There was an adjacent door to a bathroom, three separate desks, three closets, and, finally, three small lockers.</p>

<p>"I claim the green!" yelled Heather as she dumped her luggage on the floor and jumped onto the bed decked out in green. She sat up with a goofy grin on her face. "This is so much cooler than last year\'s dorms!"</p>

<p>I grinned as well and threw myself on the blue bed. "This is awesome," I agreed. "I mean, I wasn\'t here last year, but I can imagine it\'d be hard to beat all this!"</p>

<p>"I wonder who the third bed is for,"  murmured Heather. "Generally there are only two person dorms, since there are so few kids per grade... well I mean not so few, but there\'s only a hundred, and only fifty are girls... so I mean..."</p>

<p>"Well, I guess we\'ll find out later," I shrugged off. "Anyway, you need to fill me in on a few things."</p>

<p>"Such as?" Heather said lazily, lying back down.</p>

<p>"Why are there lockers at the foot of our beds when we have closets, why is there an intercom, and what time is dinner?" My stomach was rumbling by that time. While I knew it hadn\'t been more than an hour and a half since I left home, travel just has a way of making you ravenous.</p>

<p>Heather laughed before starting to answer a few of the questions. "Well, the lockers are kind of where the stuff we need appears. It sounds weird to explain but if a teacher assigns you something, the homework will appear in  there... and if you get a detention or something, that\'s where you\'ll find the notice. It\'s like a mailbox."</p>
<p>"And the intercom?"</p>

<p>"Announcements and stuff. For example, if there\'s a meeting or something that we have to attend, it\'ll come over the intercom."</p>

<p>"Sounds cool," I said, my American heritage showing itself in excitement. Heather raised herself up on her elbows again and looked at me curiously.</p>

<p>"You know, you sound rather funny. You did in the subway too. Are you American or something?"</p>

<p>I blushed. "Kind of. I was born in America, brought up in England... well for the last five years. It\'s really complicated."</p>

<p>Heather and I had a good time talking for the next half hour or so, before a voice came on the intercom telling us lunch had begun. While I admit I don\'t really remember what we had for the meal, I do remember that no third roommate ever showed up.</p>

<p>Before dinner there was supposed to be a meeting of the whole school, as everyone should have arrived on the second subway, and Heather and I headed down excitedly. I was happy to have made such a good friend so quickly, and had actually forgotten the existence of the boys I had met earlier. Heather and I hadn\'t eaten with them and the two of us had been inseparable.</p>

<p>However, I was reminded of their presence during dinner, when Ray and Dean sat down directly across from us and started shoveling food into their mouths. Being the oh-so-refined young lady I was, I stared at them in disgust before a rather loud "ew!" left my mouth.</p>

<p>"What?" Ray asked, his mouth filled with a biscuit and gravy. Heather looked at him in disgust.</p>

<p>"You two are barbarians, I swear," I said, laughing. "I mean, look at the way you eat."</p>

<p>"And such atrocious manners," came a mocking voice from behind us. Dean and Ray cracked up, as did Heather. "After all, I\'m Little Miss Perfect who-"</p>

<p>Turning around, my glare effectively cut Race off. He was still irritated for me calling him rude on the subway, and then ignoring him. Oh yes, and turning his hair that beautiful shade of pink. I was still irritated for him being rude and for, well, I don\'t know, but something about him really annoyed me, and sometimes still does.</p>

<p>"Afraid of your getting in trouble?" Race asked, raising an eyebrow. "Well, well, well, I wouldn\'t have thought that little Nicole Raven here actually completely followed the rules."</p>

<p>Needless to say, Race didn\'t get away with that. I turned his hair a bright pink as I leaped at him, stupidly thinking that a five-foot \'munchkin\' could do damage to his five foot ten inch body. Let me tell you now - he\'s still growing. At the moment, he\'s at least six foot. Anyway, at the time, to save myself humiliation, I\'ll just tell you that he grabbed my wrists and I was pretty much helpless.</p>

<p>I don\'t think I understood quite how powerful he was for another few months, but I realized then and there that there that most people wouldn\'t be able to mess with him. I couldn\'t get myself out of his grip, and he was just sitting there rather lazily. And I\'m pretty strong for a girl, I think. I mean, I was thrashing around like crazy, but he was strong.</p>

<p>In the end, Heather was the only one smart enough to save me from getting into a ton of trouble. Note, I said me. Race got detention for two days, for, um, abusing a new student, while I was simply an innocent victim. Innocent my... well, this is a G-rated story.</p>

<p>After everyone had finished eating, a hologram appeared in the center of the cafeteria. Now, I\'m sure that this is going to take all of you by shock, as it surprised me to no extent. I mean, hello, we\'re going to a school based on power and you give us a hologram? This was a powerful one, though I didn\'t realize it for a long time. See, wherever you were sitting, it seemed the teacher was talking directly to you. Well, not teacher. Ms. Ursa was the Head of Astra.</p>

<p>"Welcome, the old, the new, and the staff. Welcome to a new school year fraught with new teachers and new challenges. New classes, new adventures, and, god forbid, new troublemakers. However, that is all besides the point. I\'m just here to welcome you in general to a new school year. We hope to cultivate your power to the best of your abilities, to allow you to make your lives easier with a simple thought, and to be able to improve the world with effortlessness. Not only our world, but the other world too.</p>

<p>"Before you all get bored with me and doze off, I\'d just like to give a warning this year that any more attempted fist fights at dinner will result in six weeks\' worth of detention. And next time the \'bystanders\' and \'victims\' won\'t be let off either. Please restrain all fights, but if you must have them, do power based ones. Thank you and have a great year."</p>

<p>The hologram had disappeared and I had gotten up, severely embarrassed, when suddenly, with a pop, it reappeared.</p>

<p>"I forgot to mention, classes start at eight tomorrow morning, you\'re stuff is in your lockers, don\'t be late!" Again, there was a pop and the hologram was gone.</p>

<p>I remember leaving the hall that day ashamed yet intensely satisfied. While Race was physically fine, his hair still had a slight pink tinge to it.</p>';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>