<?php

$aid = 'ruchi';
$title = 'JCL Club Review #2';
$cid = c7;
$issueid = i3;
$body = 
'
<p>JCL. The Junior Classical League. Latin Club. To most people, these three monikers refer to the same thing. However, only two of these are the same - JCL and Junior Classical League. Latin Club? Eh. Nah, Latin Club is for those people who only take Latin and delight in the language. JCL is for the kids who are interested in the people behind the language. The great works of the Greeks and Romans - the battles of Troy, the Roman Empire, Alexander the Great, and many other famous people.</p>
<p>Of course, that\'s not all JCL does. Sure, we love the mythology. We love the history. But we also love the languages - I admit it, a large part of JCL is Latin or Greek. But it\'s not pure vocabulary and grammar. It\'s a lot of idioms too - for example, did you know "quid pro quo" is Latin? Or that half the law and medical terms are all ones used in ancient times?</p>
<p>And then there\'s the conventions. Cheering like crazy, running to win the marathon, fighting people in gladiator, playing certamen (a buzzer-trivia game) - these are all exciting thing the JCLers do. We have fun - more than many other clubs out there.</p>
<p>Maybe we aren\'t as widespread as other clubs, but we sure aren\'t just "Latin Club." We\'re infinitely cooler than that.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>