<?php

$aid = 'shan';
$title = 'Let\'s Speak Meat - A Blood for Blood Horror Story';
$cid = c8;
$issueid = i3;
$body = 
'
<p>Picture this scenario: you\'re sitting down to a delicious steak dinner with a large appetite and a watering mouth, when you\'re annoyingly perfect friend decides it happens to be a perfect time to lecture you on the evils of eating meat. Has this ever happened to you? If it has, pour gravy on their head, because they deserve it for being a pompous know it all.</p>
<p>However, when you\'ve satisfied your lust for his blood, give some serious thought to the possibility of turning away from the tempting calls of beef, chicken, and other meat.</p>
<p>Now before you turn your pitchforks in my direction, take some time to listen to why it\'s a good idea to become, yes I\'ll say it, a vegetarian. No, I don\'t believe the crap I hear about animals\' feelings and how it\'s morally wrong. Let\'s face it; besides the milk and eggs, there really isn\'t any purpose for all livestock. Think about it, what good does a pig do? Do you even have an answer? I\'ll bet not. It\'s easy to see why people turned to the solution of eating the animals in the first place.</p>
<p>So, why should you turn into a vegetarian? Is it because of religion? Because cows are sacred? Um, noooo. I\'m very proud of what Hindus have accomplished, but I seriously don\'t know what went wrong when they were picking sacred animals. I mean, come on, why can\'t the tiger be our sacred animal?</p>
<p>So if it isn\'t because of morals or religion, why should you be a vegetarian? Well, I\'ve had to go through some rough times because of some health problems lately. While I was in the hospital, the doctors told me some health reasons for staying a vegetarian. While it may taste good, and gives you protein and energy, meat contains 10 times the bacteria and disease that all non-meat products do. Normally it doesn\'t matter for most people, because they\'re healthy enough to fight everything off, and pull through without noticing any problems. However, the bacterium kills off a good number of white blood cells in the process, and it takes time to replenish your body\'s supply.</p> 
<p>What this means is, for a person that is vegetarian, his or her body will generally have a higher store of white blood cells than a non-vegetarian. Granted, for people with high activity lives, being vegetarian may not give them enough energy. But when you all get older, it\'s a lot harder to replenish your white blood cells than it used to be, and you won\'t have a reserve supply to count on. So it\'s feasible to think that people who are devout vegetarians can easily live to 100+ years with a little luck, because they\'ll be able to fight off most sicknesses with out too much trouble.</p>
<p>So the next time you get a craving to eat a burger or some other meaty substance, weigh your options, because you might regret it later on in life. 
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>