<?php

$aid = 'ruchi';
$title = 'Marvin the Mole and the Ugly Troll';
$cid = c3;
$issueid = i3;
$body = 
'
<p>There once was Marvin, he was a mole<br/>
And a chemistry buff, it\'s true.<br/>
He walked under a bridge belonging to a troll<br/>
And was threatened with death by a shoe.<br/>
<br/>
"You fiend!" yelled the troll. "Get away from my spot<br/>
Or with a shoe I will hurt you!"<br/>
Marvin the mole was shocked at being caught<br/>
And replied, "Oh no! Whatever shall I do!"<br/>
<br/>
"If you want to leave," the troll growled,<br/>
"You must answer my query."<br/>
"Oh, I will do whatever you say!" Marvin howled,<br/>
"\'Cause you are awfully scary!"<br/>
<br/>
"Suffer or give me Boyle\'s law,"<br/>
The ugly creature demanded.<br/>
"V is inversely proportional to P," said Marvin in awe.<br/>
"Ha! I knew that! Soon I won\'t be, with you, stuck and stranded!"<br/>
<br/>
"Now you must tell me what Avogadro said<br/>
Before you can go!" the troll, smirking, insisted.<br/>
"Pfft, V is proportional to n, I could say that in bed!"<br/>
Marvin exclaimed, his mood now uplifted.<br/>
<br/>
"One last question, then you are free,<br/>
What is the law of Charles and Gay Lussac?"<br/>
"V is proportional to T, that\'s easy!"<br/>
Marvin exclaimed before smirking back.<br/>
<br/>
"Gah! You may leave, but don\'t come back!"<br/>
The troll threatened with rage.<br/>
"I won\'t, don\'t worry, next time I\'ll take a different track!"<br/>
Marvin replied, escaping the deadly bridge of a cage.<br/>
<br/>
That was the story of a Marvin the Mole<br/>
A chemistry buff, it is true,<br/>
Who walked under the bridge where there lived a troll<br/>
And was threatened to death by a shoe.<br/>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>