<?php

$aid = 'ruchi';
$title = 'A Compilation of Today\'s Musical Favorites';
$cid = c13;
$issueid = i3;
$body = 
'
<p>People\'s music tastes change over time - as kids, there\'s Disney songs (although I know many teens, myself included, who still occasionally love a <u>Beauty and the Beast</u> or <u>The Lion King</u> song), as teens there\'s metal, rock, soul, rap, and country, and for the ancient folks (otherwise known as "parents"), there is, well, everything that the kids of the next generation consider "old." Out of all these groups, the teenagers are by far the most "modern."</p>
<p>What exactly do I mean by modern? Over the past week, I collected eighty people\'s favorite songs (all these people were between the ages of 13-18).  I wasn\'t too surprised to discover that many people answered my question with the top 100 songs of the week. However, the range varied to include Backstreet Boys, U2, and the Eagles. There were some older hits, including Green Day, Celine Dion, and Christina Aguilera.</p>
<p>Without futher delay, here are the "favorite" songs represented by many of you readers.</p>

<h12>MOST POPULAR:</h12><br/>
<i>(These were the songs that were listed the most from all the people I asked.)</i><br/>
<b>You and Me</b> by Lifehouse<br/>
<b>Collide</b> by Howie Day<br/>
<br/>
<h12>WEEKLY TOP 100 SONGS:</h12><br/>
<i>(These were the songs that were listed by people as favorites and also hit the top 100 in the music charts.)</i><br/>
<b>Talk</b> - Coldplay - Number 2<br/>
<b>Check On It</b> - Beyonce - Number 3<br/>
<b>Be Without You</b> - Mary J. Blige - Number 6<br/>
<b>Dance, Dance</b> - Fall Out Boy - Number 7<br/>
<b>Stickwitu</b> - The Pussycat Dolls - Number 8<br/>
<b>Unwritten</b> - Natasha Bedingfield - Number 11<br/>
<b>Sugar, We’re Going Down</b> - Fall Out Boy - Number 15<br/>
<b>Pump It</b> - The Black Eyed Peas - Number 16<br/>
<b>So Sick</b> - Ne-Yo - Number 17<br/>
<b>L.O.V.E.</b> - Ashlee Simpson - Number 29<br/>
<b>Soul Meets Body</b> - Death Cab for Cutie - Number 34<br/>
<b>My Humps</b> - The Black Eyed Peas - Number 83<br/>
<b>Bad Day</b> - Daniel Powter - Number 85<br/>
<b>4Ever</b> - The Veronicas - Number 110<br/>
<br/>
<h12>OLDIES:</h12><br/>
<i>(These are the songs that we\'ve know forever... and yet we love them.)</i><br/>
<b>Sometimes You Can\'t Make It On Your Own</b> - U2<br/>
<b>City of Blinding Lights</b> - U2<br/>
<b>With or Without You</b> - U2<br/>
<b>Miracle Drug</b> - U2<br/>
<b>Hotel California</b> - The Eagles<br/>
<b>I Love Rock\'N\'Roll</b> - Joan Jette<br/>
<b>Misery</b> - Beatles<br/>
<br/>
<h12>TODAY\'S BIG ARTISTS:</h12><br/>
<i>(These songs may not be big right now, but the artists certainly are. These, according to the people who submitted them, are or should be old chartbusters.)</i><br/>
<b>Good Riddance</b> - Green Day<br/>
<b>Backstreets Back</b> - Backstreet Boys<br/>
<b>Eulogy</b> - Tool<br/>
<b>First Date</b> - Blink 182<br/>
<b>Tears and Rain</b> - James Blunt<br/>
<b>Presidential Remix</b> - Youngbloodz feat. Akon<br/>
<b>Infatuation</b> - Christina Aguilera<br/>
<b>Miss Independent</b> - Kelly Clarkson<br/>
<b>Behind These Hazel Eyes</b> - Kelly Clarkson<br/>
<b>Be My Escape</b> - Reliant K<br/>
<b>Who I am, I Hate Who I\'ve Been</b> - Reliant K<br/>
<b>Swing, Swing</b> - All American Rejects<br/>
<b>My Heart Will Go On</b> - Celine Dion<br/>
<b>Meteora (album)</b> - Linkin Park<br/>
<b>Numb</b> - Linkin Park<br/>
<b>Hummer</b> - Smashing Pumpkins<br/>
<b>Here Is No Why</b> - Smashing Pumpkins<br/>
<b>Drops of Jupiter</b> - Train<br/>
<b>Sunday Morning</b> - Maroon 5<br/>
<b>Teenage Dirtbag</b> - Wheatus<br/>
<b>Title and Registration</b> - Death Cab For Cutie<br/>
<b>So Lonely</b> - Mariah Carey Feat. Twista<br/>
<b>Diamonds are Forever</b> - Kanye West Feat. Jay Z<br/>
<b>99 Problems</b> - Jay Z<br/>
<b>I Need A Girl P.2</b> - P.Diddy, Mario, etc.<br/>
<b>Black Balloon</b> - Goo Goo Dolls<br/>
<b>Just the Girl</b> - The Click Five<br/>
<b>White Tee</b> - Dem Franchize Boyz<br/>
<b>Flake</b> - Jack Johnson<br/>
<b>Better Together</b> - Jack Johnson<br/>
<b>The Quiet Things That No One Ever Knows</b> - Brand New<br/>
<b>Remember the Name</b> - Fort Minor<br/>
<b>Crash and Burn</b> - Savage Garden<br/>
<b>Still Loving You</b> - Scorpions<br/>
<b>The Only One for Me</b> - Brian McKnight<br/>
<b>How to Deal</b> - Frankie J<br/>
<b>There it Go</b> - Juelz Santana<br/>
<b>Movement of Hand</b> - Bright Eyes<br/>
<b>Unbreak My Heart</b> - Toni Baxton<br/>
<b>Dear Jamie...Sincerely Me</b> - HelloGoodbye<br/>
<b>Fallen</b> - Mya<br/>
<b>99 Red Balloons</b> - Nena<br/>
<b>Halo</b> - Bethany Joy Lenz<br/>
<br/>
<h12>SOUND TRACKS:</h12><br/>
<i>(People often told me "I don\'t have a favorite song - I love these soundtracks... here they are.)</i><br/>
Rent<br/>
Chicago<br/>
Phantom of the Opera<br/>
<br/>
<h12>REMAINING SONGS:</h12><br/>
<i>(To be totally honest, I didn\'t know where to put these songs... so here they are!)</i><br/>
<b>Leave</b> - R.E.M.<br/>
<b>Bure Bure</b> - Persian Song<br/>
<b>Breathe Me</b> - Sia<br/>
<b>Boats And Birds</b> - Gregory And the Hawk<br/>
<b>Cage</b> - Dir En Gray<br/>
<b>Killing me</b> - l\'arc-en-ciel<br/>
<b>New World</b> - l\'arc-en-ciel<br/>
<b>Shallow Sleep</b> - Hyde<br/>
<b>Evergreen</b> - Hyde<br/>
<b>Never Been In Love</b> - Talib Kweli<br/>
<b>Go</b> - Common<br/>
<b>Glass In The Trees</b> - Dead Poetic<br/>
<b>Boy Brushed Red Living In Black and White</b> - Underoath<br/>
<b>Shadowland</b> - Heather Hedley<br/>
<b>Swing Life Away</b> - Rise Against<br/>
<b>This Years Love</b> - David Grey<br/>
<b>The Only Difference Between Martyrdom and Suicide is Press Coverage</b> - Panic at the Disco<br/>
<b>How Good It Can Be</b> - The 88<br/>
<b>Ain\'t No Sunshine</b> - Bill Withers<br/>
<b>The L.A. Song</b> - Dave Barnes<br/>
<b>3 Libras</b> - A Perfect Circle<br/>
<b>What I Got</b> - Sublime<br/>
<b>Westside Story</b> - The Game<br/>
<b>Okkervil River</b> - Black<br/>
<b>Andrew Birds</b> - Fake Palindrome<br/>
<b>Yeah Yeah Yeahs</b> - Y Control<br/>
<b>Eye of the Tiger</b> - Europe<br/>
<b>Final Countdown</b> - Survivor<br/>
<b>The Very Thought of You</b> - Nat King Cole<br/>
<b>Run Girl</b> - David Banner<br/>

<p>And that, folks, is the list of the songs that I compiled from your contributions. I doubt any of you has heard all of them (though if you have, major props. You\'re a true music buff.) I myself found this list pretty nice - it\'s relatively concise and covers most of the major music of today (and back in the day).</p>
<p>Thanks to everyone who contributed their favorite song!</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>