<?php

$aid = 'ruchi';
$title = 'Jokes, Jokes, and More Jokes!';
$cid = c4;
$issueid = i3;
$body = 
'
These quotes, jokes, and riddles were all taken from:<br/>
<a href="http://www.aboutteens.org/humor.htm">http://www.aboutteens.org/humor.htm</a><br/>
<br/>
My girl and I were playing Trivia for Dummies when she amazed
me by answering correctly that there are seven rays on the crown of the
Statue of Liberty. "How in the world did you know that?" I asked.
Rolling her eyes, she answered, "Duuuhh... the seven original colonies!"<br/>
--submitted by Cimino809<br/>
<br/>
Two teens were walking home from church after hearing a strong
preaching on the devil. One said to the other, "What do you think about all this Satan stuff?" The other boy replied, "Well, you know how Santa Claus turned out. It\'s probably just your Dad."<br/>
--submitted by Dr. Jim<br/>
<br/>
"New Rule: Girls, leave your eyebrows alone. Here\'s how much
boys care about your eyebrows: do you have two of them? Okay, we\'re done."
--Geo Carlin<br/>
<br/>
"Boys, avoid arguments with your sister about lifting the toilet
seat by simply using the sink."<br/>
<br/>
"I\'ve never worried about fame or fortune or power or wealth. As long as I have just the simple things in life. Like sitting in front of the fireplace with a copy of <u>War And Peace</u>. You know, a book like that will feed a fire for half an hour."<br/>
--Emo Phillips in Details Magazine<br/>
<br/>
<h12>Things My Mother Taught Me:</h12><br/>
My mom taught me about time travel... "If you don\'t behave, I\'ll knock you into
next thursday."<br/>
--submitted by hrdhardrock02<br/>
<br/>
<br/>
<h12>More Things My My Mother Taught Me:</h12><br/>
1.My Mother taught me about ANTICIPATION..."Just wait until your
father gets home."<br/>
2.My Mother taught me about RECEIVING... "You are going to get
it when we get home!"<br/>
3.My Mother taught me to MEET A CHALLENGE... "What were you
thinking? Answer me when I talk to you ... Don\'t talk back to me!"<br/>
4.My Mother taught me LOGIC..."If you fall out off that swing and
break your neck, you\'re not going to the store with me.<br/>
5.My Mother taught me MEDICAL SCIENCE... "If you don\'t stop
crossing your eyes, they are going to freeze that way."<br/>
6.My Mother taught me to THINK AHEAD... "If you don\'t pass your
spelling test, you\'ll never get a good job."<br/>
7.My Mother taught me ESP..."Put your sweater on; don\'t you think
I know when you\'re cold?"<br/>
8.My Mother taught me HUMOR... "When that lawn mower cuts
off your toes, don\'t come running to me."<br/>
9.My Mother taught me how to BECOME AN ADULT... "If you don\'t
eat your vegetables, you\'ll never grow up."<br/>
10.My Mother taught me about SEX... "How do you think you got here?"<br/>
11.My Mother taught me about GENETICS... "You\'re just like your father."<br/>
12.My Mother taught me about my ROOTS... "Do you think you were
born in a barn?"<br/>
13.My Mother taught me about WISDOM OF AGE... "When you get
to be my age, you will understand."<br/>
14.And my all time favorite... JUSTICE... "One day you\'ll have kids, and
I hope they turn out just like you... Then you\'ll see what its like."<br/>
--from <a href="http://www.jokeseveryday.com">jokeseveryday.com</a></p>';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>