<?php

$aid = 'sharon';
$title = 'Do You Believe?';
$cid = c3;
$issueid = i3;
$body = 
'
<p>Do you believe in pigs that fly?<br/>
Do you believe in fate?<br/>
Do you think that life\'s passing by?<br/>
That our paths are never straight?<br/>
<br/>
I believe in anything<br/>
Than the impossible is not so<br/>
I believe in the surprises life brings<br/>
I believe that goodness can grow<br/>
<br/>
So I believe that this can be done<br/>
And I won\'t show dismay<br/>
Because, Teacher, class has just begun<br/>
And I will pass this test today.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>