<?php

$aid = 'sharon';
$title = 'Eulogy for Doubt';
$cid = c3;
$issueid = i3;
$body = 
'
<p>My friends, we gather here today<br/>
To celebrate<br/>
Doubt\'s passing away<br/>
<br/>
Doubt left terrible things in his wake<br/>
Like failure and worry, prejudice and dismay<br/>
But they too are buried with Doubt today<br/>
<br/>
Doubt is survived by<br/>
Self-Esteem and Acceptance<br/>
Hope and Love<br/>
Satisfaction and Success,<br/>
And various pleasant relations thereof.<br/>
<br/>
So Doubt, may you rest and never plague us again.<br/>
<br/>
<i>Amen.</i></p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>