<?php

$aid = 'sharon';
$title = 'Oh Socks, How I Love You';
$cid = c3;
$issueid = i3;
$body = 
'
<p>If you want to know happiness, look at my socks<br/>
They seem to get along fine<br/>
Their relationships run on no snags and no rocks<br/>
Socks never fight and socks never whine<br/>
<br/>
People never agree, oh no<br/>
They have arguments and they always fight<br/>
But socks, you see their little patterns aglow<br/>
With happiness and knitted delight<br/>
<br/>
Socks don\'t care about orientation or race<br/>
Left socks fit right feet<br/>
Black socks and white socks willingly embrace<br/>
Whenever they happen to meet<br/>
<br/>
People should observe how their socks behave<br/>
Then we sure would get along<br/>
You don\'t need to be bold, don\'t need to be brave<br/>
\'Cause socks never do anything wrong.<br/>
<br/>
Oh socks, how I love you.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>