<?php

$aid = 'sharon';
$title = 'The Miseries of Life';
$cid = c3;
$issueid = i3;
$body = 
'
<p>I still remember my friends from first grade<br/>
It seems like yesterday we fought over the swings<br/>
I remember the foolish promises we made<br/>
Sharing, loving, other silly things<br/>
<br/>
Remember the quiet girl who sat in the back?<br/>
The one who was too scared to go down the slide?<br/>
I heard her grandma got a heart attack<br/>
And then she committed suicide<br/>
<br/>
As for the boy who was always too loud<br/>
And did things that were really gross<br/>
He started to hang out with the wrong crowd<br/>
And died of a drug overdose<br/>
<br/>
Remember that plump girl, was it Marybeth?<br/>
I heard she starved herself to death<br/>
And the girl with the bows in her hair-<br/>
I saw her yesterday in maternity wear<br/>
<br/>
The boy who passed out the candy corn-<br/>
Arrested for buying and distributing porn<br/>
And the boy who made me cry when he called me a dolt<br/>
He got imprisoned for battery and assault<br/>
<br/>
So we survivors face the future, deserted and alone<br/>
We were the brightest, we were the blessed<br/>
Our past now left under one gravestone<br/>
And I wonder if misfortune will claim me next.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>