<?php

$aid = 'neil';
$title = 'Why Did the Chicken Cross the Road?';
$cid = c4;
$issueid = i3;
$body = 
'
<p>Since the beginning of time, people have wondered about the chicken\'s motives for crossing the road, but to this day, we have not managed to come to an agreement on the answer. Well, I decided to do some research and discover the real reason behind the chicken\'s seemingly irrational decision to journey to the other side.</p>

<p>So why did the chicken cross the road? Well, according to...<br/><br/>

<b>George Bush:</b> We don\'t really care why the chicken crossed the road. We just want to know if the chicken is on our side of the road or not. The chicken is either with us or it is against us. There is no middle ground here.<br/><br/>

<b>John Kerry:</b> While serving in Vietnam, I was in favor of the chicken crossing the road. Then later I realized that there were those who needed the chicken on this side of the road. Now I would like to see the chicken on the other side of the road, unless of course it would be better served to be on this side of the road. Ideally, I think the chicken should be in the middle of the road.<br/><br/>

<b>Bill Gates:</b> I have just released eChicken 2004, which will not only cross roads, but will lay eggs, file your important documents, and balance your chequebook and Internet Explorer is an inextricable part of eChicken.<br/><br/>

<b>Martha Stewart:</b> No one called to warn me which way that chicken was going. I had a standing order at the farmer\'s market to sell my eggs when the price dropped to a certain level. No little bird gave me any insider information.<br/><br/>

<b>Dr. Seus:</b> Did the chicken cross the road?<br/>
Did he cross it with a toad?<br/>
Yes, the chicken crossed the road,<br/>
But why it crossed, I\'ve not been told!<br/><br/>

<b>Ernest Hemingway:</b> To die. In the rain. Alone.<br/><br/>

<b>Martin Luther King Jr:</b> I envision a world where all chickens will be free to cross roads without having their motives called into question.<br/><br/>

<b>Our Grandparents:</b> In my day, we didn\'t ask why the chicken crossed the road. Someone told us that the chicken crossed the road, and that was good enough for us.<br/><br/>

<b>Barbara Walters:</b> Isn\'t that interesting? In a few moments we will be listening to the chicken tell, for the first time, the heart-warming story of how it experienced a serious case of molting and went on to accomplish its life-long dream of crossing the road.<br/><br/>

<b>Ralph Nader:</b> The chicken\'s habitat on the original side of the road had been polluted by unchecked industrialist greed. The chicken did not reach the unspoiled habitat on other side of the road because it was crushed by the wheels of a gas-guzzling SUV.<br/><br/>

<b>Jerry Seinfield:</b> Why does anyone cross a road? I mean, why doesn\'t anyone ever think to ask, "What the heck was this chicken doing walking around all over the place anyway?"<br/><br/>

<b>Pat Buchanan:</b> To steal a job from a decent, hard-working American.<br/><br/>

<b>Jerry Falwell:</b> Because the chicken was gay! Isn\'t it obvious? Can\'t you people see the plain truth in front of your face? The chicken was going to the "other side." That\'s what they call it -- the other side. Yes, my friends, that chicken is gay. And, if you eat that chicken, you will become gay too. I say we boycott all chickens until we sort out this abomination that the liberal media whitewashes with seemingly harmless phrases like "the other side.".<br/><br/>

<b>John Lennon:</b> Imagine all the chickens crossing roads in peace.<br/><br/>

<b>Aristotle:</b> It is the nature of chickens to cross the road.<br/><br/>

<b>Saddam Hussein:</b> This was an unprovoked act of rebellion and we were quite justified in dropping 50 tons of nerve gas on it.<br/><br/>

<b>Captain Kirk:</b> To boldly go where no chicken has gone before.<br/><br/>

<b>Bill Clinton:</b> I did not cross the road with THAT chicken. What do you mean by chicken? Could you define chicken, please?<br/><br/>

<b>The Bible:</b> And God came down from the heavens, and He said unto the chicken, "Thou shalt cross the road." And the chicken crossed the road, and there was much rejoicing.<br/><br/>

<b>Albert Einstein:</b> Did the chicken really cross the road or did the road move beneath the chicken?<br/><br/>

<b>Sigmund Freud:</b> The fact that you are at all concerned that the chicken crossed the road reveals your underlying sexual insecurity.<br/><br/>

<b>L.A.P.D.:</b> Give me ten minutes with the chicken and I\'ll find out.<br/><br/>

<b>Richard Nixon:</b> The chicken did not cross the road. I repeat, the chicken did not cross the road.<br/><br/>

<b>Buddha:</b> If you ask this question, you deny your own chicken nature.<br/><br/>

<b>Joseph Stalin:</b> I don\'t care. Catch it. I need its eggs to make my omelet.<br/><br/>

<b>Louis Farrakhan:</b> The road, you will see, represents the black man. 
The chicken crossed the "black man" in order to trample him and keep him down.<br/><br/>

<b>Steve Jobs:</b> Because of the brand-new iChicken- a portable device that crosses roads, lays eggs, gives wakeup calls and provides dinner, automatically. This amazing device can simply plug in to the $4000 iCoop to produce additional iChickens and recharge existing iChickens, or plug it into the $9000 iChop to convert iChicken files into iFood. iFood-to-Regular Food converters sell for an additional $50/month fee, however the optional iFood-to-FoodXP converter is still in development. iChickens are only available from authorized iDealers, which can be found in nearly every US state. If your iChicken develops a disease or stops working, you must send it by FedEx Overnight to Littleton, Montana and our iTechnicians will send you a replacement within 3 months. The iChicken. Wow.<br/><br/>

<b>The Pope:</b> That is only for God to know.<br/><br/>

<b>Emily Dickenson:</b> Because it could not stop for death.<br/><br/>

<b>O.J. Simpson:</b> It didn\'t. I was playing golf with it at the time.<br/><br/>
<br/>
<p>So why do you think the chicken crossed the road?</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>