<?php

$aid = 'ruchi';
$title = 'My Pot of Gold';
$cid = c1;
$issueid = i3;
$body = 
'
<p>As a little kid, I loved the idea of leprechauns. I don\'t know what it was, but the idea of a pot of gold at the end of a rainbow revealed to me by a little guy in all green with a four leaf clover really appealed to me. Maybe it was my overactive imagination or just my inclination towards the fantastic, but when March rolled around, I was always delighted.</p>
<p>In kindergarten, my dreams came true. It was St. Patrick\'s day and I was (very excitedly) telling my mom that I was going to wear green so that I wouldn\'t get pinched. I hopped into the car and endured the three minute ride to school in unbearable excitement - excuse me, but I was going to go see if the other kids remembered that today I just might get to see a leprechaun.</p>
<p>Well, they all did. I know, it\'s sad, I wasn\'t the only child completely excited about the day of the Irish, but not everything in life is perfect. Anyway, I was sitting in the kindergarten playground with my friend Shelley, and we were excitedly discussing how we were going to find our own pot of gold when my kindergarten teacher opened her classroom door and yelled that we had a leprechaun in the room.</p>
<p>I was so incredibly excited as I jumped off the slide and dashed into the classroom (honestly, I don\'t think I ever ran that fast again). As I entered the room, I was shocked to see the chairs turned over and green paint handprints all over the wall. And when I say all over, I mean all over - there wasn\'t more than six square inches of clean classroom. Naturally, my kindergarten self was hyped up and I looked around, trying to spot the mischief maker.</p>
<p>"Aw, you missed him you guys. Next time come faster," my teacher said. At that moment, my heart broke. I had missed my one chance to see a leprechaun.</p>
<p>"B-b-but I ran so fast," a girl beside me started sniffling. I guess I wasn\'t the only one with dreams to see (and catch) a leprechaun.</p>
<p>"They\'re magical," another boy said knowledgably. "I bet they disappeared the moment they heard us."</p>
<p>"Well, they still left you a treat," my teacher said. Smiling at our naivety (or maybe we just looked hilarious seeking leprechauns), she informed us that the leprechaun had left us a pot of gold somewhere in the room. Immediately, fifteen hyper six year olds tore the already-wrecked room apart to find our gold.</p>
<p>Two minutes later, a large cauldron (the type people put Halloween candy in) was unearthed, filled with golden chocolate coins and fools\' gold rocks. Being the little kids we were, we screeched in delight and fought over who got the chocolate and the pretty, sparkling stones.</p>
<p>After I had gotten (more than) my share of candy and "gold" I retired to the back of the classroom to study the handprints. After all, it was my dream to catch a leprechaun and get my own pot of gold.</p>
<p>"This is so cool," Shelley said, standing beside me. "I can\'t believe we almost saw a leprechaun."</p>
<p>"Yeah, I know," I said, grinning at her. "Just wait, next year, I\'m gonna sneak up on one and catch it."</p>
<p>"Me too," she proclaimed. We laughed in delight at our idea and settled down for story time. I vowed to myself that sometime, before I got old, I would catch a leprechaun.</p>
<p>As you can guess, I never really caught one. But I don\'t think I need one, not anymore - I already got my pot of gold at the end of the rainbow.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>