<?php

$aid = 'ruchi';
$title = 'Illusion';
$cid = c3;
$issueid = i4;
$body = 
'
<p>From the time I was a little girl<br/>
I was told it was only inside that truly mattered.<br/>
As I grew older and discovered this world<br/>
That precious illusion was cracked and shattered.<br/>
<br/>
In our imperfect world people are always seeking-<br/>
We all know that they aren\'t looking at the soul.<br/>
It\'s all about persuasive speaking,<br/>
It\'s about the money, the power, the control.<br/>
<br/>
I\'m just one person out of many long lists<br/>
These are only words - not action<br/>
I know that while this system exists<br/>
I\'m never going to have satisfaction.<br/>
<br/>
Maybe this generation can start anew,<br/>
I want to fix this world.<br/>
Until we fight the system as a group,<br/>
I\'m just a disillusioned little girl.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>