<?php

$aid = 'editors';
$title = 'Editor\'s Note: Issue 2';
$cid = c19;
$issueid = i2;
$body = 
'
<p>Hey everyone!</p>
<p>I hope, for all of you that read it, you enjoyed Issue 1 of Amalgam. Now Issue 2 is released! Hopefully, you all will enjoy this just as much, if not more, than our previous issues. We have some fantastic stuff, from Natasha Wu\'s "Bottles and a Butterfly" to Natalie So\'s "Focus on a Designer: Stella McCartney."</p>
<p>From this month on, we\'re accepting student submissions. If you have something you wrote or drew, on any pretty much any topic, send it in to <a href="mailto:highschoolmagazine@gmail.com">highschoolmagazine@gmail.com</a>. Amalgam is "For the Teens, by the Teens," and we\'d like to keep that up.</p>
<p>Once again, I hope you enjoy reading this!</p>';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>