<?php

$aid = 'editors';
$title = 'Editor\'s Note: Issue 3';
$cid = c19;
$issueid = i3;
$body = 
'
<p>Dear Reader,</p>

<p>Welcome to the third issue of Amalgam Magazine!</p>
<p>As you have probably noticed, we now have a new layout, props to the webmaster, Neil Gupta. However, the looks of the website are not the only things changing. We have also added a subscription box - that\'s right! Enter your email and receive an issue of Amalgam in your inbox every month!</p>
<p>Thanks for your support of this magazine so far. I\'m glad to say we have had plenty of student submissions this issue. Keep in mind that it\'s not that hard to submit - if you\'ve written something creative for fun (or class) or just finished a beautiful painting, feel free to submit it to <a href="mailto:highschoolmagazine@gmail.com">highschoolmagazine@gmail.com</a>. After all, this is a magazine for you, by people your age.</p>
<p>Remember to comment on the pieces you like in this issue. Authors write what they think you want to read! It\'s also a great way to show appreciation for the hard work these people put into their poems and projects.</p>
<p>Finally, I\'d like to wish all of you a belated happy Valentine\'s Day and an early happy St. Patrick\'s Day. Till then, though, I hope you enjoy this issue with Sharon Su\'s "Eulogy of Doubt" and Shan Swaminathan\'s "Let\'s Speak Meat - A Blood for Blood Horror Story."</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>