<?php

$aid = 'ruchi';
$title = 'The Secret of the First Charm - Chapters 2-3';
$cid = c1;
$issueid = i4;
$body = 
'
<h12>Chapter 2: Enchantments and Arguments</h12>

<p>I\'ve never been a morning person, not back then, and barely (meaning not even) now. During second semester, I flatly refused to take any morning classes, and Heather had a hard time getting me to wake up the whole beginning of the school year.</p>
<p>Surprisingly, that\'s relevant to my life. On the first day of school, I didn\'t appreciate the intercom waking us up at six in the morning when classes started at eight.</p>
<p>"Can you turn that freaking thing off?" I moaned as I stuck a pillow over my head. Now is the time to mention that Heather was an annoyingly cheerful morning person.</p>
<p>"Get up, Nicky! Come on! First day of classes! Aren\'t you excited?" she squealed. I looked up at her, my black hair obscuring my vision relatively well. It must have been at any rate, or my eyes must have been very blurry, because she looked happy. At six in the morning.</p>
<p>"You. Are. A. Freak." I bit off and I put my head back down. However, less then a minute later I was out of bed and chasing her around the dorm room, out of the dorm room and through the common room. My hair and neck were sopping wet.</p>
<p>By seven the both of us, armed with book bags and the day\'s schedule, headed down for an early breakfast. Well, in my opinion it was early. Half the school was up and eating, although many had expressions similar to the grumpy one I was wearing. We caught sight of Dean and Ray and headed towards them. As we sat down, plates with food whizzed to us, and we began to eat.</p>
<p>"How can you three be so cheerful?" I groaned as I listened in to an animated discussion they were having about the first subject we had for the day, Enchantments.</p>
<p>Dean grinned. "You know, you could have put the fact that you can use your charm to use. Like, I don\'t know, gotten some tea or coffee for yourself when you got up. They did leave us a store of teabags in our room for a reason."</p>
<p>"Uh, Dean, I think she\'s lost," said Ray, mocking me as he saw the confused expression on my face. "Is Nicky confused on how to make teabags into tea?" The baby voice was really annoying and my temper started to sizzle.</p>
<p>"I know you put them in boiling water," I snapped back. "There were no mugs." My three so-called friends dissolved into laughter at my innocent blunder. This is, I think, when I realized how hopelessly naive I was when it came to power.</p>
<p>"Nicky," gasped Heather, tears starting to form in her eyes, "if you transformed Race\'s hair into that delightful pink, you could transform the teabags and bits of plastic into a Styrofoam cup of tea without much of a problem. Especially if that\'s what they are rigged to transform to."</p>
<p>I flushed slightly. I do not hesitate to admit that until I came to this school, I had a bit of an arrogance problem. I had to be popular, I had to be cool, and I had to be smart. And I generally was too. This was one of the first times I wasn\'t completely "perfect."</p>
<p>"I didn\'t mean to turn his hair pink either time," I confessed. "I was aiming for his skin and it just..."</p>
<p>"I thought that was a fluke," came a cold voice behind me. "I didn\'t think I\'d find someone new here smart enough to actually try to jinx me and then to do it properly."</p>
<p>"Aw, come on Chris, be nice. It\'s her first real day here," protested Ray as I concentrated on turning his skin pink again and, as before, his hair turned a deep shade of hot pink.</p>
<p>With a slightly malicious grin, I raised my glass of orange juice. "Cheers," I replied in the same tone as Ray. That was the first and last time I saw Race speechless. After that he was always ready to deal with me. In hindsight, it occurred to me I could have made a friend of Race that day instead of dealing with him as an extremely worthy enemy over the school year.  Either way, what was done was done, and soon the four of us were heading to Enchantments.</p>
<p>As I walked into the door, I saw a young woman, around twenty-two, sitting at a desk in the back. I didn\'t know what to make of her - and I did mention I had an arrogance problem, right?</p>
<p>"Hello, my name is Nicole," I said, walking up to this young woman and shaking her un-offered hand. "What\'s your name?"</p>
<p>With a grin which told me she was about to make an idiot of me, she answered. "Enchantress Kelly, your teacher. Why are you touch-" She cut off her sentence at my pleading look and lifted one of her eyebrows. She never gave me that put down, though, and from then on I worshipped her as a teacher.</p>
<p>"Welcome to Enchantments, kiddos," she said with an easy air after the whole class had trickled in and settled down. If I hadn\'t decided this was probably the coolest teacher I would ever have earlier, I had now. "Now, I\'m sure most of you can do the very basics of this class, as I\'ve heard of a few kids - tampering, shall we say? - with other kids\' hair color." She stopped as the class looked over at me and let out a few quiet laughs. When all the noise died down, she started to speak again. "Well, there isn\'t much to say except I do have high expectations in this class. I\'ve never known a student able to goof off and still maintain grades good enough to get a decent job. As you could guess, Enchantments are the most important course you shall ever take. It\'s what our whole world is based on. Now it just depends on what type of Enchantments you choose to specialize in. However, you have till next year to decide that. This year, we are just covering the basics."</p>
<p>I was not only impressed by this teacher, I started having dreams to be just like her. I must admit, at fourteen I was rather old for hero worship, but Enchantress Kelly seemed so... well, real. It was amazing, but she was like the big sister I always wanted. I was pathetic, don\'t you think? That is beside the point, though.</p>
<p>Within fifteen minutes of our first class, Enchantress K, as I now called her, had assigned us to our first task. It was a simple one. We had a set of stones each, four or five small grey pebbles, and our goal was to move them from basket A to basket B. Before you start thinking any dimwit could do this, listen to the instructions.</p>
<p>We were to move the pebbles without touching them with any part of our body. Oh, did I mention that in the next class there would be a test on this?</p>
<p>I sat in my seat, suddenly feeling like I didn\'t belong in this school at all. I had no clue how to move the pebbles, and I knew that within one day I\'d be unbelievably behind and embarrassed. I closed my eyes and touched my snowflake charm, my memento of my mother, and just wished the pebbles would move from basket A to B. When I opened my eyes, a full two or three minutes later, I was shocked to see the stones had indeed moved.</p>
<p>"Excellent job!" said Enchantress K as she passed my desk. This was the series in the first of many strange happenings that occurred to me that first week. I knew that I hadn\'t moved the pebbles on my desk, but I also know no one else had touched them.</p>
<p>Once again, I have the advantage of hindsight when telling all this to you. See, I never thought to look around to see the other students in my class and to see their reaction to my surprise. If I had, I would have discovered my mysterious benefactor much earlier.</p>
<p>After an hour of class, I found out I could lift the pebbles on my own and move them, using the same concentration I had to turn Race\'s hair pink. However, I chose to concentrate on one pebble, and, instead of turning it pink, I tried to move it up.</p>
<p>I could only endure lifting it for about a minute before I felt all my energy slip away and hear the pebble drop to the desk, halfway between the two baskets. Whoever had helped me earlier had definitely known what he or she was doing. That and whoever it was had amazing control over power - and he or she had an equally amazing amount of it. By the end of class, though, I could move the pebbles to and from the baskets, if not with ease then at least quickly.</p>
<p>Enchantress K hadn\'t really assigned us homework. She had just told us that in our next class we would be quizzed, so we better get to work on moving "them pebbles."</p>
<p>There\'s one thing I always appreciated about Astra, even when the times got bad. There were thirty minute breaks between each class. Granted, the classes were two hours long so you really needed those breaks, but that\'s beside the point. This meant that after Enchantments I had a full half hour till Communications started.</p>
<p>"That was so cool!" I said as we exited the classroom. "I mean, I didn\'t know we could do stuff like that! That was so awesome!"</p>
<p>"Speak for yourself," Heather muttered. With her hair pulled back into a braid and glasses perched on her nose, Heather looked slightly nerdy. It suddenly occurred to me that she was probably one of those more studious people who always had their homework done before it was assigned. "I couldn\'t lift those idiotic stones until class was practically over. Just watch, I\'m going to be working for hours tonight, trying to learn how to do that."</p>
<p>"Calm down, Heather, I\'ll help you," said Race, pointedly ignoring me. I returned the favor.</p>
<p>"Lighten up, Lee," Dean said, grinning. "I agree with Nicky, class was pretty cool. I mean, Enchantress Kelly seems pretty laid back. Right, Ray?"</p>
<p>"I\'m dead," was Ray\'s oh-so-enthusiastic response. "I suck at Enchantments. I couldn\'t even lift a pebble, and I was going green with effort."</p>
<p>"Uh, it\'s red with effort..." Heather said with a giggle. I suppose Ray\'s failure made her feel a little bit better.</p>
<p>"Whatever. The fact is, I\'m dead," repeated Ray.</p>
<p>"So, where\'s Communications?" I interrupted, trying to change the subject. I guess I wasn\'t that subtle, as the four of them looked at me with expressions of equal amusement. "What? I just wanted to know!" I protested.</p>
<p>Shaking their heads, Dean, Race, and Heather started walking down one of the god knows how many corridors of Astra. Just so you know, I\'ve been here for one year now, and I still haven\'t been down half the passages.</p>
<p>Either way, we reached Communications in fifteen minutes and started fooling around outside the classroom. Continuously, I\'d try and turn someone\'s hair pink, as it was the only power I was well-acquainted with, but more often then not, something else would change colors instead. By the time we entered the classroom, Ray\'s textbooks were bright pink, and Heather had a pink uniform.</p>
<p>As two teachers swept by us, they eyed her censoriously, and she shot me a glare with the clear meaning of "turn my uniform back to grey, you idiot!" I replied with a shrug which could be translated as "Sorry, no can do!" After about a minute of glaring at me, she turned to Dean and asked him to help. He changed the color back immediately as we took seats and looked up at the front of the classroom, where the teachers were eyeing the three of us and waiting to speak.</p>
<p>"Thank you," said a fat, dumpy teacher. "Now, assuming I have all of your attention, my name is Translator Avis and this is Carla. We are your Communications teachers. Now, I want the class to split into two groups, of equal numbers. One should line up in front of me, one in front of Carla."</p>
<p>The class immediately stood to split, and I gathered with my friends behind Carla. However, we were the last to decide upon the teacher and apparently we made the groups into "unequal numbers."</p>
<p>"I said equal numbers, was that so hard to understand?" snapped Translator Avis. "You, come here and get into this line," he told me. "What\'s your name?"</p>
<p>"Nicole Raven, sir," I said. For once my politeness was sincere. Translator Avis didn\'t seem like the type of teacher you could mock and successfully get away with it.</p>
<p>"Well, Miss Raven. Could you have possibly counted and evened out the numbers?" he said sarcastically. "Was that request too hard for you to handle?"</p>
<p>Embarrassed beyond belief, as half the class was trying to hide their snickers, I answered quietly, "No, sir."</p>
<p>"Good. Make sure you don\'t mess up again." He then straightened up and led his line of students to the back of the room. "Class, every Monday and Thursday we meet at the back of the classroom. Communications is a difficult subject comprising of actual verbal communication and the written language. As I have seen, some of us have problems with the verbal-" he glared at me-"and others probably will have difficulties at the written. When with me, we shall be working on the written portion, and when with Carla, the verbal. Any questions?"</p>
<p>No one spoke up and he smiled. When he wasn\'t being sarcastic with me, the man had a pleasant smile, and it was easy to see he wasn\'t naturally ill-natured. I wondered exactly what I had done to earn his hostility.</p>
<p>"Now, alphabetically line up and I\'ll start pairing you off for your written work and assignments. Hurry up now!" Immediately all sixteen of us lined up and, to my disgust, I found myself side by side with none other than Chris Race. It was my misfortune to then be paired with him for all Communications assignments, verbal or written.</p>
<p>Chris, at first, looked more disgusted to be paired with me than I with him. However, when we were in our groups of two and starting to work out some old English into modern day English, he looked up curiously.</p>
<p>"Nicole, what\'s your last name?" he asked. I wondered what type of idiot didn\'t know my last name when I was standing by him alphabetically less then two minutes ago.</p>
<p>"Raven," I replied shortly.</p>
<p>"Any relation to the great Daniel Raven?" he questioned. There was sarcasm on the word \'great,\' and I felt my defenses go up as I muttered a "yes."</p>
<p>I heard him curse under his breath as he heard my affirmation, but I didn\'t think much of it. I was more occupied in thinking of how to get out of working with him.</p>
<p>The rest of class was spent translating the sheet of Old English we were given. It wouldn\'t have taken the whole two hours if we hadn\'t argued about almost every single word in the translation. I decided right then and there that Race was a jerk with a serious need for an attitude adjustment. He seemed to think I was some stupid little girl. Once again, now that I\'m blessed with hindsight, I would have realized he was being a pig because of my father. Well, more because of the shock of figuring out who my father was.</p>
<p>As we left the class, Translator Avis shouted that our assignments would be found in our lockers and that we were to do them with our partners and turn them in. I let out a groan and continued walking.</p>
<p>"Wow," said Heather confusedly. "You seem upset about being partnered with Race."</p>
<p>"Tell me about it," I complained. "We couldn\'t even work on the stupid translations properly because he was so...so...so..."</p>
<p>Dean started laughing. "Look, Nicky, we generally don\'t argue with him when it comes to academics. He\'s as smart as Heather here, and you just don\'t argue with brains as brilliant as that."</p>
<p>"He is an arrogant jerk, he kept insisting he was correct about the translation!" I protested. I mean, come on, this kid couldn\'t be that brilliant.</p>
<p>Heather, blushing from Dean\'s compliment, chimed in. "Actually, he really is that brilliant. I won\'t be surprised if he gets elected as class president."</p>
<p>"What do you mean? He\'s a pig! He was so rude earlier! He called me a klutz and acted like he was the king of the world!" Boy I would have felt stupid if I knew he was walking pretty much right behind me, with Brianna and some other kids I\'ll tell you about later.</p>
<p>"Hey, he\'s pretty cool," protested Ray. "He\'s excellent at football."</p>
<p>"ARGH!" I said in frustration and started walking away. Dean, Ray, and Heather didn\'t stay standing shocked for long. Instead they caught up again and avoided the subject. We walked down to lunch and looked over our schedules for our remaining classes.</p>
<p>"Hm...I have...uh, HOP," I said, looking at my schedule like it was broken. Honestly, have you ever heard of a class called HOP?</p>
<p>"Ditto," said Heather, looking over at Dean\'s schedule. "Uh, Dean, what\'s POP?"</p>
<p>Ray snorted. "We have classes called \'HOP\' and \'POP.\' I really don\'t think that these are our schedules. Generally classes have normal names..."</p>
<p>"Those are normal names," came a familiar voice.</p>
<p>"Hello, Enchantress K!" I said, immediately polite. "How are you?" She looked faintly amused. I think she found the fact that I was acting like the snotty teenager that I am as funny.</p>
<p>"You know, Nicole, I would expect this behavior more from a boy than yourself. Actually, more from Mr. Connor or Mr. Patil here."</p>
<p>"What?" I asked, confused. A teacher was telling me I should act more like a girl?</p>
<p>"You  know what I mean," she said with a smile. I\'m assuming she was referring to my idiocy before class and the fact that I was just slightly show-off-ish. "By the way, Mr. Patil and Mr. Connor, please don\'t start any pranks today...if the club assembly goes wrong, James will murder the both of you. He\'s heading it."</p>
<p>Dean grinned. "Yes, Enchantress Kelly. By the way, what do HOP and POP stand for? Sounds like music..."</p>
<p>"Yes, it does, doesn\'t it?" she said, shaking her head. "I have to tell Eleanor to stop shortening the names. They are real classes, don\'t worry."</p>
<p>"Thanks, Enchantress Kelly," said Heather.</p>
<p>"It\'s nothing. By the way, Heather, if you use your Charm when you try to move the pebbles, it will become much easier for you."</p>
<p>"Oh. Thanks."</p>
<p>"Well, I must be off. I have a meeting with Carla. Have a nice lunch."</p>
<p>"Same to you," we all chorused.</p>
<p>After she left though, my cheerful facade dropped. "Did she say I acted like a BOY?" I asked.</p>
<p>"Sounds like it to me," said Heather through a mouthful of potatoes. At my disgusted look, she rolled her eyes and swallowed. "Well, you do act like one until it comes to eating."</p>
<p>"No I don\'t!" I argued indignantly.</p>
<p>"Don\'t what?" came a girl\'s voice. Brianna sat on the bench by Dean and began eating.</p>
<p>"Don\'t act like a boy," said Ray, when he saw I wasn\'t going to reply. "But she does, doesn\'t she?"</p>
<p>"I wouldn\'t know, I haven\'t been around her that much. But from what Race said, she acts kind of boyish, yeah," stated Brianna as she began to eat. How could Race judge me, I thought furiously. He was a pig-headed, arrogant...</p>
<p>"I do not!!" I protested again. Annoyed, I found they were all giving me skeptical looks. "You\'ve only been around me one day, how can you judge? And how the heck would Race know?"</p>
<p>"Uh, I\'ve only been around you four hours and I can tell," came a voice which, until recently, I found annoying. I turned, and to my disgust Race and another girl I hadn\'t met where there. By the looks of the others, the girl wasn\'t very well liked, but they all seemed pleased to see Race.</p>
<p>"Whatever, you guys, I\'m going," I said to Dean, Heather, Brianna, and Ray. Despite what the other\'s said, I really didn\'t want to be around Race. I still couldn\'t get over how unbelievably arrogant he was. As I was heading out towards the common room, Heather caught up to me.</p>
<p>"My god you walk fast," she said, slightly out of breath. I waited for her breathing to even out before I continued walking. After a minute, I spoke.</p>
<p>"Am I really that boyish?" I asked.</p>
<p>"Uh, kind of. But I think it\'s a good thing," said Heather hesitantly. I suppose she didn\'t know me well enough to know how I\'d react. In my mind, I resolved to become more "girly," although I couldn\'t stand those ditzy girls with tons of makeup. Outwardly, I smiled and said "whatever."</p>
<p>"Um," she interrupted my thoughts, "we have less than ten minutes to get to class. I think we better go." I looked at my watch and then her, and the two of us went sprinting through the halls, barely reaching class on time.</p>
<p>The teacher looked extremely amused to see the two of us dashing in last minute and grabbing seats in the front just as the bell rang.</p>
<p>"Welcome to History of Power," said the teacher, a tall man with a rather scary face. "My name is Dr. Price. Despite Ms. Ursa\'s atrocious abbreviation on your schedules, this class has absolutely nothing to do with music."</p>
<p>A lazy voice drawled out, "Aw, sir, you have no clue how disappointing that is."</p>
<p>"Oh, Mr. Race, do shut up," said Dr. Price good naturedly. The class laughed, and he smiled. "Well, I suppose since we have that established, I might as well do some explaining as to why you and your friends are split up. Well, we have the History of Power and Potions of Power course. You take one in the ninth class and one in tenth. This year you were chosen for the History of Power. So, can anyone here differentiate power and magic?"</p>
<p>Heather slowly raised her hand as she became aware that no one else was going to raise it. Being slightly clueless about the world of power at the time, I stayed quiet.</p>
<p>Oh, I didn\'t tell you, did I? Well, my dad hadn\'t wanted me exposed to "his world," and as a result, I knew nothing about power until he died. Basically I had only known about it four years and even then had stayed in a normal school until Astra.</p>
<p>Anyway, Heather raised her hand. "Yes, Miss...?" said Dr. Price.</p>
<p>"Miss Lee, Dr. Price. Well, with magic you can just make things disappear or appear. With power you have to change things which, well, are somehow related, with your mind. And with magic, you don\'t use energy or anything, you have a wand and your abilities come as you learn spells. With power, you use energy from your own body, which can kill you if you use too much. Also, you can only get magic through stardust, so anyone can have it, while you must have some amount of power in your mind and blood."</p>
<p>"Excellent, Miss Lee. Does anyone have anything to add?"</p>
<p>I swear, I could have heard crickets chirping in the room after Heather\'s definition. She had almost nailed everything. I hated how it was an almost.</p>
<p>"Ah, Mr. Race, what do you have to add?"</p>
<p>"With magic you  need a wand. It has nothing to do with the person themselves. When you have power, you need to have it in your blood. Also it\'s almost impossible to steal someone\'s power and, power can be reused, whereas magic cannot. Finally, it\'s legal to use power no matter what, while you need a license to use magic."</p>
<p>"Good job, Mr. Race."</p>
<p>"Thank you sir."</p>
<p>I was ready to murder Race, to say the least. I don\'t know what about him had rubbed me the wrong way. No, that\'s a lie. I did. The idiot had knocked me down, well I had knocked him down, but he hadn\'t accepted my apology, was rude about it, and then insulted me the same time at dinner. And I had noticed that look of disgust he had given me during Communications!</p>
<p>I noticed Dr. Price staring at me and that the class had become dead silent.</p>
<p>Heather passed me a note while the teacher and class stared at me in shock. I kept the note to this day.</p>
<p>"You IDIOT! You go to a power school, people can read your mind if you think with enough emotion! And your thoughts were so bloody loud that I\'m sure kids in the next room heard you!"</p>
<p>"Oops," I muttered, embarrassed.</p>
<p>"Detention, Miss Raven, after dinner," said Dr. Price with a grin. I guess he found my outburst slightly amusing. If I hadn\'t now known my thoughts weren\'t safe, I would have cursed him in my mind. And I would have made up a few scenarios of Race dying a painful death.</p>
<p>The rest of the class proceeded smoothly, and we were assigned to make a list of the differences between power and magic. As I walked out of class, Race stopped me.</p>
<p>"Hey, um, Nicole, you know I was kidding on the subway, right? I mean if we had stayed in the hall a minute longer," he said awkwardly.</p>
<p>"Go away," I said angrily. "Good god, just stay away from me, will you?"</p>
<p>"What?" he said, shocked. You could tell from his face that he wasn\'t used to people rejecting him in any way. The expression of utter surprise almost made me laugh.</p>
<p>"Just back off," I said quietly now. I had been a little too humiliated to just let it go, and it felt like it was mostly his fault, not mine.</p>
<p>"Raven," he started as I walked away. I didn\'t really give him a chance to finish as I caught sight of Dean down the hall.</p>
<p>"Hey, Connor!" I called. "Wait up! C\'mon Dean! Heather!" Putting it simply, I ran away on him.</p>

<h12>Chapter 3: Much Ado About Something</h12>

<p>The four of us went back to the common room, laughing and joking. I had completely forgotten about my detention and by the time I got to my dorm, I was in a good mood. Dean and Ray had somehow gotten into a fight, and they had been rolling all over the floor punching one another. Talk about amusing.</p>
<p>I took out my homework pile from my locker after I dumped my books atop the bed. Translation for Communications, the paper I had to do my History on, and some tips on moving the rocks from Enchantress K. Then I found the detention notice, for eight, almost directly after dinner ended.</p>
<p>I brought my homework down to the common room and started working on the differences between magic and power. I really didn\'t want to do the translation. In fact, if I could just not do it at all, I\'d have preferred it.</p>
<p>Actually, I worked through everything but translation in a matter of an hour and a half. I was zipping the stones from basket A to B no problem, and had even helped Heather do hers. I was willing to do extra work, but I just didn\'t want to do translations.</p>
<p>At around six, an hour before dinner, a Blox entered the room. I suppose you might be wondering what a Blox is. Try to imagine a dog\'s head on the body of a baby (badly dressed, may I add) with a cat\'s tail and wings. Now you know what a Blox is. Although I knew about power, I hadn\'t lived in the power world, but rather in the normal one. I jumped at the sight as the creature came flying to me.</p>
<p>"Miss Raven?" it asked in a gruff voice. I slowly regained the feeling in my legs.</p>
<p>"Yes," I croaked. The creature looked at me in disgust.</p>
<p>"Oh, calm down, I won\'t eat you. Mr. Race is wondering if you would come to the library so that you two could get your translation done," it said.</p>
<p>"Oh. Tell Mr. Race that he can do the first half of the translation till the word "whizznot" and I\'ll do the rest. There is no need for the two of us to work together."</p>
<p>"How odd. Mr. Race told me you\'d say that. He also told me that if you did I\'d have to drag you out."</p>
<p>Before you wonder why I decided to leave at that threat, you had to see this creature\'s teeth. This wasn\'t a friendly looking Blox, but a very, very scary looking one.</p>
<p>Race, on the other hand, petted the thing on it\'s head before he told it that it could go do whatever it wanted now, he\'d call it again if he needed it. Then he turned to me.</p>
<p>"Ready to work?" he asked in a friendly tone. I stiffened and knew not to fall for his "kind" act, and just nodded. "Great!" he said. "Look, you aren\'t actually allowed to yell at me in here, so we might actually get our work done. Why don\'t we just work at this library for homework assignments we have to do together?"</p>
<p>"How about we just don\'t meet at all and split the homework up?" I suggested in a would-be-pleasant voice.</p>
<p>Race stopped and rolled his eyes. "Look, Raven, I\'m really sorry about earlier. Can you stop being so stuck up and just let it go? We\'re in all the same classes and we have to work together in one of them, so we might as well just try and be friends."</p>
<p>"I\'m stuck up?" I said, raising my eyebrows. "I\'m not the one who wouldn\'t let his partner have a single say in Communications, I didn\'t insult you during dinner, and I was quite kind on the train. So don\'t you dare call me stuck up."</p>
<p>There\'s one good aspect about living alone with your mother. You pick up on that quiet, venomous tone she uses to Child Care Workers. That was the exact voice I used on Race, and I could tell it got on his nerves.</p>
<p>"God, you can stop being such a prim and proper little girl," he said, his tone slightly angry. "And can you just try and forgive and forget? I don\'t want to work with someone who has no sense of humor-"</p>
<p>I stepped on his foot, hard. I don\'t deny it and I\'m still quite proud that I managed to hurt Race. And he was rather arrogant. I mean, he really couldn\'t say I had no sense of humor. He didn\'t know me at all, and in addition to the way he had treated me, some of the rude things he had said, for example "stuck up" and "prim and proper little girl," weren\'t very forgiveness inducing.</p>
<p>He groaned and then deliberately stepped away from me, so that a good two feet were separating us. "Look," he said in a reasonable voice laced with pain. I really had stepped on his foot hard, and with my heel. "Why don\'t the two of us just work on it together in the library, let\'s say from six to seven, the nights we have an assignment together. This way we both do the whole assignment and we can make sure we have it completely correct. And, by the way, my foot hurts really badly."</p>
<p>I couldn\'t help but laugh. "Well, since your foot hurts so badly, I can agree with that. But that doesn\'t mean you\'re forgiven for being a complete idiot from the first time I met you," I said with a smile.</p>
<p>Surprisingly, we got along for the next forty minutes, during which we finished our translations. I stuffed mine in my book bag as he put his in his textbook for Communications. We walked back to the ninth grade common room together, and I was starting to think the two of us could be friends after all.</p>
<p>"Well, this is amazing, but you weren\'t such a stuck up brat after all," he said, as I was entering the common room. "I mean, you seemed really arrogant and rude earlier." I stiffened and anger flowed through me as I walked up to the dorm to put my books away. Friends my butt.</p>
<p>Heather and I walked down to dinner with me complaining bitterly about him. "He was so nice and I had just made up my mind that maybe we could be friends when he said that I wasn\'t such a stuck up brat and called me arrogant. He thought I was rude!"</p>
<p>"Thought, as in past tense," said Heather as she sat down. "As in get over it, he was just being blunt."</p>
<p>"He was being a jerk," I insisted, starting to eat the pasta that had whizzed down on a plate in front of me.</p>
<p>"Who was rude? Wait, let me guess, Race," said Dean as he sat down beside me. He was covered with a thin layer of sweat, as was Ray.</p>
<p>"Yeah, Race," I said angrily and shoveled a forkful of food into my mouth.</p>
<p>"Just chill, Nicky," Ray said as he started eating. "I mean is there any point in getting worked up over him annoying you?"</p>
<p>"No, I guess not," I said reluctantly. I finished my meal in silence, smiling my greeting to Brianna when she joined us. As I looked around, listening to my friends talk, I noticed a lot of dirty glares directed at me. Most of them were from kids who I didn\'t know, and I found it rather odd that I was getting so many weird stares.</p>
<p>"Uh, guys, is there something on my face? I\'m getting a lot of nasty looks," I said, gesturing at the unfriendly masses of people. Instantly, Ray and Dean looked away, uncomfortable, while Brianna looked at me in shock. Obviously there was something very wrong here.</p>
<p>"Um, Nicky, do you know who your father was?" she asked uneasily.</p>
<p>"Daniel Raven...my...father?" I said, confused. What did my father have to do with this?</p>
<p>"Uh, well, um, he\'s in your history book. I suggest you look him up when you get to your room tonight," she said. Ray and Dean both looked up and shot her glares. I hadn\'t seen the two do anything but smile earlier, so I was wondering where all this sudden hostility came from.</p>
<p>Ignoring their calls to come back, I walked out of the hall and to my dorm, where I took out my History book and started searching the index. Finally, I found the name "Daniel Raven," and flipped to the page. There was a footnote underneath a picture of my father.</p>
 
<p><i>A well-known menace, Daniel Raven is an example of the first murder due to power. Raven was well known for a period of five years as a "random killer." It was never known who he would strike, or why. He was the first known person to discover how to kill utilizing power, a feat that has not been repeated since his death. His most noted murder was that of Joe Connor, a well known Secret Sorter.</i></p>
 
<p>The footnote ended there, but it told me what I had wanted to know. My father was a murderer. Anguish ripped through me as I realized why no one had brought it up, why Race had asked, why everyone was awkward when I asked what was wrong. They were talking to the daughter of one of the more renowned - one of the first - murders of all time when it came to power.</p>
<p>I lay on my bed, staring in shock at the book, tears pouring down my face. I didn\'t hear Heather enter the room or feel her sit down on my bed.</p>
<p>"Nicky, it\'s okay. We didn\'t know that you didn\'t know about this," she said quietly.</p>
<p>"I can\'t believe this," I said through my tears. "IÑI..."</p>
<p>"It\'s okay. Look, it\'s not like anyone holds it against you. I mean everyone from a family immersed in power knew, and Dean certainly wasn\'t angry. I mean your dad killed his and he doesn\'t hold it against you..."</p>
<p>That was the worst thing she could have said. I hadn\'t noted the "Joe Connor," but I now made the connection instantaneously.</p>
<p>I shoved the book out of the way and dropped my head on the pillow, waves of hurt and sorrow pouring through me for what my father had done, for what I must have represented to many of the people in the cafeteria. Heather seemed to realize that she shouldn\'t have told me about Dean\'s dad.</p>
<p>I cried myself to sleep that night, forgetting completely about my detention. I don\'t know when Heather turned off the dorm lights or when she herself slept.</p>
<p>The next morning I was up at five in the morning, having been too miserable to sleep properly. I went through the motions of getting ready, although I didn\'t take the time to brush my hair. I just shoved the long black mess into a bun and left the room with my books.</p>
<p>I had no appetite either, and before six I was gloomily wandering around the halls. Unfortunately, I wasn\'t looking where I was going and I ran into somebody.</p>
<p>As I fell, I knew that it was Race. My luck was so horrible it had to be Race.</p>
<p>"You okay, Nicky?"</p>
<p>For one of the first times I was wrong.</p>
<p>"Nicky?" Ray waved his hand in front of me. "Are you okay?"</p>
<p>"Yeah, I\'m bloody brilliant," I said sarcastically. "I mean my dad just happened to be a murderer who killed Dean\'s father. So I\'m just peachy, thanks."</p>
<p>"Uh, you want to walk or something?" he asked, his eyes concerned.</p>
<p>"Sure," I shrugged. He led me down a confusing amount of halls and through a door that led outside. I couldn\'t help but gasp. We were standing in front of a huge field and a beautiful lake, and the sun was just starting to rise. I walked over to a tree and sat down, my back resting against the trunk.</p>
<p>Ray sat as well and just looked at me. Thoughts of my father were still swimming in my head, and finally, I cracked.</p>
<p>"Why me?" I whispered. "My mother never told me. And why does it have to me my father that killed Dean\'s? And why did it have to be Dean\'s? He\'s never going to want to talk to me again, and he\'s going to hate me. Every one\'s going to hate me. Why shouldn\'t they? I carry the blood of a murderer."</p>
<p>As I went on, Ray moved closer to me, and as he put his arm around me, I burst out into tears. For the next fifteen minutes, as cliche as it is, I cried my heart out. However, when I finally stopped sniffing and feeling sorry for myself, I felt much better.</p>
<p>"Look, Nicky," said Ray comfortingly, "Don\'t worry about it. Dean doesn\'t blame you, Heather doesn\'t, neither does Bri, and I definitely don\'t. I personally would be more worried about that detention you missed..."</p>
<p>"Shoot!" I said as I stood up. "I\'m so dead. Crud. Dr. Price is going to so kill me."</p>
<p>Ray grinned. "You\'re right, he is. So I figure you forget about your father, because in a short time, this whole school will, I\'m betting in two weeks no one is going to associate you with your father at all, and run and apologize to Dr. Price."</p>
<p>"Yeah, uh, I\'m not sure about the first thing," I said, panicked, "but I am worried about Dr. Price. Crud, how\'d I forget? I\'m so dead!"</p>
<p>"Maybe, instead of complaining, you should go," said Ray dryly. "I\'ll see you during Enchantments."</p>
<p>"Okay." In the middle of dashing off, I turned back. "Oh yeah, thanks," I said, kissing his cheek and running to find Dr. Price to avoid getting in bigger trouble. This is one of the points in my life too, where I wished I had looked back to see Ray\'s reaction. Either way, I didn\'t.</p>
<p>I dashed through the halls, trying to find Dr. Price, who had to not be in his room. Just then, the six AM bell rang. Well, that explained why he wasn\'t in the classroom. I ran to the cafeteria and stood by the teachers\' table, waiting for him to show up. By six fifteen, students were trickling in, and I was getting seriously nervous. I was convinced that missing a detention was a federal offense.</p>
<p>When Dr. Price finally showed up, it was with Enchantress K, and the two were talking in serious tones. My heart sank - now my favorite teacher was going to hate me because I skipped a detention. However, when they caught sight of me, Enchantress Kelly smiled. Dr. Price looked more serious.</p>
<p>"Sir," I said as he approached. "I\'m really sorry about missing the detention yesterday. I kind of forgot about it. I know there\'s no excuse, but I\'ll make it up tonight. I\'m really sorry," I repeated.</p>
<p>"Calm down, Ms. Raven. You aren\'t going to be expelled for missing a detention, although I am rather disappointed," he said. "I was hoping you would be able to serve the detention with me and that we would be able to figure out the reason for your animosity. It\'s no matter though. You may serve it tonight with your friend Mr. Race. I believe it\'s with Ms. Bethany, the Power of Potions professor."</p>
<p>"Thank you, sir," I said, turning to head out of the cafeteria, slightly disappointed. A detention with Dr. Price would have been rather fun, and I liked the teacher a lot. I didn\'t know anything about this Ms. Bethany character.</p>
<p>"Oy! Nicky!" called Dean as I was leaving the cafeteria. I turned, paling at the sound of his voice. While missing a detention had made me nervous enough to forget what had happened last night, the nerves for that were over.</p>
<p>"Hey," I greeted him softly, gauging his reaction. He grinned at me and motioned for me to sit down.</p>
<p>"So, did you get in trouble for ditching detention yesterday?" he asked, his mouth full of eggs. I cringed and nodded \'no,\' scared that I would vomit if I opened my mouth. He noticed something was wrong and swallowed before he spoke again. "What\'s wrong?"</p>
<p>"Ugh, you\'re so gross," I said candidly. "Talking while chewing...yuck!" He blushed and muttered an apology. After a few minutes of quiet eating, Heather piped up.</p>
<p>"You missed the club meetings and stuff yesterday," she informed me, "and so I signed you up for some clubs, and you\'ll see tonight which ones you got in."</p>
<p>The orange juice I had been imbibing was spat out as I stared at her in shock. "You WHAT? Oh, god, please don\'t tell me you signed me up for anything nerdy," I pleaded.</p>
<p>"Calm down, Nicky, she signed you up for Dean\'s clubs. That\'s it," said Ray soothingly.</p>
<p>"Thank god," I said weakly.</p>
<p>"Anyway," Heather continued, slightly miffed, "Race came looking for you as you two were supposed to be doing detention with Dr. Price together...and he was kind of irritated you never showed up. I told him you were sick-"</p>
<p>"You should have told him I ditched," I interrupted. I had no kind feelings toward Race, his insults still at the back of my mind.</p>
<p>"-and so you two are going to be doing detention together tonight. Other than that, you didn\'t really miss anything," she finished.</p>
<p>"Cool," I said, grinning. "Look, classes start at eight and this is my second breakfast...and it\'s not even seven...you guys want to go explore or something. Although it looks like Ray already knows his way around."</p>
<p>"We went out to play football there yesterday," he said by way of explanation at the same time Dean said "definitely." The four of us quickly finished eating and decided to go down a corridor we hadn\'t really paid attention to earlier. In fact, we noticed most people\'s eyes completely skipped that corridor. We found this odd, and walked down the passage, where we hit a dead end next to a statue of a phoenix. The statue was broken, with a hole in it\'s wing, and it\'s feathers were intricately detailed, I noted with surprised. Who would bother to put so much effort into a stupid statue?</p>
<p>"Something feels weird here," I said, feeling a tug towards the wall opposite the statue. "I feel like I should walk through the wall...crazy, huh?"</p>
<p>"Not really," said Dean slowly. "My bro said that there are a few secret rooms...maybe there\'s one here."</p>
<p>"Yeah, and how are we supposed to get in? Magic?" said Heather sarcastically. I looked at her surprised, she was normally so sweet. I made a mental note to myself to get to know her better. "I mean, I don\'t see a door."</p>
<p>"Well...maybe we\'re supposed to use our power," suggested Ray after a minute of silence. "I mean, it makes sense..."</p>
<p>"It\'s worth a try," I said, closing my eyes and trying to focus all my energy on revealing a hidden door. After two minutes, a door visualized in my mind, and I opened my eyes in shock.</p>
<p>The other three were staring at me and then the door in shock. "How\'d you do that?" demanded Dean.</p>
<p>"I focused all my energy on revealing a hidden door," I said dryly, imitating my thoughts. Insultingly, the boys looked impressed that I was able to follow that much logical thought.</p>
<p>Heather pulled open the door and the four of us coughed as we entered the musty passage.</p>
<p>"Shut the door," I hissed. "We don\'t want anyone to be able to find this." Instantly she slammed the door shut and we were left without light.</p>
<p>"Smart, Nicky. Now what are we supposed to do?" came Dean\'s voice.</p>
<p>"Um...keep walking?" I hazarded. "I mean, it\'s not like the door had a handle on the inside, so our best guess is to go down wherever this place leads...just keep your hands out in front of you so you don\'t run into a wall or something."</p>
<p>I heard the other three groan, but they followed my advice, as I was shoved by three sets of hands within the next two minutes.</p>
<p>"Look, light!" Ray said, as a pinprick of light was visible at the end of what seemed to be a long tunnel. We broke into a jog, eager to see where the light was coming from, and the spot of sun slowly grew larger.</p>
<p>As we came close enough to see that the light was coming from a window overlooking the lake, we were blinded by light from all around.</p>
<p>I let out an involuntary gasp as I took in my surroundings. There were three couches comfortably arranged, a refrigerator, a bookcase, shelves, a pantry, stoves...basically, we were in a miniature house without bathrooms or bedrooms. There seemed to be a space designated as a living room, dining room, library, and kitchen. What had me most surprised, though, is that these were decorated with Phoenix signs and colors - antique gold phoenixes upon a black background. Despite the excessive black, I felt as if I had stepped into an affectionate and happy home, as a feeling of warmth enveloped me.</p>
<p>"This is awesome," said Dean, flopping down on one of the couches. He looked at the magazine bin and let out a disappointed sound. "These are thirty years out of date."</p>
<p>"Well, the place is so musty, I mean, it\'s kind of obvious no one has used it for some time," Heather pointed out reasonably.</p>
<p>Ray crossed to the fridge and opened it. Yelling in shock, he slammed it back shut.</p>
<p>"What happened?" I said, frightened.</p>
<p>"It...it...there was no food when I opened it, and then suddenly all this food appeared, and it was all the food I was thinking of. It\'s like it was magic!" he said, stammering.</p>
<p>"God, I thought it was something bad," Dean said, joking. Obviously, he didn\'t believe Ray. That changed a mere second later when he tried to use the refrigerator himself. He let out an excited squeak that had Heather and me laughing on the floor, and took out a turkey sandwich.</p>
<p>"That\'s amazing!" he exclaimed. "This is officially my favorite spot in the world."</p>
<p>"And it\'s magical," added Heather. "I mean, it\'s obviously all magic and not power. That\'s pretty awesome..."</p>
<p>"You know," I said, "despite that essay, I still don\'t see the difference. I\'ll just take your word on it." Heather just shook her head and muttered something that sounded suspiciously like "slacker." She went to check out the library while Ray raided the kitchen and Dean prodded around the living room. I joined him there, checking out the \'far end\' of it. There was an elaborate tapestry of a phoenix on the stone wall, drawn in surprising detail. On either side of it were at least two hundred scrolls, tightly wrapped up in black string and hanging.</p>
<p>I took one down and unwrapped it, wondering what it\'d say. Either way, I wasn\'t expecting to see tons of photos somehow merged onto the scroll like a scrapbook, with some text beside it.</p>
<p>"Hey, guys, look at this," I said. Heather, Dean, and Ray gathered around me and we stared down at the photos of two freshmen, a guy and girl, fighting with one another. One picture had the girl punching the boy, another had him dumping a creme pie on her, and on they went. At the very top of the scroll, in elaborate lettering, was written, "The Life of Ryan and Carol Sullivan."</p>
<p>"I wonder who they were," said Heather, eyeing the rest of the pictures. "Either way, it looks like they couldn\'t stand each other. I don\'t see a single friendly picture of the two of them." I rolled up the first scroll and took down the second. This one also contained pictures of the same two children, and it continued with their fights with commentary along side.</p>
<p>One particular comment that had me laughing for a good two or three minutes was written by a picture of Carol, as I am assuming the girl was, slapping Ryan, who was holding a black rose.</p>
<p>"Ryan asked me out with a white rose, saying it was as beautiful as I was. The moment he said that, the rose turned an ugly black and became all wormy and disgusting. He grinned and said that the rose was just trying to become as \'beautiful\' as me. I couldn\'t help it...I hit him. This was slap number fifteen."</p>
<p>Carefully, I rolled this scroll up as well, vowing to take the time to go through all of the scrolls one day and see what these two did through their high school lives.</p>
<p>"That rose trick was clever," Dean muttered. "I could use that sometime."</p>
<p>"Try that with Bri and she\'ll kill you," said Heather, who had turned back to the library. "You know, this library is tight. They even have modern books in here, which is awesome. And the cool thing is that if you are looking for a specific book, it seems to glow. It\'s weird, but it\'s had all the books that I\'ve asked for in here..."</p>
<p>"You\'re the one who said the room was magic, so you really shouldn\'t be surprised," commented Ray, who was now looking at the dining room. "This place must have cost a fortune to make. I wonder who came up with it."</p>
<p>"Not to state the obvious, but Ryan and Carol Sullivan," I said. "I mean, we just looked at the first bit of their history, so it\'s an easy guess."</p>
<p>"How long do you think this took?" said Dean, jumping back onto one of the couches. "I mean, magic is supposed to incredibly difficult to learn how to use properly."</p>
<p>"Who cares?" I asked. "The fact is, it\'s here now, and if we ever want to, I\'m sure we can read about it." I gestured to the scrolls. "I\'m a little more interested in getting some napping done. Anyone willing to wake me up in time to get to Enchantments on time?"</p>
<p>"I will," said Heather absently. "You have an hour...it\'s not even six fifty."</p>
<p>And so, as far as I know, nothing happened in the hour I slept, and the day continued as normal.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>