<?php

$aid = 'ruchi';
$title = 'This is Bunny';
$cid = c4;
$issueid = i4;
$body = 
'
<pre>
(\\__/)
(=\'.\'=) <b>This is Bunny. Copy and paste Bunny into your</b>
(")_(") <b>profile to help him gain world domination.</b></pre>

<p>"Ha!" squeaked Bunny. "I knew it\'d work. Stupid kids, so easy to manipulate. They just think I\'m so darn cute."  He closed one AIM info window and opened up yet another. To his shock, he saw an anti-Bunny ad. In fact... it was for Chicken!<br/>
"THAT LYING FRAUD OF A CHEAT! HOW DARE HE! I\'LL GET HIM! \'<i>I behind you all the way, Bun,</i>\' he said! Well! We\'ll see!!!" Furious, Bunny stared at the (ugly) picture of his new nemesis and ex-best-friend Chicken.<br/><br/>
<pre>
  !!!!
 [\'<>\']
/(____)\\
  |  |  
  ^  ^
</pre>
<br/><b>This is Chicken. Copy and paste him into your profile to help him defeat bunny.</b><br/><br/>

Bunny picked up the phone and dialed 555-CHIC to reach his new arch enemy.<br/>
"Hello?" a voice squawked.<br/>
"EAT FUR, FEATHER FACE!" Bunny shrieked into the phone. "You\'re going <i>down</i>!"<br/>
For a second, Chicken wondered what Bunny was talking about. Then he realized he had just been called Feather Face. There was no way that a stupid rabbit was going to call him feather face. "We\'ll see, you wingless rodent!" he squawked into the phone.<br/>
"FINE!" shouted Bunny before slamming down the phone. He stared some more at the Chicken advertisement before calling the President over to his bunny hole. There was no way that a measly bird that looked like a demented pillow was going to get away with taking over his plans for domination.<br/>
<i>Five minutes later...</i><br/>
"WHAT DO YOU MEAN I CAN\'T SUE! HOW IS THAT NOT SLANDER? OR A DEATH THREAT! HOW STUPID CAN YOU PEOPLE GET!"<br/>
The President smiled. This was going perfectly; if Bunny was against Chicken, he could finally take over the world...! There\'d be no stupid fluffy rabbit (who was oh-so-cute) in his way…he knew that making a fake campaign with that stupid Chicken would work. "I mean, Mr. Bunny, that you can\'t sue. Surely you can\'t take all this public attention? Maybe you should stop trying to dominate the world."<br/>
"NEVER!" Bunny screamed. "IT\'S MY WORLD! MINE!"<br/>
The President frowned. The phone rang.<br/>
"What is it?" Bunny snapped, "Because I\'m in the middle of a world-domination crisis."<br/>
"Mr. Chicken has been killed, sir." The policeman\'s voice was impersonal. He had acted on Mr. President\'s orders and killed the Chicken as soon as the (adorable) Bunny had seen the death threat.<br/>
"Oh," Bunny said, speechless. He hung up the phone and turned to face the President and relay the bad news. Immediately there was a sharp pain in his head (like glass cracking over it) and everything went dark…really dark…and really wet and hot. Almost like he was boiling...<br/>
<i>Later that evening...</i><br/>
"Great rabbit stew, honey," the President told his wife.<br/>
"It was a great (and cute) rabbit," Ms. President replied. President grinned and went to his computer to check the AIM profiles.<br/>
<br/><pre>
  O   <b>This is President.
/|v|\\ Copy and paste President
 |-|  into your profile to help him
 |||  brainwash Americans into abject stupidity!</b></pre>
<br/>
Props to Anik Debnath for "Chicken," half my school for "Bunny," and Tonia Sun for "President."</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>