<?php

$aid = 'ruchi';
$title = 'Busy Summers';
$cid = c15;
$issueid = i4;
$body = 
'
<p>Some time ago, my mother attended college night at my school. While she sat inside listening to college counselors\' lectures, I was outside enjoying my "freedom."  However, this wasn\'t such a good idea - on the way home, my mom started a conversation that\'s still stuck in my head.</p>
<p>"You need busy summers," she said. I mistook this for a random statement.</p>
<p>"Uh, why?" (Yes, I\'m oh-so-witty.)</p>
<p>"Because colleges want kids who have busy summers and you already have had one slacker summer," my mother explained.</p>
<p>I was stunned. Attending an expensive private school, maintaining a respectable GPA, and participating actively in clubs and sports weren\'t enough; nope, I had to have "busy summers" as well.</p>
<p>It\'s true that the Silicon Valley (along with the rest of the world) has become more competitive; we have many excellent private and public schools filled with students who have above average intelligence. But somehow it seems wrong that in order to get ahead of these kids in the race for college, I have to sacrifice my summer as well.</p>
<p>What is a busy summer? According to my teachers and parents, a summer is only busy if you are working, interning, taking classes, or volunteering. Sadly, traveling isn\'t on that list.</p>
<p>When all this had been explained to me, I came to the brilliant conclude that I had had a busy summer. Pleased, I informed my mother that I had gone to the NJCL convention.</p>
<p>"That was one week," my mother replied. My ninth grade summer was officially useless. I was upset about that - like any normal (nerdy) child, I want to get into college. I want to get a great education and become a high-powered executive or genius researcher... or at least a well known psychiatrist.</p>
<p>Thankfully, I have two more summers to "redeem" myself. And better yet, I finally found out how to have this so-called "busy summer" and enjoy it as well. (Ha! I\'ll have my cake and eat it too!)</p>
<p>"How?", you ask.</p>
<p>Well, I genuinely like Biology... so I\'m willingly taking the pre-AP course that my school offers. Basically, I\'m doing something that I actually love during summer so that it won\'t seem like the fun has been sucked out of the sunny-beach days.</p>
<p>I\'m pretty much trying to say that beware; you need something other than school-year work to get yourself into college, to pull yourself ahead of the rest of the crowd (or so say the college counselors).</p>
<p>The more important point I\'m trying to make is that these summers don\'t have to be dry and boring; it\'s summer vacation! Just take the initiative and find something that lasts the whole summer that you want to do - go and ask the school office. They have a stack of paper for people to apply for volunteer work and internships. Go, find a job in a place you are interested in, volunteer with your friends, or learn something that actually excites you.</p>
<p>Sure, as high school teens, our summers are officially now shot to hell... I mean, I\'m going to miss lying around on my back in the sun while reading some book and chilling with my friends. But we can still have fun with what we need to do to get into the place we call college.</p>
<p>...right?</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>