<?php

$aid = 'sharon';
$title = 'Under the Costume';
$cid = c3;
$issueid = i4;
$body = 
'
<p>I once went to Disneyland<br/>
I smiled while Mickey Mouse held my hand<br/>
I hugged him and he blew a kiss<br/>
As if to say, "It doesn\'t get happier than this."<br/>
<br/>
Now I wonder, who is he?<br/>
The person under the guise of dear Mickey?<br/>
What\'s going on in that person\'s head<br/>
If I asked him that, what would he have said?<br/>
<br/>
Why did I hug someone who I don\'t know?<br/>
Isn\'t that something I learned ages ago?<br/>
Why are the rules suspended here?<br/>
Why do we abandon the values that we hold dear?<br/>
<br/>
What if, costumed as Mickey, there\'s a real pervert?<br/>
Who hugs me and then tries to look down my shirt?<br/>
Is that why he squeezes me so close?<br/>
Don\'t you think that\'s really gross?<br/>
<br/>
Or maybe a kid as old as I?<br/>
Who, without the costume, is really shy?<br/>
What if he\'s so afraid to go on the stage<br/>
He\'s stuck here hugging a girl his own age?<br/>
<br/>
What if Mickey\'s not a him, but a her?<br/>
Who feels itchy and sweaty under the fur?<br/>
What if she\'s afraid that by the end of the day<br/>
She\'ll be so stinky she\'ll scare her boyfriend away?<br/>
<br/>
So as I look up into Mickey\'s blank eyes<br/>
Wondering who\'s under that large-eared disguise<br/>
And because I really have no clue<br/>
I want to say, "Mickey, who the hell are you?"<br/></p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>