<?php

$aid = 'stephanie_sharon';
$title = 'The Pros and Cons of AIM';
$cid = c8;
$issueid = i4;
$body = 
'
<h12>Pros of AIM</h12>
<p>Stephanie Lio</p>

<p>AIM, or any form of instant messaging, is often held responsible as the leading cause of distraction from homework and other school related activities. I myself choose to limit the time spent on AIM simply because I work more efficiently without it. Of course, it is only an evil if we choose to make it so. It, too, has its merits as a form of online communication that we can apply to our advantage, with a bit of self control.<br/>
<br/>1.	As a form of communication, instant messaging is extremely convenient. Not only is it cheap, the only cost being whatever you pay for internet service or a phone line, but it expands the breadth of conversation. For example, you can talk to multiple people at the same time, unlike the phone or even text messaging, since messages must be sent one by one. Quicker than email, instant messaging is a wonderful way to "mass communicate", so long as everyone is online of course (unless you use YIM, which allows the leaving of messages).<br/>
<br/>2.	It\'s never been easier to be social. Because of the widespread use of AIM and its convenience, instant messaging has a lower pressure factor than an in-person or phone conversation. Of course, it\'s best to not replace these vital functions with those online (and it\'s never a good idea to approach someone for the first time online, as that would be...stalking, really), but the fact that you now have time to process messages and make contemplative responses allows more ease - as well as the lack of face-to-face conversation, which is both positive and negative. However, for the extremely shy, typing in front of the computer may be less intimidating than speaking in person, where one\'s facial expressions are tantamount.<br/>
<br/>3.	While instant messaging has been accused as the cause of plummeting grades and late-night consequences, I\'ve found that in some very special cases, AIM can be used for collaborative studying. Yes, studying. On those rare occasions, I quiz my friends via those flashing AIM windows, copy and paste text for peer editing exercises, and ask purely school related questions. If you are studying online, the best way to stay focused is to quiz items that don\'t require too much typed explanation that might lead you astray. For example, quizzing each other on vocabulary and definitions or history facts often work fairly well. Going over chemistry or math equations does not, as I discovered when attempting to have a friend explain Physics concepts - extremely difficult to convey through words, sans paper and interactive diagrams.<br/>
<br/>However, if you find that you lack utter self control to limit your time spent idly chatting on AIM, or that these tactics are far outweighed by their negative side effects, it might be best to just "sign off" for the long term, or even permanently.</p>

<h12>Cons of AIM</h12>
<p>Sharon Su</p>

<p>I used to be the world\'s biggest AIM addict. My life revolved around AOL Instant Messenger. If I was in two chats and seven conversations at once, I\'d feel popular and loved. I brushed away guilty feelings by insisting that it was all for the good of my academic life; after all, if I couldn\'t contact people, pronto, how could I get help for history class? Clear up the tangle of laws that were confounding my physics class? I figured the reason why I never had any time was because I just had so much homework.</p>

<p>When my mom told me to "please do your homework and don\'t get distracted with instant messaging," I\'d ignore her; she didn\'t understand that I needed AIM for homework, that one or two (or fifteen) conversations on the side weren\'t going to hurt anyone.</p>

<p>The administrators at my school just didn\'t seem t to understand either. They told stories of students who had decided not to use AIM and came back with fairy tales of "I had so much more time!" and "My grades went up!"</p>

<p>They just don\'t understand , I\'d think, and continue gossiping with my best friends, leaving my history book abandoned on the floor.</p>

<p>Then in late November or so, I was at my piano teacher\'s Steinway, fumbling through Bach\'s Italian Concerto. My teacher was, safe to say, quite exasperated, and wanted to know if I seriously thought I could be ready for an audition in March. Her words made me feel ashamed of myself and my pro-slacker habits.</p>

<p>I\'m not sure what happened, but I decided, in a frenzied, faux-noble state of mind, that I would swear off AIM, for the sake of piano and homework and all that was good.</p>

<p>The first few days, I was desperate. Absolutely deprived of my only means of social contact, I moped around, then fired off e-mails to about a dozen of my friends, begging them to reply soon. While waiting, I shuffled up and down the stairs, flipped through a few books, and scavenged for things to nibble on - all to fill up that horrible, empty feeling of loneliness. I found myself identifying with those smokers, alcoholics, and drug addicts who only wanted a puff, a drink, or a snort of that wonderful stuff that kept them alive.</p>

<p>After those agonizing few days, I bounced back and found that life without AIM was so much more satisfying than life before. I discovered that those arguments I had clung to in order to validate my addiction had been, really, too weak to validate anything.</p>

<p>1. The old standby, "AIM is so convenient!" was struck down by the harsh light of truth. What did I need instant messenger for? For most things in which I would need to contact someone, e-mail would be fine, even though there were times I wished my teachers had AIM. If I wanted to clear something up with my carpool, I could always call her. Besides, with instant messenger, I couldn\'t always be trusted that I would get a prompt reply; more often than naught, the people whom I wanted to talk to would have put up an away message, or, infuriatingly, would be off eating or something without having indicated so.<br/>
<br/>2. I had once told my worried mom that AIM heightened my social skills. That\'s what we all say, right? Well I found that I, as a person, was more open and social once I had given up AIM. Sure, it\'s easier to approach a person you\'re mildly intimidated by through AIM, but it doesn\'t do anything for your character; on the contrary, it only makes you more of a coward. AIM has watered down the intensity of life, and there is no way that chatting on AIM will ever prepare you for college interviews. The only way to practice using eye contact and explore the ways you can vary your voice is, of course, to practice.<br/>
<br/>3. And that argument we all use against our parents: "But I use to study!" Sure, it\'s good that you quiz your friends through AIM, or ask them for a list of synonyms, but it doesn\'t do much for your study habits. I found that my grades improved when I employed the use of flash cards, and I got better at studying when I learned to skim passages and spot key words; before, I had relied on my friends, and while my friends are great at explaining things, they can\'t really pinpoint my weak points or cover all subjects in a chapter, and they are often too preoccupied studying their own books to thoroughly grill me. I got better at researching and coming up with things on my own that hadn\'t already been endlessly passed on through multiple conversations. Besides, many things that I had trouble with had to do with math or science, and diagrams are pretty hard to convey through instant messaging.</p>

<p>My point? AIM has its merits, being convenient and all, but it\'s not worth your time. You will not be "out of the loop" if you don\'t use AIM, it doesn\'t do wonders for your grades, and you are not going to be any cooler if you spend your lifetime online. (If that\'s how you\'re judged by your friends, pick better friends next time.)</p>

<p>I\'ve been off AIM ever since that "fateful day" in November. I initially meant to get back on around March or so, but I\'ve enjoyed my AIMless life so much, I think I\'ll stay off for a bit longer. I suggest you swear off for a bit, even it it\'s just a week or so. Go ahead, "sign off."</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>