<?php

$aid = 'neelaysh';
$title = 'Reflections on the Lunch in Darfur';
$cid = c15;
$issueid = i4;
$body = 
'
<p>A few weeks ago, Harker students had the chance to forgo their double lunches (90 min lunch period) in order to raise money for the genocide currently occurring in Darfur. The money saved (approx. 5 dollars per student) from not making lunch was to be donated to OXFAM to help build a well for the refugees.</p>

<p>Despite the large number of people who did attend the lunch in Darfur, many, for various reasons, did not attend. Perhaps they didn\'t feel it was worth their time or maybe they didn\'t think they could make a difference or still others might have felt that having food in their own bellies was more important.</p>

<p>When it first came to my attention that some didn\'t feel that their five dollars could make a difference, I immediately thought back to a story that had hung on my bedroom wall for a greater part of my life:</p>

<p>"One day a man was walking along the beach. In the distance, he saw a figure bending down and then throwing something into the ocean. Upon coming closer, the man saw that the shore was covered with starfish that had been trapped because of the low tide. The man remarked, "There must be thousands of starfish on this beach, you can\'t possibly save enough to make a difference." The young man stooped down to pick up another starfish and said, "It made a difference to that one.""</p>

<p>Maybe we can\'t save every child in Africa, maybe the genocide will continue, but at least we can help one person. One person who may one day grow up to help another. Entire generations of creativity and vitality have been lost in Africa because we didn\'t have the strength to stand up. Either we draw the line now, or we risk another dark chasm in what was once the rich, vibrant history of Africa.</p>

<p>Perhaps the biggest reason why people didn\'t attend was because they didn\'t feel that depriving themselves of a lunch was worth it. After all, does it really matter whether you donate five dollars by sitting in an assembly or just donate five dollars in cash? What many fail to realize is that the act of forgoing a veritable feast transcends monetary value. What the people of Darfur feel is beyond comprehension to even the most empathic of us. The only way we can get a taste of what they feel is if we subject ourselves to an infinitesimal portion of their situation. In depriving ourselves of our usual meal, we hope not only to gain some insight into their plight, but also to spur ourselves to action.</p>

<p>But if you didn\'t attend, please don\'t feel bad, just concentrate really hard in all the excuses mentioned above and concentrate even harder in blocking out the gruesome images of bodies hacked apart, blood soaked earth, and emaciated children. If you succeed, maybe then you\'ll understand how most world leaders have been able to ignore the issue and still look at themselves in the mirror.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>