<?php

$aid = 'aneesh';
$title = 'The Fourth Horseman - Chapter 1';
$cid = c1;
$issueid = i4;
$body = 
'
<h12>Chapter 1 - Enter the Dragon</h12>

<p>"The vell? Where am I?" the youth asked groggily and more than a little confused.  Opening his eyes, he sat up on the bed - surprisingly comfortable, he noted - and looked around at the rather spartan quarters he was in.  Cold steel walls, in a small round room with just enough room for the bed, the small table next to it, a desk on the far wall, and a chair next to the desk - a chair occupied with a young man, perhaps just a few  years older than himself.  Twenty three, maybe twenty four, he thought.</p>

<p>"Oh good, you\'re awake. We were beginning to think we\'d lost you to shock. I hope you\'ll forgive the abruptness, but what\'s your name, and what are your abilities?"</p>

<p><i>Abilities?</i> the youth thought, saying aloud, "I don\'t know what you mean by abilities, but my name is... umm... my name is..."  Frustrated, and irritated that he couldn\'t even recall his name, he added, "I could ask you the same question, and I still want to know where I am."</p>

<p>The young man smirked, but avoided laughing, as he replied, "Of course, I\'m sorry.  It\'s common that people waking after their first jump are disoriented, and after the shock you went through, having short-term amnesia isn\'t entirely unexpected.  Your memories should return more solidly in a little while.  My name is Wes - Wessel Comder, but everyone just calls me Wes or West.  You\'re on planet Sekaii."</p>

<p>"PLANET Sekaii?  As in, another world entirely, not Rrth?"</p>

<p>"That\'s what planet tends to mean, kid."</p>

<p>"That\'s not velling possible, now seriously, where the vell am I?  I\'m not in the mood for games, I\'ve got a splitting headache and I would very much like to know who I am, what happened, and were I am."  He could remember vague details about his life, but nothing concrete; his identity, along with any recent memories, was a blur, however.</p>

<p>"It\'s not only possible, it\'s true... but I can tell you don\'t believe me and won\'t until it\'s proven, so we can get back to that.  As for who you are, we don\'t know.  And what happened... if you have a hard time believing this isn\'t your home planet, you\'re not going to believe that either.  It\'ll be explained later.  Any more questions?  If I can answer them, I will."</p>

<p>"Err... you said something about abilities earlier... what exactly were you asking for?  I can\'t exactly recall what I\'m good at, but if you could tell me what kinds of abilities you mean, I might be able to help more."</p>

<p>"You are thick, aren\'t you?  Your abilities, your powers, what kind of spells-" Wes cut off suddenly, unable to avoid chuckling at the look of sheer incredulousness on the newcomer\'s face.  "You don\'t believe me, do you? Don\'t have magic on your homeworld?  Ah well, there\'s still a chance you can use it even if the force is almost nonexistent on your home.  Not nearly as good as if your home had magic, and even then it\'s not common, but the fact that you\'re here means something, I hope."</p>

<p>"More of this junk about this not being Rrth?  And now magic too, that\'s rich.  This is all really funny and I\'m having a blast, now care to tell me the truth?"  The youth stood, ready to just leave, but felt dizzy the moment he got up.</p>

<p>Wes\'s smirk finally faded, and he looked somewhat irritated now.  "I\'ve been completely level with you, you brat, so shut up and listen!  Try to focus on the area around you, nothing in particular, and see if something feels differently from how it should.  That\'d be the presence of magic - some worlds have it, others don\'t.  We don\'t know why, and I frankly don\'t care."</p>

<p>Despite being pissed off, the newcomer sighed and sat back on the bed, trying to focus on the room.  <i>This is idiotic.  I can\'t believe I\'m doing this,</i> he thought.  Suddenly, he felt as though he was being shocked with an electric current.  "The freg was that?" he asked, standing up again, and feeling even dizzier than before; reluctantly, he again sat back on the bed.</p>

<p>"You felt something?  A surge of energy, maybe, or feeling some sort of presence? A shock, a strange heat, something like that?  That\'s you touching the magic, calling on it."  Wes smiled again.  "From the look on your face, it was a strong feeling, too.  That\'s good, kid, because it means you\'re more likely to be some good at it - and we\'re in desperate need of good mages right now."</p>

<p>"What - you must have shocked me or something, that couldn\'t have been..."</p>

<p>"ALL ACTIVE AGENTS - REPORT TO THE BREIFING ROOM.  SHRODINGER, REPORT TO THE NEWCOMER\'S CHAMBERS AND RELIEVE COMDER," the loudspeaker blared into the room.</p>

<p><i>\'Active agents?  What the freg?\'</i></p>

<p>"Well, looks like I\'m going to be released, then... I\'ll let Shrodinger try to put some sense into you, kid."  Wes walked over to the door and opened it, as a youth perhaps twelve wearing a khaki shirt and shorts walked into the room.</p>

<p>"Yo!  I\'m Schrodinger, nice to meetcha," the boy said, grinning innocently.</p>

<p>"I\'ll leave the new kid in your hands then, Schrodinger."</p>

<p>"No prob, sir!"</p>

<p>The newcomer was slightly confused at the boy\'s entry, but replied, "Hey."  After a moment, he added, "So you\'re another of these nut-cases here to convince me I\'ve got magical powers and am here to save the universe or some crap like that?"</p>

<p>Schrodinger\'s grin widened.  "Well, the magic bit is true, anyway.  Saving the universe not so much - more like multiverse, and you\'d just be one member of just one of the teams of scattered resistance, not some savior or something.  If you agree to sign up, I mean.  But you never told me your name."</p>

<p>"I can\'t remember it."</p>

<p>"Amnesia?  Well, that\'s alright, we\'ll just come up with something to call you for now then!" Shrodinger said, enthusiastically.  "Shrodinger isn\'t my actual name, actually, just the name they gave me when I couldn\'t remember, and I liked it so I kept it.  My real name is Wolfgang.  Wolfgang Blitz, actually."</p>

<p>"Hmm... how would I find out what my abilities are? And what are yours, anyway?"</p>

<p>"My powers?  Line of sight teleportation.  Plus, I can kind of blur the whole life-death thing, raise undead from corpses.  I don\'t really know how it works - I could only do the porting thing back home, the necromancy is new."</p>

<p>With a start, the nameless entrant realized how much he was buying into what the kid in front of him was saying.  The disarming smile and childish enthusiasm made it difficult to believe that Shrodinger was lying.  He was about to say something, when the kid vanished, only to reappear behind him.</p>

<p>"That proof enough for you?  I sure hope so, because I\'m not going to raise the dead for you, Herr Noname."</p>

<p>The title irked the newcomer, who glared at Shrodinger, saying, "Don\'t call me Herr Noname!  Anyway, how can I work out what I can do?"</p>

<p>Shrodinger mused over it for a moment, then replied, "I dunno.  I guess you\'d hafta find out by using them, maybe?"</p>

<p>"How can I use them if I have no idea what they are?" he demanded, again irritated.</p>

<p>The boy only shrugged.  "Beats me, I woke up here just kind of knowing what I could do.  But hey, Mal will be by sooner or later, she\'ll check you up - she\'s the all-purpose medic - and if anyone would know, it\'d be her or the captain.  And you don\'t want to piss off the captain.  The captain can and will make life suck for you.  And I kinda annoyed her when I first showed up, I acted too much like a little kid."  Yawning, he stretched.  "Monitor duty is boooooooooring.  Lets come up with a name for you that we can use instead of Herr Noname.  Just until you remember what your own name is."</p>

<p>"A name?  Hmm..." the nameless newcomer mused over the idea, not entirely sure, before one name stood out solidly enough that it could even have been his own.  "Mordred.  Mordred Draeg."</p>

<p>"Mordred Draeg?"</p>

<p>"Yeah, is there something wrong with that?"</p>

<p>"Nah.  And if the name just came to you, maybe it was a  memory coming back, or something like that?"</p>

<p>"Maybe it is.  The name just feels right." Mordred replied, feeling a little better.  Having a name would help, and it was a good sign that his memory was coming back.</p>

<p>"That\'s good.  But now I\'m bored again.  This sucks, why did I get stuck on monitor duty?  No offense or anything, but watching over you isn\'t the most thrilling of jobs."</p>

<p>Both Schrodinger and Mordred turned as there was a rap on the door.  Shrodinger\'s eyes widened and he gasped.  "Oh, vell..." The handle turned, and the door swung open.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>