<?php

$aid = 'raymond';
$title = 'Movie Review: Capote';
$cid = c12;
$issueid = i4;
$body = 
'
<p>Capote: Good, but not great.</p>

<p>For a while I had been interested in watching all of the Oscar Best Picture nominees. I had already seen 2, Munich and Good Night and Good Luck, but I still had 3 left. So, I went off and rented Capote. Most people have heard of it, but nobody I know had actually seen it. I figured it would be interesting seeing a best picture nominee nobody had seen. Well, I saw it, and I must say it was pretty good.</p>

<p>The movie is a true story about Truman Capote him writing his famous book <u>In Cold Blood</u>. It revolves around two men who kill an entire family while robbing a house. The culprits are caught and sentenced to death, and the movie shows Capote interviewing them while they are on death row as research for his book.</p>

<p>What I found interesting about this movie is that it does not explore Truman Capote\'s moral dilemmas until 10 minutes before it ends. Capote shamelessly exploited two death row inmates in order to make money off of his book. The movie portrays him as a selfish, heartless man who cares more about his book than the lives of the people he is exploiting. At one point, he gets the death row inmates a decent lawyer for an appeal. This seems like a benevolent act until he explains his motives: to keep them alive until they tell him what happened the night of the murders. After he gets this information out of them, he expresses his desperate desire for their appeal to be rejected so that his book can end on the right note: with their execution. Capote is a thoroughly reprehensible character who, sadly, actually existed.</p>

<p>Oh, and I forgot to mention, Capote was a homosexual. Wow, I love how politically incorrect that is. In Hollywood, you can have the protagonist be a homosexual or an evil character, but not both. Depicting a homosexual as evil would normally be considered intolerant and mean. However, this guy actually existed, and making an accurate movie about him would require this depiction. You have to love it.</p>

<p>Now, I said before that Capote undergoes a character transformation 10 minutes before the film ends. And he does. What happens is the inmates get their final appeal rejected. Capote initially said this is exactly what he wanted, but when he gets a call telling him this, you see him begin to realize that he is nothing but a greedy scumbag. He comes to this realization more and more while watching the inmates get executed. But it isn\'t until after the movie is over, before the credits start rolling where you see some black text explaining that Capote had many regrets from publishing the book and that he eventually drank himself to death.</p>

<p>The movie itself is pretty good, but what keeps it from being great is the incredibly slow beginning. I guess the best way to describe the pacing is that it\'s like Fargo without the comic relief. The editing is pretty similar as are the landscapes. But without comic relief, the beginning moves at a snail\'s pace.</p>

<p>However, aside from the slow beginning, the movie is very good. Philip Seymour Hoffman\'s depiction of Truman Capote is superb. He definitely deserved that Oscar. He perfectly contrasts Capote\'s ruthlessness with his innocent appearance and childish voice. Highly recommended.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>