<?php

$aid = 'editors';
$title = 'Editor\'s Note: Issue 4';
$cid = c19;
$issueid = i4;
$body = 
'
<p>Hey everyone!</p>

<p>Before I start on the Editor\'s note, I\'d like to clear up a few questions:<br/>
<br/>
1. Yes, we are changing the domain name. It is now <a href="http://www.amalgammag.com">www.amalgammag.com</a>.<br/> 
<br/>
2. The reason we\'re doing only one issue a month is because, frankly, not all of us have time to write much more. Although you see several great things written by the same author in one issue, it\'s all generally submitted in the last four days. It also takes time for me to read through everything and for Neil to post it.<br/>
<br/>
3. There is indeed going to be a clearer submissions page. But for now, if you want to submit, just email your work to highschoolmagazine@gmail.com.<br/>
<br/>
4. If you would like to write regularly, please subscribe to the staff-list. That\'s how we distribute the deadlines and give topic suggestions.</p>

<p>Now...</p>

<p>Extra! Extra! Read all about it! Amalgam Issue 4, finally released!!! That\'s right, folks, it\'s finally out! I know you\'ve been waiting some time, and it\'s here!</p>

<p>This month, I found it pretty difficult to find a few articles that just seemed exceptional among the others - so much so that in the end, I really couldn\'t pick only two. The quality of the articles this issue are excellent; the writers have done an impressive job.</p>

<p>Before I tell you all to go and read to your heart\'s content, I have a small story for you (as well as what I would consider a treat).</p>

<p>On Sunday, the second day of Spring Break, one of my friends sent me the link to <a href="http://www.foon.co.uk/farcade/hapland3/">Hapland 3</a>. I acutally spent an hour trying to figure out this game before going to the cheat codes (provided by said friend). I still couldn\'t beat the game. However, it did provide a few hours of entertainment for me, and I hope it does for you as well. </p>

<p>By the way, the treat was the link to the game. Now, happy reading!</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>