<?php

$aid = 'shan';
$title = 'A Bar-None Solution to Stress';
$cid = c13;
$issueid = i4;
$body = 
'
<p>The school bell rang (why do they call it a bell, it\'s just a beep)
signaling the end of another grueling school day. A girl, who we\'ll
call Jane, walked slowly out of her class clutching an armful of
books. As she trotted over the lawn towards her car, parked behind the
\'Don\'t walk on the grass\' sign, she sighed with frustration at the
ridiculously heavy backpack weighing her down. Her day was filled with
four AP classes, two honors classes, and two clubs after school. To
add to it, she was a junior, it was a week before SAT, and she also
needed to prepare for AP exams and SAT II exams. To top it off, her
parents wanted her to draft a letter to a professor at Stanford about
internship opportunities for the summer. She drove home and walked
into her room. The pressure was building up inside her mind, she
needed to escape. Twenty minutes later, all thoughts about school or
internships were out of her mind.</p>

<p>Music. Why do people listen to music? To relax? To show off knowledge
of lame lyrics? To drown out editors who harp on people to write
articles? Most students listen to music at some point during the day.
A great percentage of the teenage population in the US owns iPods or
alternative music players. However, not everybody truly appreciates
just what it is that music does for us.</p>

<p>Yes, yes, it\'s supposed to make us better at math and all that jazz
(lame pun, I know). But today\'s music selections can also help us with
the stress of a student\'s life, like the anecdote above. Sadly, some
teenagers turn to drugs and alcohol to get away from the problems and
trauma of pressure (academic pressure, I mean). People may listen
casually to music from time to time, but not really put their mind to
it.</p>

<p>If you really put your focus into listening to the music, trying to
pick out the individual melodies and harmonies, trying to listen to
the drums and the other various instruments, sooner or later, you WILL
lose grasp of reality. Try to become so proficient at this, so that in
time, anytime you want to veg out, start the song in your head.
However, this works only with songs that have a significant musical
background. Some rap and hip-hop contain just a drum beat and a
baseline. While that might be enough to occupy a squirrel\'s focus, it
certainly isn\'t enough for yours. At least, I hope not.</p>

<p>The need to lose terms with reality from time to time is perfectly
understandable, everybody has stress and pressure. It would be nice if
we could get away from that from time to time without any consequences
or guilt. Also, as my parents remind me constantly, it\'s been proven
to improve math ability. This, in my opinion, is even more important
(I\'ve been told that\'s how I feel).</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>