<?php

$aid = 'eric';
$title = 'Procrastination';
$cid = c15;
$issueid = i4;
$body = 
'
<p>Ah, procrastinating. Undoubtedly a favorite among high school students. In fact, it\'s one of the only things they do, next to gaming and cramming.</p>

<p>So you\'ve got four weeks to write up an essay. It\'s easy, right? I mean, in eighth grade, we only got like two days to write one up. So why start now, right? Seriously. What kind of idiot starts an essay due in four weeks? And are you going to do that essay when there are better things to do? No way. you\'d rather eat, sleep, play video games, hang out with your friends, pick your teeth, etc., etc. And okay, so you don\'t do it for another, say, 3 weeks. Your life is happily cruising along. The essay is the only homework in the class, so for the last few weeks, you\'ve been living the easy life full of money and girls (metaphorically). And you know, you\'re going along your merry way when you realize "Oh shit! The paper\'s due tomorrow!"</p>

<p>But hey, that\'s what, twenty-four hours! Plenty of time, and you\'ve got lunch to do it! And, oh wait, your free period! So it\'s all good. So that night, you start on it. And you know it\'s just the biggest essay of the year, but even if you fail, you know you can just bribe the teacher, right? So you\'re working at your leisurely pace, while also answering all of your AIM buddies in complete sentences and even copying and pasting stuff into Microsoft Word to make sure you\'ve spelled everything correctly. So that\'s taken care of. Then you\'ve got the punk rock music blasting because it makes you think better and plus, you totally need to memorize those lyrics for the rock concert with your girlfriend tomorrow. And so you\'re writing along and BOOM. Done.</p>

<p>Huh. That was easy, wasn\'t it? Definitely. And just imagine, this essay was supposed to be done over FOUR WEEKS! And while you\'re laughing at the teacher and congratulating yourself, you\'re reading over your perfect essay. That\'s when you realize that half of your essay is the lyrics to the songs you were listening to. You scroll down the page and read "Sir Gawain is depicted as the epitome of A MOTHERF**KING ASSHOLE...WHO LOOKED LIKE A GIRLFRIEND THAT I HAD IN FEBRUARY OF LAST YEAR." Then you realize that you weren\'t even listening to The Killer\'s "Somebody Told Me" or any song with swear words in it.</p>

<p>This is when one of the voices in your head goes "Sorry, but that song was SO cool. I just HAD to put that in there." Well, at this point, you\'re probably questioning your sanity and wondering if your parents were right when they said you were schizophrenic. In fact, you\'re starting to recall instances where you had the urge to tell the teacher to go to hell and suppressed it by saying "Shut up, Bob!" Oh, and that time you were getting every single answer right on the homework? That was probably Bob too. And right about now, you\'re hearing conversations in your head and hoping they\'re coming from the next room.</p>

<p>That\'s when you know you should have taken your pills in the morning.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>