<?php

$aid = 'eric';
$title = 'Disadvantages of Sleep: Pro-Shower';
$cid = c15;
$issueid = i4;
$body = 
'
<p>I\'m what you might call a shower freak. I\'m the guy who goes "OMG, there\'s a speck of dust on my arm! To the shower!" Yeah, that\'s right. But seriously here, who can\'t resist the temptation of a shower every few hours? After a stressful day, all you can really do is fight it off with coffee or succumb to the slow seduction of the bed, or for those who are too sleepy to make it that far, the floor. And after a few days of no sleep because of that stupid study of theater project, who can resist the temptation of sleep?</p>

<p>Ah, sleep. It starts with a glance. Just one. But that\'s when it gets you. You try to concentrate on the stupid math problem you\'ve been trying to figure out for the last 5 hours, but all you can think about is the bed, and it\'s not helping that, thanks to your parents\' dysfunctional feng shui, the bed is in plain view. And you\'re sleepy. And bored. Not a good combo. "x...equals...2, y equals 3...z equals....zzzzzzz." Before long, you\'re dozing off, convinced that you will be able to make up for the 36 problems you haven\'t done when you\'re fired up and alert in a few hours.</p>

<p>Then of course you wake up and, feeling charged, bolt upright and start on that problem. And it seems easy. 2+3? That\'s 5. And 1+2? 3. And that\'s when you realize that in your zombie-like sleepiness, you\'ve just done your 6-year-old brother\'s homework. AGAIN. Then you look at the clock. It\'s 3:00, so you\'ve got plenty of time. But then, of course, because God hates you, it\'s only 3:00 because the clock has stopped. And then you realize you\'ve run out of toothpaste. And soap. And, while we\'re at it, running water.</p>

<p>But, my friends, there\'s a simple solution to all of this. No, I\'m not about to suggest running out to your local neighborhood well to fetch water. No. the solution is: the shower! Well, you didn\'t expect anything different, did you? Of course! Because once you start to feel that first wave of drowsiness (not drug-induced, I hope), you know you can safely march off to the shower and come back feeling fresher and [for all of you females above 30 years of age] younger too (which I guess is a cheaper alternative to plastic surgery). And really, I don\'t really want to go into the intricacies of the effect of individual droplets stimulating the human nervous system, so I\'ll leave you to try it for yourself.</p>

<p>Just a note though. Showering is NOT a known panacea, although really, it almost is.<p>

<p>Sleepy? Shower.<br/>
Bored? Shower.<br/>
Complete and utter stupidity? Shower.<br/>
Marriage problems? Shower.<br/>
Suicidal tendencies? ...not advisable.</p>

<p>Well, I\'m off now. To shower, of course. Enjoy.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>