<?php

$aid = 'sharon';
$title = 'One Dollar, Please.';
$cid = c3;
$issueid = i4;
$body = 
'
<p>I wonder what this dollar bill has seen<br/>
What the little rip on the corner must mean<br/>
It seems a dollar bill goes everywhere<br/>
That we want to be<br/>
<br/>
Unlike a credit card, a dollar bill goes places<br/>
Sees new things, sees new faces<br/>
If only I could somehow know<br/>
What this dollar bill has seen<br/>
<br/>
Perhaps it fell out of Bill Gates\' pocket<br/>
Maybe it was stuffed in a donation bucket<br/>
Maybe a little girl who wanted a balloon<br/>
Found it on the ground at Disneyland<br/>
<br/>
Maybe it slithered out of a burglar\'s grasp<br/>
As he struggled with a Gucci purse clasp<br/>
Maybe it was in a policeman\'s fist<br/>
As he paid for his donut at the donut store<br/>
<br/>
If dollar bills could speak<br/>
I would ask<br/>
<br/>
Where have you been?<br/></p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>