<?php

$aid = 'raymond';
$title = 'Movie Review: V for Vendetta';
$cid = c12;
$issueid = i4;
$body = 
'
<p>I figured you all have heard me rant on about old crap you\'ve never heard of long enough, so I decided to review something more recent. So, the movie of the day is V for Vendetta, also known as the most over praised film I have seen this year. Rotten Tomatoes rates it at 76%, which, for the website, is very good. IMDB currently has it at 8.1/10 and number 241 out of its top 250. Rotten Tomatoes\' consensus explains it as:<br/>
"Visually stunning and thought provoking, <i>V For Vendetta</i>\'s political pronouncements may rile some, but it\'s story and impressive set pieces will nevertheless entertain."</p>

<p>Ok. Let me explain something. This movie has NOTHING VISUALLY STUNNING ABOUT IT WHATSOEVER. If you want to see a visually stunning movie, watch Blade Runner. It was made 24 years ago and still has some of the GREATEST visual effects of all time. V for Vendetta doesn\'t even qualify as a futuristic movie; it merely takes place in the future. The camerawork was pretty standard, and there wasn\'t anything particularly interesting about the cinematography.</p>

<p>Thought provoking? It is no more thought provoking than the usual dystopia movie. A movie was made about 4 years ago which had the exact same political message. The movie is called Equilibrium, which is quite a bit better than this.</p> 

<p>Political pronouncements may rile some? What is wrong with our society? This movie is anti-fascist and anti-corruption. What the hell is wrong with this political pronouncement?</p>

<p>The story is EXACTLY the same as any sci-fi movie EVER MADE. Basically, there is a guy who seeks to end an evil dictator\'s reign on post-apocalyptic London. Hmmm... where have I heard this before? OH I KNOW, this small film called TOTAL RECALL, where Arnold Schwarzenegger attempts to end an evil dictator\'s reign on Mars.</p>

<p>Impressive set pieces? They seemed pretty standard to me. Sure, there are several tall buildings, and a few of them even blow up, but nothing incredibly impressive.</p>

<p>Now, is this a bad movie? Not at all. It most regards, this is a more than decent comic book movie. I\'d probably recommend it to the typical action fan. However, what I don\'t understand is all the praise it is receiving. It is simply a typical dystopia movie with a bit more dialogue than most.</p>

<p>Ah, dialogue. Now, one thing that I did not like about the movie was the protagonist, who is named V. Sure, he fights well, and the last fight scene was pretty cool (and bloody), but he is also, to be blunt, a preachy blabbermouth. The first thing he does after beating the crap out of a bunch of people is break the record for the number of times a word starting the letter "v" is used in a single sentence. I don\'t know about you, but I found this incredibly irritating. I was pretty close to shouting at the screen, telling him to shut up. V blabbers on and on several times in the movie. Some mistake his dialogue as being meaningful; I see it is as just plain annoying. V usually says something about how the government is corrupt and that a revolutionary is needed to help overthrow it, but I\'d argue that V could have made his point better if he simply used fewer words.</p>

<p>But overall, the movie is fine. Just don\'t listen to all of that trash about this being an intelligent, sci-fi thriller with great set pieces. It\'s not. It is no more than a standard dystopia future movie with some cool fight scenes and interesting characters. And Natalie Portman shaves her head.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>