<?php

$aid = 'raymond';
$title = 'Movie Review: Murderball';
$cid = c12;
$issueid = i4;
$body = 
'
<p>Hey, scumbag. Yes, YOU, SCUMBAG!</p>

<p>Let\'s take a look at a simple scenario:</p>

<p>Hollywood decides to make two movies. One is a piece of crap superhero movie where four people manage to find the meaning of teamwork and use their superpowers to do good. They slap it with a big budget and lots of effects and "hot" actors and actresses.</p>
<p>Hollywood also decides to make a second movie. However, it\'s a documentary that explores the lives of quadriplegics and how they adapt to living in a wheelchair. Some mourn the rest of their lives while others seek refuge in a sport called wheelchair rugby, or murderball.</p>

<p>Now, which movie do the studios think will make more money?</p>
<p>Obviously, they count on the public being incredibly stupid and watching crap like Fantastic Four and overlooking quality documentaries like Murderball. And this is exactly, and I mean EXACTLY, what happened.</p>

<p>While millions of pathetic losers lined up to see Fantastic Four, only several hundred understood the brilliance behind Murderball and went to see it.</p>

<p>Now, how many of you have seen Fantastic Four?</p>
<p>Now, how many of you have even HEARD of Murderball?</p>

<p>Get the point?</p>

<p>Murderball explores the life of quadriplegic rugby players who elaborate on their lives and the influence of the sport on them. The star player on the American Team is Mark Zupan, who is more or less a jock. And an asshole, apparently. Some of his friends comment on how he was an asshole before he was injured, and just as much of an asshole after. Zupan seems to be the typical jock. He parties, drinks, and has fun with his girlfriend.</p>

<p>There is one interesting segment in the film where they talk about girlfriends. Apparently, whenever a girl talks to a quadriplegic, the question in the back of her mind is "Can you still do it?" Usually the answer is "yes," and the girl will feel a need to nurture this little quadriplegic as well as screwing him every once in a while.</p>

<p>Zupan was apparently paralyzed in a car accident where he was riding in the back of a truck while his drunk best friend, Christopher Igoe, crashed, causing Zupan to fly out and break his neck. It isn\'t until nearly 20 years after the accident until Zupan finally forgives him and they meet up again. Igoe is incredibly supportive of Zupan\'s wheelchair rugby career and they manage to get back on excellent terms again.</p>

<p>There is another segment on Joe Soares. During the 90\'s, he was one of the greatest wheelchair rugby players in the world. However, as he aged, his skills deteriorated, and one day, he didn\'t make it to the Paralympic team for the US. Infuriated, he joined the Canada team as a coach and used his immense knowledge to help lead Canada to victory against the US twice.</p>

<p>The film also explores Soares\' family life. He lives in a happy family, more or less. He has a wife and son, and his son is the typical nerd. He gets straight As at school and is bullied by stupid kids. He also plays the viola, which pisses Soares off a bit. Soares wants his kid to be the ideal athlete, like he was, not a music loving nerd. It takes Soares a heart attack to realize that he needs to accept his son for who he is and to support him at whatever he wants to do. In one particularly moving scene, Soares rushes back from an important game in Europe to see his son\'s viola concert.</p>

<p>There are several other parts of the movie that I don\'t have time to get into, including a segment about a recently crippled daredevil who learns about wheelchair rugby, but to find out more, rent the movie at your local blockbuster. At heart, it is an interesting character study on real wheelchair bound people. While the story seems a little cliched, keep in mind everything that happens in the movie actually happened.</p>

<p>Highly recommended to anybody who isn\'t a complete idiot.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>