<?php

$aid = 'raymond';
$title = 'Movie Review: Total Recall';
$cid = c12;
$issueid = i4;
$body = 
'
<p>Hi. My name is Raymond, and I will be another film critic around here. Allow me to introduce myself. I am a sadistic high schooler with a particularly bizarre taste in movies. I tend to prefer violence and blood over unimportant things, like plot and character development, but I do prefer a quality film every now and then. It is no secret that my favorite movie is Fargo, but I like a wide variety of genres as well. I used to be the biggest action fan you ever could have known, but my tastes are beginning to evolve and now I\'m beginning to warm up to character movies and romances. But whetever. All this is boring, and I know you all want me to get to the review. So, the first movie I shall review for this pathetic little internet site will be... TOTAL RECALL.</p>

<p>Now most of you are probably wondering "what the hell is this." Well, it stars Arnold Schwarzenegger for one thing. This means it is filled to the brim with violence and blood and guts and severed limbs. In fact, this is probably one of Arnie\'s most violent movies. If violence is not your cup of tea, then I suggest you skip it. But, if you go in expecting a typical piece of crap action vehicle, you\'ll be pleasantly surprised.</p>

<p>Now, Arnie\'s films are known to be rather campy and bad. *cough* Commando *cough*. However, screenwriter Ronald Shusett managed to make a tightly paced sci-fi thriller based off of Philip K. Dick\'s short story We Can Remember It For You Wholesale. After 40 drafts of the script were written, the now extinct production company Carolco purchased the rights and hired Paul Verhoeven, famous for his magnificent film Robocop, to direct the film. Now one thing you get when hiring Verhoeven is a very edgy, violent, and borderline R rated movie. In fact, the MPAA threatened to slap the film with an X rating if Verhoeven didn\'t cut down the violence. The point is, this movie is VIOLENT, and I mean VIOLENT. One of my favorite scenes in the movie is where Schwarzenegger uses an innocent bystander to shield himself from bullets. I have yet to see another movie where you see this happen to a RANDOM BYSTANDER. Needless to say, the guy gets shot to bits and it is all very, very funny.</p>

<p>Now, I have given you history and a little glimpse into the violence of the movie, but now you are all probably wondering "what the hell is this movie about?" I\'m trying to avoid spoilers here, so bear with me. Well, Schwarzenegger plays Douglas Quaid, who keeps having dreams about Mars. So, he goes to this facility that is able to implant memories of a Martian vacation. Needless to say, things go horribly wrong and Quaid ends up flying to Mars for real, where he encounters an evil dictator bent on killing him. This might not sound very interesting, but it is actually pretty complex. But I don\'t want to spoil the movie for you guys, so just see it for yourself.</p>

<p>Overall, this is a tightly paced action sci-fi movie with great visual effects, awesome action, and even an intriguing plot. Highly recommended for anybody who can stomach strong violence.</p>

<p>And now for some Q&A:</p>

<p>So, how many people die in this movie?<br/>
76. Yes I counted.</p>

<p>Wow, what a loser.<br/>
Yep.</p>

<p>So, this is a Schwarzenegger movie with an actual plot?<br/>
Yep.</p>

<p>You have got to be shitting me.<br/>
I\'m not. It\'s a pretty complicated story and deals with stuff like corrupt governments, reality vs. dreams, and all that kind of good stuff.</p>

<p>Are there any other cool death scenes?<br/>
Other than the bystander scene, there\'s this one part where this guy gets his arms ripped off by an elevator. OOO And apparently if you are sitting on Mars without any equipment, your eyes begin popping out and your skin puffs up. </p>

<p>On a scale of 1-10, how would you rate it?<br/>
11.</p>

<p>Are you serious?<br/>
I love this movie, man.</p>

<p>Ok fine. Anything else you want to add?<br/>
Well, it\'s an awesome movie. Watch it!</p>

<p>Is there something you\'re not telling us?<br/>
Nope.</p>

<p>Really?<br/>
Ok, ok. There\'s this one semi-creepy part where this woman has three breasts...</p>

<p>OH MY GOD THAT\'S SICK!!!!<br/>
Grow up, loser.</p>

<p>Is it bad?<br/>
Not really, no. </p>

<p>Ok, phew. Anything else?<br/>
Not really. As I said, if you can stomach violence, SEE IT. </p> 
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>