<?php

$aid = 'shan';
$title = 'The Presidential Question';
$cid = c4;
$issueid = i4;
$body = 
'
<p>While visiting India, George Bush is invited to tea
with  President Abdul Kalam.</p>

<p>He asks Kalam what his leadership  philosophy is. He
says that, it is to surround himself with 
intelligent people.</p>

<p>Bush asks how he knows if  they\'re intelligent.</p>

<p>"I do so by asking them the  right questions," says
Kalam. "Allow me  to demonstrate."</p>

<p>Bush watches as Kalam phones Manmohan  Singh and
says, "Mr. Prime Minister, please answer this
question: your  mother has a child, and your father
has a child, and this  child is not your brother or
sister. Who is  it?"</p>

<p>Manmohan immediately responds, "It\'s me, Sir!"</p>

<p>"Correct. Thank you and good-bye, sir,"says  Kalam. He 
hangs up and says, "Did you get that, Mr. Bush?"</p>

<p>Bush nods: "Yes, Mr. President. Thanks  a lot. I\'ll
definitely be using that!"</p>

<p>Bush,  upon returning to Washington, decides he\'d
better put the Condoleeza Rice to the test. Bush
summons her to the White House  and
says, "Condoleeza, I wonder if you can answer a
question for  me."</p>

<p>"Why, of course, sir. What\'s on your mind?"</p>

<p>Bush poses the question: "Uhh, your mother has a 
child, and your father has a child, and this child
is not your   brother or your sister. Who is it?"</p>

<p>Rice was  puzzled and finally asks, "Can I think
about it and get back to you?" Bush agrees, and Rice
leaves.</p>

<p>Rice immediately calls a meeting of senior senators,
and they puzzle over the question for several hours,
but nobody can come up with an  answer.</p>

<p>Finally, in desperation, Rice calls Colin Powell and
 explains the problem.</p>

<p>"Mr. Powell, your mother has a  child, and your
father has a child, and this child is  not your
brother or your sister. Who is it?"</p>

<p>Powell  answers immediately, "It\'s me, of course."</p>

<p>Much relieved, Rice  rushes back to the White House,
finds George Bush,and exclaims, "I know the answer,
sir! I know who it is! It\'s  our Colin Powell!"</p>

<p>And Bush replies in  disgust, "Wrong, it\'s  Manmohan
Singh!"</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>