<?php

$aid = 'gwynnie';
$title = 'Addiction';
$cid = c1;
$issueid = i4;
$body = 
'
<p>I don\'t know why I do this. My mind says it\'s bad, my heart says it\'s bad, I even hear myself say the words out loud - this is wrong.</p>

<p>But then why does something so wrong feel so good? A prick of pain and then cool ecstasy floods my veins, coursing through my blood. So I can\'t remember what happened the night before when I wake up - but isn\'t living in the moment, living off that perfection, isn\'t that okay?</p>

<p>It\'s so wrong, but it feels so right...</p>

<p>Sometimes I find myself lying on the side of a road, my face scratched up with my shirt ripped open and cuts bleeding sluggishly. I don\'t know how I got them, but I\'m just too tired to care. So I crawl my way to the nearest phone booth and call a friend to take me home.</p>

<p>Cara used to be my best friend, but when I started using, she got angry and soon she couldn\'t be in the same room without yelling at me. When she walked in on my sticking the needle into my arm, she burst into tears, told me that she hated me for doing this to myself, and left. I haven\'t seen her since.</p>

<p>Part of my mind says I should care more, that maybe Cara\'s right. She and I used to plan to go to the same college, both major in Fine Arts and teach at a top school together. The only thing I\'ve painted in the last six months didn\'t make sense even to me. A jumble of colors thrown onto a canvas in frustration that I wasn\'t inspired - that I didn\'t want to paint anymore.</p>

<p>God it feels good. All my worries evaporate and there\'s this feeling of just being, a happy contentment that stems from a small syringe. I\'m careful - I never take more than my limit, and I never reuse needles or take them from other people. So what\'s so wrong with it, if I\'m cautious? I can take care of myself.</p>

<p>But then I remember what Cara yelled, and this feeling of guilt starts choking my heart.</p>

<p>"Gabby, you\'re going to get hurt! What if you try to drive and get into a car accident or some guy picks you up? What then? What then, Gabby!"</p>

<p>She stood in the doorway, tears pouring down her angry and scared face, but I couldn\'t look at her. It was like I knew that it was wrong, that she was right. But at the same time, those waves of that floating, dream-like state were closing in. I don\'t know how much time passed before I realized she had left.</p>

<p>I could stop this now. Really, I could.</p>

<p>I just have to throw away the needles, throw away the drugs, throw away my money or give it to someone who won\'t let me have it unless it\'s for food. Therese says that rehab is helping her a lot; maybe I should try it out.</p>

<p>But then again...</p>

<p>That means waking up to the real world again and realizing that it\'s full of rage and hate and prejudice. People don\'t even have a reason; their beliefs are unfounded, their disgust mindless.</p>

<p>So I\'ll stay with my constant companion, my friend through every storm, my little needle. It won\'t ever hurt me; it loves me like I love it. Give a little, get a lot.</p>

<p>I know why I do this. My mind says it\'s good, my heart says it\'s good, and as I load up another dose and shoot up, I hear myself say the words out loud.</p>

<p>This is right.</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>