<?php

$aid = 'shoshana';
$title = 'Ode to a Queen';
$cid = c3;
$issueid = i4;
$body = 
'
<p>Drag queen<br/>
Beautiful woman<br/>
Strong<br/>
Determined<br/>
Lovely<br/>
In the very<br/>
Contrary-ness<br/>
Of her existence<br/>
As herself<br/>
Despite society<br/>
Not to spite<br/>
Society<br/>
Just who she feels<br/>
Inside and out<br/>
Dance with me<br/>
Nothing else matters<br/>
You<br/>
Me<br/>
The music<br/>
That moves<br/>
Us<br/>
Nothing else<br/>
In that moment<br/>
Exists<br/>
Just us<br/>
Bathe in your beauty<br/>
Plant in the sun<br/>
No one can<br/>
Take this away<br/>
This moment<br/>
Your beauty</p>
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>