<?php

$aid = 'neil';
$title = 'Roots - Prologue, Chapter 1';
$cid = c1;
$issueid = i4;
$body = 
'
<h12>Prologue:</h12>

<p><b>World Peace Corps. Convention - Jakarta, Indonesia<br/>
Monday, November 13 - 18:01:23</b></p>

<p>A man in his late forties paced back and forth in a giant ballroom, stress and frustration clearly visible in the wrinkles on his forehead. Exquisite ornaments and fabric hung from the beautifully painted walls and everything seemed prepared to perfection, with the exception of the middle-aged man, who appeared to be at the point of ruin. His tie hung loosely around his neck, his coat carelessly tossed aside, and his dress shirt hanging open.</p>

<p>"I\'m gonna get some fresh air, Larry," he reported to his companion in the room before heading towards a side door that led to a back alley. Immediately, he was besieged by low-life scum looking for a quick buck. Brushing them off and pushing his way through the small group, he gasped in panic as he spotted three members from the local gang heading his direction. If this alley was like an eco-system, the drug dealers and prostitutes that filled the alleys at all times were at the bottom of the food chain, with the "normal" civilians in the middle, the gang members just above them, and the warlords at the top.</p>

<p>This poor man, living in downtown New York and rapidly falling into greater debt every day, was about to take an even deeper plunge. He owned his own pizza parlor only two blocks from his current location, called Roberto & Pablo\'s Pizzeria. His wife had left him, taking his life\'s savings and his children, leaving him nothing, except the small, dingy apartment. As a result of the heavy blow, Roberto had taken to indulging in drugs, ecstasy being his favorite, and alcohol.</p>

<p>"Well, well. What do we have here," one of the members mused, eagerly anticipating the events to unfold. Roberto took two steps back, inadvertently cornering himself between a wall, a dumpster, and the group of bloodthirsty teenagers. He felt a metal baseball bat swing out and break through his rib cage. While collapsing from the pain of the initial blow, he saw someone reveal a switchblade from the corner of his eye. A hand grasped his neck and pulled him off the ground, slamming him against the wall and holding the knife to his neck in a threatening fashion. Roberto realized that the blade was held at the wrong angle and one simple maneuver on his part could disarm the careless boy.</p>

<p>"Amateurs," he thought to himself, considering the notion of dispatching all three of them with one swift blow. He was confident he could kill all three without a sweat, but fear of the rest of the gang kept him in check. Having his throat slit now was much better than what he would suffer if the older members of the gang hunted him down. He closed his eyes and awaited what he expected to be the last moments of his life.</p>

<p>He thought about the country that had once been considered the greatest in the world many decades before and how it had become a breeding ground for filth and death. He remembered the days when corporate America thrived due to the honest, working American citizen, rather than the shady, black-market deals of the underworld.</p>

<p>Everything was run by the ways of the underworld now. There was no need for government or law. Power and wealth rested only on one\'s influence over the warlords. People were bought, controlled, and sold with fear and the warlords commanded the most fear above all others.</p>

<p>Roberto thought about the time when society had a police force it could depend on to save people in situations like the one he found himself in currently. But after the majority of the police force was bought out and corrupted, the remaining cops were forced to retire out of fear for their lives and their family\'s lives. Since then, the police department had been entirely dismantled and nothing but the memories of a utopian nation ruled by laws and justice remained.</p>

<p>"How did we go from the peak of our civilization to this far low?" he wondered. Nobody knew for sure, but there were many theories.</p>

<p>Roberto opened his eyes just in time to see the blade thrust into his throat. Blood spurt onto the hand holding the knife, and his vision faded to darkness. The pain slowly numbed and then he felt nothing...</p>

<p>The movie reel stopped rolling and the room was engulfed in complete silence. Suddenly, thunderous applause broke out amongst the audience and the keynote speaker for the day got up and approached the podium.</p>

<p>Clearing his throat, he began, "Now I want you all to take what you have just seen and heard and apply it to your everyday life. This isn\'t just a Hollywood film. This is real life. People die like this every second! If we don\'t stop the violence on our streets today, tomorrow we will all just be corpses!" With a momentary pause to let it all sink in, he continued, "Thank you all for attending the World Peace Corps. Convention. I\'ll be around here all night if you have any questions. Once again, thank you." With a final bow, he headed towards his seat, greeted by a standing ovation from the sea of nameless faces.</p>

<h12>Part 1:</h12>

<p><b>Fort Geroldy - Nebraska, USA<br/>
Tuesday, November 14 - 13:42:05</b></p>

<p>The walls reverberated with a loud thud. Sector J4 blipped on the screen for a brief second.</p>

<p>"Should we investigate?" a voice questioned, cutting through the deep silence in the large, circular room, plastered with plasma screens across every inch of wall. This was not one\'s typical room. It had computers that ran 24/7 with two separate backup power supplies dedicated to each computer. Each screen monitored a different aspect of the compound. However, not a single wire was visible. Everything was either tucked away behind the bullet and sound-proof walls designed with ten inches of titanium alloy, or transmitted wirelessly across a large network of routers, servers, and proxies to make the signals almost impossible to trace. Almost.</p>

<p>The only openings in the room were several ventilation holes too small for anything living to fit in and an electronically locked door. The ventilation shafts were monitored at all times on one of those many plasma screens in the circular room. The electronic lock was composed of a biometric keypad that had a fingerprint scanner hidden underneath the numbers. Anybody planning on watching the key combination being inputted and then re-inputting it later would set off an alarm as soon as the fingerprints did not match the one\'s on file for authorization. If that wasn\'t enough, every possible corner was carefully monitored and no known blind spots existed from the surveillance cameras.</p>

<p>A hoarse, older voice responded after a momentary pause, "Probably just a glitch in the system. It never happened."</p>

<p>"Sir? Just send one man, sir. As you always say, better safe than sorry."</p>

<p>The senior officer shot a glare at the lieutenant that would have paralyzed any other man with fear. But the lieutenant simply stared back.</p>

<p>Despite the relatively large age difference, the two men sported similar builds. The older was somewhere in his seventies and had a tall, muscular frame, while the younger was in his early thirties and had a slightly shorter, more slender body. Although they commanded equal respect from those around them, the senior officer preferred to think of himself as the master and the lieutenant as the apprentice, and, therefore, always expected more respect from him. The young man let the old fool enjoy his days of power and control, as he knew they were numbered.</p>

<p>"Are you questioning my orders, boy?" he grunted, with a mixture of anger and shock. Who could be so naive as to think they could challenge him?</p>

<p>The younger maintained eye contact, but remained silent. It was only a matter of time until the apprentice became the master.</p>

<p>Astonished by the boy\'s confidence and determination, he granted him permission to send a search squad to investigate the occurrence.</p>

<p>After some shuffling of papers and typing, the intercom beeped audibly and spat out a muffled "Roger that."</p>

<p><b>U.S. Base of Operations Camp - Herat, Afghanistan<br/>
Sunday, November 12 - 8:27:56</b></p>

<p>Adriana ripped out her sidearm from its holster. It was a small Beretta 93R pistol, but it had enough firepower to incapacitate whoever was outside the camp.</p>

<p>She could hear gunshots outside and the distinct yelling of enemy combatants as they sprayed bullets from their imported AK-47 rifles. She knew the ground would be littered with bodies from both sides across the sides of the hill that the camp was located on. U.S. military personnel fired back with whatever they had on them. Most were using small pistols similar to the one in Adriana\'s violently shaking hands. She had never been in an actual firefight before and if somebody were to see her know, they would think she suffered from severe Parkinson\'s disease.</p>

<p>A US soldier collapsed through the doorway, shrapnel from a nearby grenade lodged in his right leg and torso. As blood drenched the dirt floor and the ground changed color, the soldier\'s shrill screams of anguish and torture rang through the air. Terrified of the prospect of hopelessly watching a fellow soldier die before her, Adriana started screaming "MEDIC!" into the midst of the chaos, but a grenade exploding outside of her tent drowned out her cries of help.</p>

<p>Realizing that the soldier had gone limp and was no longer responding to any verbal or visual forms of communication, Adriana assumed he had either fainted from extreme blood loss or was dead. Remembering the lessons she had learned from her drill sergeant at boot camp, Adriana regained her composure and peered out through the tent entrance. Several bullets whizzed by only a couple inches from her head. Lifting her pistol, Adriana pulled the trigger twice and a body dressed in all white, with the exception of the two circular red stains on his chest, dropped to the floor not ten feet from her.</p>

<p>It was true that Adriana had been declared an expert marksman during her training, but the real thing was vastly different. Overjoyed with her first kill, Adriana rushed over to the body and picked up the AK-47, examining the quality and checking the clip. It was too good to be from anywhere nearby.</p>

<p>"Damn Russians," she thought to herself. In all her excitement, she had forgotten basic protocol and was not aware of her surroundings. Something stirred behind her and before Adriana could react, she felt a sharp pain shoot up from her left leg. As she collapsed, she felt a cold metal blade come in contact with the exposed skin on her neck.</p>

<p><b>World Peace Corps. Convention - Jakarta, Indonesia<br/>
Monday, November 13 - 20:16:35</b></p>

<p>Ken looked around in disgust. Here he was in a supposed world peace convention and the majority of the advertisers were illegal arms dealers and gun runners looking to make a sale with a pacifist. Just when he thought the corruption couldn\'t dig any deeper.</p>

<p>He watched in dismay as reporters bombarded the president of WPC with questions about his "powerfully moving" keynote. Walking around the oversized conference hall (oversized only because the turn out for this year\'s conference was at an all-time low, with only a little over fifty attendees), Ken desperately searched for anybody in the room that actually wanted the fighting and the corruption to end. But all around him, all he could see was corruption. These people thrived from it, and without it, they would not be where they are today, enjoying their caviar and expensive wine while being swarmed by reporters looking for the perfect shot.</p>

<p>Ken trudged out the door and into the cold night, a gentle breeze blowing against his check, as he entered the dark alleyway. "Great," he thought to himself, "now I can get killed like that poor schmuck in the movie." Hearing footsteps ahead of him, he dove behind a trash can and held his breath.</p>

<p>The door that he had just walked through slammed open and out walked the president of the World Peace Corps., followed closely by two tall men in shady black suits and sunglasses. The first thought that struck Ken\'s mind was "Who wears sunglasses at this time of night!?" But that thought was quickly replaced by another when he saw three gangsters approach the president. "Uh-oh..." Ken thought, afraid that he was about to witness the murder of the president of WPC.</p>

<p>The bulky old man just stood there as the gangsters walked up to him, grinning from ear to ear. To Ken\'s astonishment, the three young men saluted the president and kneeled before him.</p>

<p>"The job is done, sir." The middle one reported.</p>

<p>"Good, good. It is about time," the old man whispered. "Now I want you to find this Ken Rubin, and I want you to kill him. His incredibly large mouth will not be bothering us anymore."</p>

<p>The three men rose to their feet, snickering, and ran off into the darkness. Ken\'s heart was beating at an astronomical pace, and he was afraid the president might hear him. He couldn\'t believe it. The president of the World Peace Corps. was a gang lord that wanted him dead! He realized that until now, he hadn\'t even begun to fathom the deepness of treachery and corruption that had rooted itself into society...</
';

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>