<?php

$aid = 'ruchi';
$title = 'Nothingness';
$cid = c1;
$issueid = i5;
$body = 
"
<p>Looking back on those days when I knew her, happy and carefree, I wonder what happened, what changed. Why did she feel the need to leave us?</p>
<p>Where did we screw up so badly that she tried to tell us that she was done with us?</p>
<p>I sat on my bed, later that night, hugging a soft teddy bear to my chest. I couldn't believe all the rage, all the misery she must have stored away from everyone, including  me, her best friend.</p>
<p>Granted, over the past few years we no longer were best friends; it was a miracle if we could talk once a week. Time has a way of ripping people apart. But never, in my wildest imagination, would I have thought that she would be ripped away from me.</p>
<p>I remember how we giggled over our first crushes together, how we cried together when my first boyfriend dumped me, how we mischievously plotted revenge against him in the form of superglue on his locker. It doesn't make sense that after all that, she could just leave me.</p>
<p>Weeks later, I receive a box from her parents of stuff that she wanted me to have. That's exactly what it was: stuff. Old Barbie dolls, friendship bracelets, projects we had begun together... nothing big, just small, insignificant memories from our past.</p>
<p>There's one thing in here I wouldn't consider \"stuff.\" Her recorder diary is in the box, and I briefly wonder if her parents knew the importance of the seemingly battered recorder.</p>
<p>Sighing, I pop it into my T.V., hoping to see one last view of my best friend alive.</p>
<p>\"Is it fair? Is any of it freaking fair? I'm sick of seeing people perceive me as the girl who tries but just isn't smart enough, isn't thin enough, isn't cool enough, isn't geeky enough, isn't anything enough.\"</p>
<p>Her impassioned speech on the T.V. sends jolts down my spine, and I pause the video for a second to check the last date on the recording. It's the day she died.</p>
<p>I hit play.</p>
<p>\"I don't care anymore if I'm not perfect. I don't want to try anymore. You know, I'm sick of this life. When you need someone the most, they aren't there for you. When you think you've finally achieved your goal, some stupid obstacle which is impossible to beat comes up. There's no way it's worth it. People are too shallow, too superficial.\"</p>
<p>I smile bitterly at the camera. She had told me all this a few weeks ago; now I realize that some of it was pointed at me.</p>
<p>\"One day, you all are going to realize that their crap wasn't worth putting up with,\" she spat into the camera. \"You're going to realize that in reality, no one cares. Not your friends, not your family...  no one. You're going to realize that no matter what, you're going to be a failure, someone that no one wants or loves.\"</p>
<p><i>Why does this sound so familiar?</i></p>
<p>\"You're going to realize that there is no perfection in anything but death. And that's because death, my friend, is nothingness. And I'm sick of this 'something.' It's crap - it's all about appearance. No one cares what actually 'is.' They care about what it looks like. No one wants the truth... they all live in a lie.\"</p>
<p>I watch in horror as she takes the razor blade and starts to end her life. I see her hand reach out to shut off the camera, sparing both it and me from watching her life slip away.</p>
<p>I shudder and rewind the recording, before hitting play again. Then, decisively, I get up and leave my room.</p>
<p><i>One day, you all are going to realize that this crap isn't worth putting up with. You're going to realize in reality, no one cares.</i></p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>