<?php

$aid = 'kriti';
$title = 'A Strange Numbness';
$cid = c15;
$issueid = i5;
$body = 
"
<p>The silence was deafening. My eyes scanned the room, perusing the faces of the seemingly countless people before me.</p>
<p>These faces now questioned me. There was a tingling sensation throughout my whole body: an adrenaline rush.  The smiling accompanist awaited my cue, but my smile in return was not quite as warm. I knew she would overshadow <i>my</i> performance; I was the one auditioning. The accompanist's fingers effortlessly flew across the piano, sharply contrasting my own condition. I opened my mouth to sing, but nothing came out. My throat was coated with ice.</p>
<p>Why was I trembling? Why couldn't I sing? I remembered my voice teacher's words. <i>Take a deep breath. Relax. Try again.</i> It only took a few measly cracked notes before the accompanist's flying fingers pulled to an abrupt stop. So did my heart.</p>
<p>The faces were now worrisome and apologetic, a failed attempt at consoling my sunken heart. After a quick \"thank you\" with some semblance of a smile, I ran across the room. I hoped to find solace in my chair, but it reciprocated nothing. It was cold. Hard. I felt numb.</p>
<p>Time passed slowly as I watched auditions after auditions of familiar faces. Their voices resonated across the depths of the room, mirroring the accompanist's flying fingers. The energy was infectious, each performer surpassing the next. Everyone had overshadowed my performance.</p>
<p>I knew my voice could resonate as well as anybody else's, yet it hadn't. What once came to me as second nature had morphed into a strange numbness.  My paranoid pre-teen mind was consumed with the thoughts of <i>failure, failure, failure...</i></p>
<p><i>Take a deep breath. Relax. Try again.</i> It was audition time again; life had thrown me another curve ball. It was time to face the faces, and most importantly--myself. My fingers clasped the metal of the door to the dreaded audition room. This time, it reciprocated something. It was not cold. It was not hard. The familiar numbness wore away as a sudden adrenaline rush surged through my body as I strode through the door. The smiling accompanist awaited my cue. My smile in return was warm. No one could overshadow <i>my</i> performance.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>