<?php

$aid = 'neelaysh';
$title = 'Movie Review: United 93';
$cid = c12;
$issueid = i5;
$body = 
"
<p>As you all know, on September 11, 2001, terrorists hijacked 4 commercial airliners. Three of these planes made it to their targets, the fourth did not. United 93 was the fourth plane.</p>

<p>The first hour of the movie deals with the reaction of various agencies to the hijackings. The air traffic controllers refuse to believe that a hijacking could possibly be taking place despite overwhelming evidence that it is. Even when they did finally figure it out, they couldn't get in contact with a decent military liaison. Speaking of which, the military was completely oblivious to the hijackings. They didn't even know that United 93 was hijacked until <i>after</i> it had <i>crashed</i>. So much for fancy defense systems and a 300 billion dollar defense budget.</p>

<p>The last 30 minutes of the movie focuses on the hijacking and the counterattack by the passengers. The directors did a good job with showing the absolute chaos in the plane when it was taken over and in its final moments. And while some people criticize the camera work, the shaky camera during the take over helps illustrate the confusion that was taking place on the flight.</p>

<p>An especially interesting aspect of the movie was the way in which the terrorists are depicted with human emotions. Rather than being calm and confident, the hijackers show fear and doubt. Right before boarding the plane, one of the hijackers calls someone and says that he loves them. Even when they have control of the plane, the hijackers worry about whether or not they will make it to their target.</p>

<p>Lastly, many people have criticized this movie for various reasons, so I will attempt to answer some of it back:</p>

<p>1. \"Cell phones don't work at 30,000 ft\" - correct. However, if you were actually paying attention to the movie then you would have noticed that the hijackers brought the plan down to low altitudes. That's why the plane disappeared from the radar.</p>

<p>2. \"The material that planes are made of blocks signals\" - incorrect. Have you ever gone on a plane flight and seen people whip out their cell phones when the plan lands and start jabbering away?</p>

<p>3. \"Government propaganda\" - not really. The movie CRITICIZES the military at the end. While yes, it could have gone deeper into the actions of the president (namely, continuing to read a story book to school kids), the point of the movie was not to bash the Bush administration. If you want to see Bush bashing, go watch Fahrenheit 911.</p>

<p>4. \"The dialogue is made up\" - partially true. Much of the dialogue is taken from messages left on answering machines or conversations between passengers and their friends and families. The makers of the movie actually went and talked to the families of the victims, so it is about as accurate as any film on this topic can get.</p>

<p>5. \"The plane blew up in mid air. The debris was in an 8 mile radius. The government blew it up\" - This might be a viable theory, but lets think about it for a little bit. If the government successfully shot down the plane, why wouldn't they point to this as a success of the military? I probably don't know enough physics to be able to say whether or not an 8 mile radius of debris can only come from a mid air explosion. Either way it is just another theory in a long line of them about what really happened to United 93. Maybe the directors got it wrong, but it in no way detracts from the heroism showed by the passengers.</p>

<p>I recommend that anyone planning on watching this movie use their own discretion. It's not particularly bloody for an \"R\" movie, but it is definitely emotionally intense, and some people may not be ready to relive the day.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>