<?php

$aid = 'ruchi';
$title = 'A Bad Valentine\'s Day Card';
$cid = c20;
$issueid = i5;
$body = 
"
<p>BZZ! BZZ! THUD!</p>
<p><i>Why does every morning have to start with that? What happened to birds chirping and the sun warming me up gently?</i> Groaning, I pick myself up off the floor and turn off my alarm clock before entering my bathroom to get ready.</p>
<p>Minutes later, I am drying off the warm water and attempting to pick out clothes. Confusion clouds my mind as I realize that I have nothing \"socially acceptable\" to wear to school; my friends would term all the clothes around me \"geeky\" or \"slutty.\" <i>I could have sworn that yesterday I had several decent, normal clothes!</i> Irritated, I pick out a \"geeky\" outfit. <i>I would rather have someone call me a nerd than... yes,</i> I decide, <i>I would definitely rather be termed a nerd.</i> Still, my mind is filled with a cloud of foreboding that school is going to be unpleasant.</p>
<p>With high hopes that even a \"geeky\" outfit can be fixed with the right hair style and cosmetics, I finish getting ready. <i>After all, a successful outward appearance masks the insecure inner being!</i> However, my dismay triples as I notice that my hairbrush is missing. My cosmetics? They looked fine when I was putting them on, but now they would suit a clown more than myself. I am torn between breaking down and crying and laughing hysterically when I notice the bottle of makeup remover is missing. <i>Today,</i> I think to myself emphatically, <i>is not going to be a Ruchi-positive day.</i></p>
<p>Some time later, I am sitting in the car with my dad. He looks at me sideways and I flush a bright red with embarrassment. It is obvious he is trying to find a polite comment to ask me why I look so destroyed - and now that I blushed, I look hideous as well as nerdy. I am positive that the bright, fire-engine red of my face and blush are clashing. My dread for the school day increases even more, and the adrenaline pounds through my bloodstream.</p>
<p>In hopes of saving face with an impressive knowledge of music and celebrity gossip, I turn on the radio. Static fills the car and my dad almost jerks into the juxtaposed lane in shock.</p>
<p>\"Can you turn that OFF!\" he yells over the static. \"NOW!\"</p>
<p>Naturally, I comply and lean back against the car seat with an angry sigh. <i>No clothes, no general appearance, and now no music and gossip. This definitely is not one of my better days.</i></p>
<p>Finally, we reach school and I quickly hop out of the car - the embarrassment from the radio and the outfit fades and I feel the natural happiness of the day returning to me. I grin as my dad pulls away. <i>It was just an unfortunate and embarrassing morning,</i> I reassure myself. The school day will be fine.</p>
<p>\"What the heck? Oh my gosh, what are you wearing?\"
<p>My stomach plummets eight feet and embeds itself into the concrete below me.</p>
<p>\"It's so dorky, isn't it?\" I reply carefully. I have to maintain a facade of calmness; otherwise they are all just going to think I am a \"reject.\" Planning my words out, I continue, \"I woke up this morning and all my clothes were just...gone, I guess.\"</p>
<p>\"You look like such a geek. And I'm so not even going to comment on your make-up... demented clown.\"</p>
<p>I feel my cheeks heating and turn away, hoping she will not catch sight of the horrible clash of the pink and red that now adorn my face.</p>
<p>\"HAHA! You look like a bad Valentine's Day card!\" she shrieks, dissolving in laughter. Apparently I was unsuccessful at avoiding her stare.</p>
<p><i>This was most definitely not my day.</i> Uncomfortable, I explain that I could not find cosmetic remover before running away - figuratively, of course.</p>
<p>Walking down the school halls is making the day feel worse than it probably is, I note. People stare and I am become agitated and intimidated. Being the center of negative attention is not common for me. <i>Well... duh.</i></p>
<p>I catch sight of my close friends and start smiling; they are the people who can always make me laugh and smile, no matter what, and I depend on and love them immensely.</p>
<p>\"What the heck are you wearing?\" one of them asks immediately.</p>
<p><i>Need I reiterate that today was not going to be one of my more enjoyable days?</i></p>
<p>\"Whatever, let her wear whatever,\" another one says. \"It's not like it matters what she wears.\"</p>
<p>Flashing her a grateful smile, I turn to the rest of the group. \"What's up?\"</p>
<p>\"Did you hear about the party at...\"</p>
<p>What party? Suddenly feeling like a misfit, even among my friends, I look up at the speaker.</p>
<p>Not invited to a party... terror now takes hold of me. It feels like, from one day to another, I went from an average teenager to a social pariah. I lost my stomach when I had gotten out of the car, so I was pretty sure that it was my liver that plummeted this time.</p>
<p>\"Well, are you going?\" a voice breaks into my thoughts. I look up at a girl who I considered, mere moments ago, one of my closer friends.</p>
<p>\"Uh... I don't think so...\" I say hesitantly.</p>
<p>\"You mean you weren't invited,\" she says with a nasty grin. \"Poor little Ruchi... dorky clothes, dorky make-up, and no party invitation.\"</p>
<p>I feel myself flush again and become dejected rather than irritated. <i>Is it \"pick on Ruchi\" day? First my clothes do it, then my hairbrush and makeup, then my dad, and finally my friends!</i></p>
<p>Her smirk broadens - <i>uh-oh</i>. This is what I would call the end of the line, the last part of a three staged event: the girl dresses like a nerd, the girl acts like a reject, and then finally the girl is cast away from all her friends for being a nerd and reject. It is a vicious cycle.</p>
<p>BZZ! BZZ! BZZ! THUD!</p>
<p>What...?</p>
<p>\"6:15,\" I read aloud. Then I glance at the dog sitting on my stomach. \"Get off,\" I tell him automatically while scratching his ears. Needless to say, he ignores me. I sigh in relief as I recall the dream. \"It was just a nightmare,\" I tell him and give him a hug.</p>
<p>He yelps and jumps off the bed - I follow him, laughing. <i>Today is going to be an awesome day.</i></p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>