<?php

$aid = 'aneesh';
$title = 'Fun With Fibs';
$cid = c3;
$issueid = i5;
$body = 
"
<p>So, last month, April, was National Poetry Month.  It was also Math Awareness Month.  And in honor of that interesting pairing, <a href = \"http://gottabook.blogspot.com/2006/04/fib.html\"> Gregory K began writing 'Fibs'.</a> What are fibs?  Well, if you had clicked the link you would know, but that's besides the point.  They are six line, twenty syllable poems that follow the Fibbonacci sequence in numbers of syllables - 1/1/2/3/5/8.  Greg said that the number of lines doesn't really matter, as long as it follows the sequence.  He was also flexible on stacking it - going 1/1/2/3/5/8/5/3/2/1/1, though he said that's not really a Fib, just awesome Fibbonacci poetry.  The comments on that introductory blog post are full of much better ones than mine, and I'm going to put all of these up there as well as here.  But yeah, enough background. </p>

<p>This
<br>is
<br>a Fib.
<br>Not a lie.
<br>A poem made of
<br>The great Fibbonacci sequence. </p>

<p>Yet
<br>again
<br>I try
<br>to make a
<br>passable poem.
<br>I hope this one wasn't too bad.</p>

<p>Now
<br>for
<br>something
<br>completely
<br>different. I will
<br>Attempt to make a longer Fib.
<br>Thirteen on this line!  Can I one-up this? I think so!</p>

<p>So
<br>I
<br>will try
<br>an even
<br>longer Fib poem.
<br>Eight syllables are on this line!
<br>Can you tell that I'm running out of good ideas?
<br>Not that, I suppose, any of the ideas were good to begin with. &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; TWENTY-ONE!</p>

<p>Now
<br>the
<br>true test.
<br>Can I write
<br>A Fib that isn't
<br>completely self-referential?</p>

<p>Now!
<br>Go!
<br>Escape
<br>to freedom!
<br>We are trapped in this.
<br>Run, try to fly, and soar so far.
<br>Only to fall back,
<br>receeding
<br>into
<br>this
<br>void.</p>

<p>Yeah, alright, not so great, but at least I introduced the form.  Write your own in the comments, so that there are at least some good Fibs on this page.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>