<?php

$aid = 'shan';
$title = 'I Have an 8 Month Old Son at Home';
$cid = c4;
$issueid = i5;
$body = 
"
<p>But did you know that the hospital made a switch at birth and he's not really my biological son.</p>

<p>Yes - it's true!</p>

<p>Of course, I went to a lab and had Brandon's DNA checked (my wife didn't accompany me because she thinks I'm \"nuts and should be committed\") and it was a perfect match. But that's only because the \"black op\" guys got there and \"convinced\" the staff to replace the real DNA results with the ones they created.</p>

<p>I could go to 20 other labs and have the same DNA tests done, but I'm sure the results would ALWAYS come back a perfect match.</p>

<p>Man, those \"black op\" guys are good!</p>

<p>So, I phoned the hospital to speak with the nurse who really assisted in my wife's birth. But they told me that she's no longer employed there. Apparently she \"left\" her position about a month after Brandon was born. Very, very suspicious, don't you think? Imagine a person leaving their employment a month after a PARTICULAR baby was born.</p>

<p>Notice that she didn't leave when little boy Smith was born - or little boy Jones - or little girl Brown.</p>

<p>No, very coincidentally, it was one month after little boy Brandon was born.</p>

<p>And the little hair that Brandon had at birth - very, very blonde - is growing in and it actually looks \"dirty blonde\" after 8 months. Yes - when I compare pics that were taken at birth versus pics taken today, you can actually see a difference in the hair color.</p>

<p>So, I asked a doctor about this and he told us that it's very common for hair to change over time.</p>

<p>So if that's the case, how come my friend Bob's baby, James - who was born with black hair still has black hair. And Julie, a friend of my wife, who had a son Noah, born with dark brown hair, still has a son 11 months later with dark brown hair.</p>

<p>Think about that for a moment - three babies and ONLY Brandon has had a noticeable change in hair color. Far too coincidental!</p>

<p>Oh yeah, the doctor who told me this \"bogus\" information just happens to have gone to medical school in Virginia (I saw the diploma on his wall). Do you see the connection - medical school - Virginia - CIA HEADQUARTERS - Langley - VIRGINIA!</p>

<p>Put 2 and 2 together and what do you get? 4, OF COURSE!</p>

<p>Oh - and here's another incredibly suspicious thing. On the day that Brandon was born, apparently the fire alarm went off and the much of the hospital was evacuated. Of course, it turned out to be a false alarm, but when I inquired, there hadn't been a \"false alarm\" at that hospital for about 6 weeks.</p>

<p>Why do you suppose it happened on the very same day that Brandon was born?</p>

<p>That's easy - the firemen who showed up weren't really firemen at all - they were \"black ops\" guys bringing in the \"wrong baby\" to make the switch. But they had to do so in such a way as not to create any suspicion.</p>

<p>And what better way than to pretend to be a fireman responding to a false alarm.</p>

<p>Oh - here's something else I discovered. On the day, Brandon was born, there apparently were 5 other babies born in that hospital on that same day. As such, there was allot of confusion so the switch could be made easier.</p>

<p>But I see through that nonsense!</p>

<p>Did you know that 2 days before Brandon was born, there were only three births. And the day before, there was ONLY 2 births. And on the day after, ONLY 3 births took place.</p>

<p>Very suspicious that on the VERY day that Brandon was born, the hospital had the MOST births.</p>

<p>My guess is that they had to \"transfer\" a couple of pregnant women from another nearby hospital to the same hospital as Brandon was born in to deliberately create confusion.</p>

<p>Well, I tried to pursue this and decided that I would track down these women who were transferred to our hospital and see what reason they were given for being transferred.</p>

<p>But when I asked the hospital administrator, she told me that (a) there were no transfers on that day and (b) even if there was, they couldn't divulge that information as it was confidential.</p>

<p>I later found out that the hospital administrator was new on the job - she had been given a promotion to the job 6 months earlier.</p>

<p>Very suspicious that the same person who wouldn't divulge the truth to me was the same person to get a promotion in the same hospital that Brandon was born in.</p>

<p>Clearly, she, too, was in on the conspiracy and the promotion was a reward.</p>

<p>I saw the proof a few hours later when I saw her leave work, go to the parking lot and get into a \"new car.\" (It looked like a Ford. Hey, didn't Henry Ford provide cars to the Nazis during WW2 - something's not right here!) Clearly the car was part of the \"pay off\" for her to keep her mouth shut.</p>

<p>One more thing - she had a \"Go Dallas Cowboys\" bumper sticker on her new car. See the connection - she's probably from Dallas - Kennedy was assassinated in Dallas - Kennedy died in a hospital (Parkland) and she's a HOSPITAL administrator. Coincidences...?</p>

<p>I think not!</p>

<p>I mean - c'mon - new job/ new car with Dallas bumper sticker - all within the span of about a 6 month period after the hospital switched my baby with another. Give me a break.</p>

<p>Oh, I almost forgot - wait till you hear this. Her secretary phoned in \"sick\" that day so I couldn't question her. Apparently she had a bad migraine. In her place was a \"temp.\"</p>

<p>Right. On the very day that I'm meeting with the hospital administrator, her secretary is \"sick.\" And a temp is at the desk instead. C'mon - what's the odds of that happening - 30,000,000 to 1!</p>

<p>Oh yeah, here's something else, when I was up at the administrator's office trying to get this information, a couple of guys were loading big boxes of files to \"supposedly\" be taken to a warehouse to be archived.</p>

<p>Yeah - right. I make an appointment with a hospital administrator to discuss a switched baby and just coincidentally on that very same day, \"files\" are being moved.</p>

<p>I've got a thousand dollars that says the files pertain to baby boy \"Brandon!\"</p>

<p>Finally, I went to the internet and found a web site comprised of people who also had their babies switched at birth. And after spending more than a month on their bulletin boards, I'm more convinced than ever that some fiendish activity is being engineered by some very shadowy figures right under our noses.</p>

<p>I mean - c'mon - can we all be wrong? Is all of the above just coincidences - new car / new job / changing jobs / internet sites with other people saying the same things/ fire alarms / 5 births on the same day/ files being moved / Dallas bumper sticker / temps/ medical school in the same state as CIA headquarters/ DNA perfect results!</p>

<p>C'mon - who do they think they're kidding?</p>

<p>But when I go to the papers and speak to people on the street, they look at me like I'm nuts.</p>

<p>There are a thousand other things I could point to - for example, it was sunny the day before and the day after Brandon was born, but it rained on the day he was born. Come to think of it, I did hear an airplane overhead that day. It's my guess that the plane was \"seeding\" the clouds over the hospital to \"create\" a rainy day. I'm not entirely sure why the \"black ops\" guys needed it to rain that day - but I'm sure there's a good reason. In fact, as soon as I finish this post, I'm going to do a Google search for \"seeding clouds and switching babies\" - I bet you that I'll get a lot of good hits and links to web sites where people will be able to provide me with some explanations.</p>

<p>But that's OK. I have right on my side. And even though my wife thinks I belong in a padded cell and my co-workers are looking at me like I'm a complete idiot, I know they're just \"sheep\" that have been brainwashed.</p>

<p>And some day, we will live in a world where babies aren't being switched at birth!</p>

<p>Note: I got this from a chain mail that was forwarded to me. I do not know where it originated.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>