<?php

$aid = 'tonia';
$title = 'Fearing Nothing';
$cid = c20;
$issueid = i5;
$body = 
"
<p>\"No!\"</p>
<p>The cry shattered the silence enshrouding the house and suddenly, light pierced through the darkness as shuffling, slippered feet made their way across the hall to the source of the sound.  Clutching her bathrobe tighter about herself, the woman peered through a crack in the door at the thrashing shape on the bed illuminated with the glow of the hallway light.  Moments later, her husband, clutching a glass of water and a bottle of rattling pills, was standing behind her.</p>
<p>\"Again?\" he asked, voice strained.</p>
<p>\"Yes,\" she sighed as she made her way to the bed.  Her daughter had stopped struggling and now lay panting, her hair plastered over her forehead.  Underneath her eyelids, her eyes moved rapidly as she fought against, seemingly, nothing.  Shaking her gently, the mother raised her groggy daughter up and took the pills and water from her husband.</p>
<p>\"Here, honey, take these.  They'll help you sleep.\"</p>
<p>Blinking blearily, the girl swallowed the pills with difficulty and dropped her head back down immediately, her pale face still shining with sweat.</p>
<p>\"Shoot,\" she muttered as she turned towards her alarm clock.  School had started twenty minutes ago, and she was still in bed, eyes heavy with sleep.  She remembered vaguely having her nightmares again last night, but the little that she could recall, a suffocating black nothingness, was the same as it had been many times previously.  As she struggled with a yawn, she remembered also waking in the night and having to take sleeping pills; their soporific effect had probably prevented her from waking with her alarm clock.  Sighing, she hurriedly pulled on her clothes, wondering why her parents had not awakened her.  The answer was soon made clear as her mother burst through the door, waving a business card.</p>
<p>\"It's okay, honey.  We let you sleep in a little,\" she said and handed her daughter the card, which was engraved with a fancy-sounding \"Dr. P. A. Brada.\"  \"We arranged a meeting for you this morning with the leading psychiatrist of our day.  We're so lucky; Dr. Brada's actually a friend of your aunt, and we told him a bit about these dreams you've been having.  He said he was free this morning to have you come in and take a few tests.\"  As her daughter stared at her in alarm at the word \"psychiatrist,\" she continued, \"He specializes in medical brain analysis when mere memory does not suffice.  Don't worry; he does not deal with mental illness.\"</p>
<p>An hour later, mother and daughter found themselves in the glaringly white examination room with the psychiatrist.  He studied his patient with an intensive gaze before breaking the silence.</p>
<p>\"So.  How long have you been having these - dreams?\"</p>
<p>\"Um, a few months?  Well, actually ever since school's started.\"</p>
<p>A flash of understanding seemed to flit across his eyes, but it disappeared as he turned and pressed a few buttons on the machine behind him.</p>
<p>\"And - what do you remember before you wake up?  Scary circumstances?  A heavy oppressive weight?  Falling?\"</p>
<p>\"No, not really.  The thing is, I don't really remember much at all.  Just a blank whiteness, or maybe it's black.  Nothing much at all.\"</p>
<p>A fan whirled to life.</p>
<p>\"Let's see what's up.\"</p>
<p>Weeks later, the results came.  As mother and daughter entered the gleaming office, they were shocked to find piles of papers, all stamped with their family ID number at the top.  Graphs and diagrams littered the desk, and as Dr. Brada pointed out the various stacks, both studied the cluttered pages in amazement.</p>
<p>\"You can stay here and take a look at some of these results,\" he directed towards his young patient.  \"I will need to speak to your mother for a moment outside.\"</p>
<p>Inside another room, he turned toward the older woman.  \"The good news is we have been able to pinpoint exactly what these nightmares your daughter has been having consist of.  However, I believe this circumstance is rather unusual, as there is no real 'cure.'  She will have to find out how to stop these dreams herself.\"</p>
<p>\"Well?  What is it?\"</p>
<p>\"Nothing.\"</p>
<p>\"Excuse me?\" the mother asked in confusion, certain that the doctor had misinterpreted her question.</p>
<p>\"Nothing.  'Nothing' is the answer to your question.  'Nothing' is the conclusion from our results.  Your daughter has been haunted for the past few weeks by 'nothing.'\"</p>
<p>\"Are you telling me, Dr. Brada, that we paid well over a thousand dollars for this analysis and waited for almost a month - and those papers!  Those stacks of papers!  All this to find that our daughter hasn't been able to sleep well for weeks because of <i>nothing</i>?  I don't know what you're playing, doctor, but out of all the tests and data, surely you must have found some disorder or concrete cause for her behavior!  You can't expect us to walk out of here with no explanation at all for all that has been happening.\"</p>
<p>\"Please listen to me,\" Dr. Brada sighed as he struggled to find the words to explain.  \"What I meant by 'nothing' was not that we have not found a cause for your daughter's behavior.  Indeed, her nightmares are caused by something, and it so happens that that 'something' is 'nothing.'  Your daughter is literally afraid of the concept of 'nothing.'  We can only assume by her answers to some of the questions that she is afraid of being or becoming nothing.  Or maybe something more.  Maybe she fears being surrounded by nothing every day, to the point where 'nothing' becomes something so great that she cannot escape.  Perhaps you should talk to her yourself.\"</p>
<p>A beat of silence passed in the room before the mother nodded.  \"We'll be back tomorrow to collect our formal results.  I would like to speak with her before we return.\"</p>
<p>After the psychiatrist offered his explanation again to the daughter, mother and daughter left, promising to return soon for more detailed analysis.  On the car ride home, the girl finally spoke.</p>
<p>\"I guess I had never realized this, until it was pointed out to me.  I guess I really am afraid of 'nothing.'\"</p>
<p>Her mother turned towards her as they stopped at a traffic light.  \"But isn't this just so simplistic?  Don't you fear something more than this 'nothing'?  Maybe Dr. Brada actually meant failure, and that's what your dreams have been showing you.  Fearing failure is more plausible.  Perhaps that darkness you remember is actually a lack of success, and -\"</p>
<p>\"But I don't fear failure, Mom,\" the daughter interrupted.  \"Failure - at least it's something.  I don't think it's worse for my 'nothing' to be chased off by failure and disaster, because along the way, at least there's something to live for and to think about and obsess over.  Failure opens doors to finding one's faults and fixing them.  With failure and disaster, we find appreciation for the higher points of life, and they jolt us into seeing that there is still life yet to live.  Mom, Dr. Brada's right.  What I can't stand is the void left by a life filled with nothing.  I can't imagine wasting away day by day, letting life pass me by while I merely look on.\"</p>
<p>Her mother sighed as she pulled into the garage, turning off the car's engine.  The two sat in silence in the cooling car before the older woman turned towards her daughter and broke the silence.</p>
<p>\"You know what your only shot at putting an end to these recurring nightmares is?\"</p>
<p>\"What?\"</p>
<p>\"Go out, do something, and be somebody.\"</p>
<p>\"But I am doing things with my life; I am already out there, doing something.\"</p>
<p>\"Then why are you wasting your time worrying over this 'nothing'?  You said it yourself - you are already somebody.  We should stop making these ridiculous quote signals each time we talk about 'nothing.'  If you are afraid of becoming 'nothing' yet are already 'something,' then you are one of the few who do fear nothing.  No quotes this time.\"</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>