<?php

$aid = 'sharon';
$title = 'One Lazy Saturday Afternoon';
$cid = c1;
$issueid = i5;
$body = 
"
<p>One lazy Saturday afternoon, I was in the local library, idly browsing through books. I didn't feel up to wrapping my mind around thematic novels, nor could I find interest in the yellowed paperbacks on the \"Teen Shelf,\" so I cruised through the children's section, happily surrounded by the stories of my childhood. Amid youngsters half my height, I re-absorbed the narratives that had fed my imagination for so many years. After selecting a few elementary-school level reading books, I looked for a place to sit but realized that there were no chairs that came higher than my knees.</p>
<p>Feeling slightly foolish, I walked, dignified, back to the child-free section of the library and settled down next to a bright window where I could enjoy my reading in peace, safe from the puzzled glances so liberally given to adolescents who are found perusing children's literature. I had dug a few dozen pages into the epic battle between a group of girls and their respective enemies when I heard a hesitant voice: \"Can you help me with my homework?\"</p>
<p>I looked up to see, not a child, but an elderly woman with a slender English workbook.</p>
<p>\"Sure, I'll help,\" I told her, and watched as she flipped her book open and pointed to a page reminiscent of my first-grade reading activities; explanatory drawings studded the page.</p>
<p>\"I'm learning English, I am supposed to... writing three sentences, using 'low.' The word 'low.'\"</p>
<p>Taking my cue from the workbook's explanation, \"The word 'low' has different meanings,\" I began, trying to help her. \"Well, the word 'low' can describe different things.\"</p>
<p>\"Yes, I write three sentences for each different thing.\"</p>
<p>\"Okay, so let's go through this. Let's take this first meaning of 'low,'\" I said, pointing to a drawing of someone stepping over a rock. \"This low means something... not very high, something close to the ground,\" I explained, struggling to describe a word that, to me, was so simple and basic, it defied the need for explanation. The woman appeared Asian, but I could not determine which Chinese dialect she spoke by just looking at her; besides, I mistrusted my shaky mastery of Chinese to properly explain what she needed to know without accidentally invoking the wrong nouns. I was trapped in my own language, lost for words.</p>
<p>\"So let's make a sentence using 'low,'\" I continued. I had a sudden recollection of my seven-year-old self \"playing school\" - standing in front of an imaginary class, writing words on an imaginary board. Teaching, back then, had been easy; seven years later, I was out of practice. \"Um... you want to say that something is low... maybe something like \"The wall is very low, so I could step over it,\" I offered lamely.</p>
<p>The lady's eyes lit up, and I watched as she slowly wrote my words on an empty line. She repeated my words, speaking with careful pronunciation. \"The wall...\"</p>
<p>\"...is very low,\" I coached.</p>
<p>\"Is very low... so I could step over it.\"</p>
<p>Her pencil moved steadily, and she made sure to form each word with neat precision.</p>
<p>\"Thank you. That is good,\" she said upon finishing her sentence. \"What about this 'low'?\" she asked, pointing to an explanation of low scores and low values.</p>
<p>\"Okay, well, let's think of a sentence first,\" I began. \"Let's say our sentence is, 'He was sad, because his test grade was very low.'\" I paused and the woman waited for my explanation.</p>
<p>\"So this person we're talking about... he didn't know everything for the test. He got many things wrong, so he got a grade that wasn't very good, because it was low. So he was sad because his test grade was very low.\"</p>
<p>The woman nodded, understanding, and penciled my sentence on another blank line.</p>
<p>\"His test grade...it...\" she struggled to remember the right tense.</p>
<p>\"Was.\"</p>
<p>\"Was low.\"</p>
<p>She finished writing the sentence. \"This 'low,'\" she prompted, pointing to the last explanation.</p>
<p>\"Well... okay. Have you ever heard of the phrase 'all-time low?'\" I asked.</p>
<p>\"No.\" She eagerly awaited my explanation.</p>
<p>\"Okay... when something is low, you can say it's at a low. When something is very, very low, more low than it has been before, you can say that it's at an 'all-time low.'\"</p>
<p>\"Okay.\"</p>
<p>\"So let's use that, 'all-time low.'\"</p>
<p>\"All-time low.\"</p>
<p>\"How about... 'Her mood had reached an all-time low, because so many bad things happened.'\"</p>
<p>This sentence was trickier than the others.</p>
<p>\"Her mood reached?\" the woman repeated.</p>
<p>\"Yeah, that means it got to...\"</p>
<p>\"All-time low.\"</p>
<p>\"Yeah, 'all-time low.'\"</p>
<p>She repeated my sentence and carefully wrote it down. Then she beamed.</p>
<p>\"Thank you,\" she said gratefully, looking at what she had written before closing her workbook. \"Thank you. You are...\" she looked up at me, searching for adjectives. \"You are pretty girl, smart girl. You are very smart girl. Thank you for helping.\"</p>
<p>\"Oh, you're welcome!\" I said, beaming in return.</p>
<p>Later, I thought about just how inspiring that woman really was. Despite her advancement in years, she still had an avid desire to continue learning, and she had taken on the daunting task of learning an entirely new language, one she knew she could never master entirely, and yet she persisted. She had the same intensity that I'd had when I was young, when I'd considered learning a joyful and rewarding task. Usually, the people I'd known to possess such eagerness as children only lost the incentive later as teenagers, yet this woman was still driving herself to learn at her age.</p>
<p>I marveled at the fact that she didn't consider it a breach of dignity or pride to publicly ask for such help; my own generation feared such displays of weakness. Personally, I realized it was a fairly recent phenomenon; as children, many of us felt that the world held answers for the taking, that anyone taller than us was wise in the ways of the world, and that we were free to question them, or ask them to help us, be it to solve a long-division problem or to reach the cookie jar. As teenagers, we felt the need to uphold our pride, and in doing so, we had lost something.</p>
<p>I don't think that woman set out to teach me a lesson, but she did. I can't remember what she was wearing, or the name of her workbook, or even the exact words of our conversation, but I do remember that she was striking in that she was both eager and inspiring. I wonder if she learned anything from me besides a small snippet of the English language. I realize, now, that we were really both teaching each other lessons in life. That day in the library taught me to take joy once again in learning and absorbing the world around me, and for that reason, I won't ever forget that lazy Saturday afternoon.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>