<?php

$aid = 'neil';
$title = 'Twists In the English Language';
$cid = c4;
$issueid = i5;
$body = 
"
<p>Can you read these right the first time?<br/>
<br/>
1) The bandage was wound around the wound.<br/>
<br/>
2) The farm was used to produce produce.<br/>
<br/>
3) The dump was so full that it had to refuse more refuse.<br/>
<br/>
4) We must polish the Polish furniture.<br/>
<br/>
5) He could lead if he would get the lead out.<br/>
<br/>
6) The soldier decided to desert his dessert in the desert.<br/>
<br/>
7) Since there is no time like the present, he thought it was time to present the present.<br/>
<br/>
8) A bass was painted on the head of the bass drum.<br/>
<br/>
9) When shot at, the dove dove into the bushes.<br/>
<br/>
10) I did not object to the object.<br/>
<br/>
11) The insurance was invalid for the invalid.<br/>
<br/>
12) There was a row among the oarsmen about how to row.<br/>
<br/>
13) They were too close to the door to close it.<br/>
<br/>
14) The buck does funny things when the does are present.<br/>
<br/>
15) A seamstress and a sewer fell down into a sewer line.<br/>
<br/>
16) To help with planting, the farmer taught his sow to sow.<br/>
<br/>
17) The wind was too strong to wind the sail.<br/>
<br/>
18) Upon seeing the tear in the painting I shed a tear.<br/>
<br/>
19) I had to subject the subject to a series of tests.<br/>
<br/>
20) How can I intimate this to my most intimate friend?<br/>
</p>

<p>Let's face it - English is a crazy language. There is no egg in eggplant, nor ham in hamburger; neither apple nor pine in pineapple. English muffins weren't invented in England or French fries in France. Sweetmeats are candies while sweetbreads, which aren't sweet, are meat. We take English for granted. But if we explore its paradoxes, we find that quicksand can work slowly, boxing rings are square and a guinea pig is neither from Guinea nor is it a pig.</p>

<p>And why is it that writers write but fingers don't fing, grocers don't groce and hammers don't ham? If the plural of tooth is teeth, why isn't the plural of booth, beeth? One goose, 2 geese. So one moose, 2 meese? One index, 2 indices? Doesn't it seem crazy that you can make amends but not one amend? If you have a bunch of odds and ends and get rid of all but one of them, what do you call it?</p>

<p>If teachers taught, why didn't preachers praught? If a vegetarian eats vegetables, what does a humanitarian eat? Sometimes I think all the English speakers should be committed to an asylum for the verbally insane. In what language do people recite at a play and play at a recital? Ship by truck and send cargo by ship? Have noses that run and feet that smell?</p>

<p>How can a slim chance and a fat chance be the same, while a wise man and a wise guy are opposites? You have to marvel at the unique lunacy of a language in which your house can burn up as it burns down, in which you fill in a form by filling it out and in which, an alarm goes off by going on.</p>

<p>English was invented by people, not computers, and it reflects the creativity of the human race, which, of course, is not a race at all. That is why, when the stars are out, they are visible, but when the lights are out, they are invisible.</p>

<p>PS. - Why doesn't \"Buick\" rhyme with \"quick\"?</p>

<p>You lovers of the English language might enjoy this.</p>

<p>There is a two-letter word that perhaps has more meanings than any other two-letter word, and that is \"UP.\"</p>

<p>It's easy to understand UP, meaning toward the sky or at the top of the list, but when we awaken in the morning, why do we wake UP? At a meeting, why does a topic come UP? Why do we speak UP and why are the officers UP for election and why is it UP to the secretary to write UP a report?</p>

<p>We call UP our friends. And we use it to brighten UP a room, polish UP the silver, we warm UP the leftovers and clean UP the kitchen. We lock UP the house and some guys fix UP the old car. At other times the little word has real special meaning. People stir UP trouble, line UP for tickets, work UP an appetite, and think UP excuses. To be dressed is one thing but to be dressed UP is special.</p>

<p>And this UP is confusing: A drain must be opened UP because it is stopped UP. We open UP a store in the morning but we close it UP at night.</p>

<p>We seem to be pretty mixed UP about UP! To be knowledgeable about the proper uses of UP, look the word UP in the dictionary. In a desk-sized dictionary,
it takes UP almost 1/4th of the page and can add UP to about thirty definitions. If you are UP to it, you might try
building UP a list of the many ways UP is used. It will take UP a lot of your time, but if you don't give UP, you may wind UP with a hundred or more. When it threatens to rain, we say it is clouding UP. When the sun comes out we say it is clearing UP.</p>

<p>When it rains, it wets the earth and often messes things UP.</p>

<p>When it doesn't rain for awhile, things dry UP.</p>

<p>One could go on and on, but I'll wrap it UP, for now my time is UP, so... Time to shut UP!</p>

<p>Note: I got this from a chain mail that was forwarded to me. I do not know where it originated.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>