<?php

$aid = 'raymond';
$title = 'Movie Review: Ice Age 2';
$cid = c12;
$issueid = i5;
$body = 
"
<p>I liked it. Sure, the plot is incredibly cliched and predictable, the pace is incredibly awkward, and the animation isn't that great. Sure, the movie is basically a retread of the first Ice Age. Sure, the movie isn't as good as the original. But I liked it. It had enough funny scenes to keep me entertained, especially during the second half.</p>
<p>The movie follows the adventures of Manny, a loving mammoth, Sid, a stupid sloth, and Diego, a saber tooth tiger with an attitude problem. This time, they are stuck in a valley with a crapload of other animals while the ice dam surrounding said valley begins to melt. Vultures tell them that there is a boat on the other side of the valley that can transport them to safety.</p>
<p>The movie depicts the trio's exploits as they travel to the safe side of the valley. On the way, they meet Ellie and two possums. Ellie is a mammoth convinced that she is a possum... and it takes a while for Manny to convince her otherwise. Of course, they become friends by the end and live happily ever after, but the movie is not all plot driven. It is mostly built from small, funny moments, like when Sid is kidnapped, named the Fire God, and then thrown into a volcano as a sacrifice by sloths.</p>
<p>There are also the scenes involving Scrat. For those of you who have not seen the first Ice Age, Scrat is a squirrel who frequently attempts to retrieve an acorn. The movie opens with him hanging on an ice cliff, pushing his acorn further and further up. However, he accidentally pokes a hole, causing water to leak out. He sticks his finger into the hole as an attempt to stop the leak, but another hole forms. This goes on until he runs out of fingers and toes. Then a gigantic geyser of water erupts out of the cliff, taking poor Scrat with it. Needless to say, it is all very, very funny (especially the end).</p>
<p>Many of the people I saw this with didn't like it. Now to the majority of the idiotic, wannabe-intelligent teenage crowd, this movie might seem stupid. But if you manage to get past the predictable plot and childish humor, you will probably enjoy the movie as much as I did. All you need to remember is that this is a family movie geared towards kids, so the only way to enjoy this movie is to watch it with a kid's mindset. Otherwise, you will probably find yourself squirming at the jokes and cringing at the plot.</p>

<p><b>Recommended, to an extent.</b></p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>