<?php

$aid = 'sharon';
$title = 'Club Review: GSA';
$cid = c7;
$issueid = i5;
$body = 
"
<p>Maybe it seems paradoxical for a straight person to plug the Gay-Straight Alliance. Maybe it seems pointless to plug it at all. I certainly didn't join the Harker GSA with any lofty socio-political goals in mind. I just figured, \"Hey, I support gay rights,\" and signed up almost on a whim.</p>
<p>Well, I have learned so much more this year. I've learned, through my supremely awesome gay, lesbian, and bisexual friends, what it's really like to be homosexual. I've suffered vicariously with them as they agonized over the process of coming out to their parents, of being rejected by people they thought were their friends simply because they were a little bit different. I've squealed with joy along with them as they found \"significant others,\" and participated in ethical debates.</p>
<p>I've realized just how much we have to change society. A normal teenager should not have to lose weight and sleep and suffer from bad health just because they have to tell their parents that they like people of the same sex. A normal teenager should not have to research which states protect which rights, so that she can figure out which states to avoid. A normal teenager should not meet stunned silence when she mentions her girlfriend in passing.</p>
<p>\"Yeah, yeah, I know that, I support gay rights,\" you say. \"That doesn't mean I should join.\"</p>
<p>Okay. Fine. But the other day my lesbian friend and I saw these posters with messages like 'Saying someone is gay is like saying they like lasagna - it doesn't make a difference.' I thought it was a good sign with a good message, but my friend thought otherwise. We straight people might not see anything wrong because we just don't understand. Sure, the thought's good, but what do we know?</p>
<p>So put the \"Straight\" in \"Gay-Straight Alliance.\" (If you do, you'll be an \"Ally\" - I thought that was pretty cool.) See if there's a GSA at your school; if there is, I strongly urge you to join - if not, do what you can to start one now! The world needs changing, and you can help.</p>
<p>Want more information? There's a links page on <a href=\"http://web.harker.org/GSA\">http://web.harker.org/GSA</a> with links to fantastic sites that will help you learn more about the LGBTQ community and lifestyle. (And if you don't know what LGBTQ stands for, then you don't know enough.)</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>