<?php

$aid = 'sharon';
$title = 'Raccoon Eyes';
$cid = c3;
$issueid = i5;
$body = 
"
<p>Hair-sprayed ditz with the red, red lips<br/>
Smiling and pouting at all the guys<br/>
Miniskirt bouncing on her over-swaying hips<br/>
Black-circled, squinty-lined raccoon eyes<br/>
<br/>
Like a dead spider's legs, her eyelashes curl back<br/>
And frame her eyes, watery and pale<br/>
Her recessed eyes lined in layers of black<br/>
Flirtingly flutter at anyone male<br/>
<br/>
Jingling jewelry wrapped round her neck<br/>
The too-small tank top, cut far too low<br/>
I don't think she knows that she looks like a wreck<br/>
But she can't be hurt by what she doesn't know<br/>
<br/>
A laugh like shattering glass, too fake<br/>
A comeback she likes to pretend is so clever<br/>
What exits her glossy mouth makes my ears ache<br/>
And I wince at every sarcastic \"Whatever\"<br/>
<br/>
But I'll keep quiet, avert my clean eyes<br/>
Block out everything she thinks is so witty<br/>
Ignore her bare, fat, jiggling thighs<br/>
Hope one day she'll realize that pretending's not pretty.</p>
";

include ($Server_incRoot . 'authors/' . $aid . '.inc');
?>